<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>À</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>Á</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>Â</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>Ã</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>Ä</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>Å</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>Æ</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>Ç</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>È</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>É</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>Ê</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>Ë</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>Ì</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>Í</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>Î</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>Ï</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>Ñ</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>Ò</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>Ó</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>Ô</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>C00</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>Õ</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>Ö</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>Ø</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>Ù</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>Ú</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>Û</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>Ü</translation>
    </message>
    <message>
        <source>C08</source>
        <translation>Ý</translation>
    </message>
    <message>
        <source>C09</source>
        <translation>Ð</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">À</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">À</translation>
    </message>
</context>
</TS>
