<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_NUMBER</source>
        <translation>123#</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_EUROPEAN</source>
        <translation>A..Z</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_EU_LATINEXT</source>
        <translation>À..Ý</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_EU_CYRILIC</source>
        <translation>A..Я</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_ENGLISH_A</source>
        <translation>A</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_LATINEXT</source>
        <translation>À</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_ARABIC</source>
        <translation>العربية</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_EU_LATIN</source>
        <translation>ÀÁÂ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_ENGLISH</source>
        <translation>ABC</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_KOREAN</source>
        <translation>한글</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_DELETE</source>
        <translation>Suppr</translation>
    </message>
</context>
</TS>
