<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>Q</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>W</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>E</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>R</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>T</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>Y</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>U</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>I</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>O</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>P</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>A</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>S</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>D</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>F</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>G</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>H</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>J</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>K</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>L</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>Z</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>X</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>C</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>V</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>B</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>N</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>M</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">Q</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">Q</translation>
    </message>
</context>
</TS>
