<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>á</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>à</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>â</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>ã</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>ä</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>å</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>æ</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>ç</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>é</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>è</translation>
    </message>
    <message>
        <source>A10</source>
        <translation>ê</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>ë</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>í</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>ì</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>î</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>ï</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>ñ</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>ó</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>ò</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>ô</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>õ</translation>
    </message>
    <message>
        <source>B10</source>
        <translation>ö</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>1/3</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>ø</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>ú</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>ù</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>û</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>ü</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>ý</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>β</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">á</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">á</translation>
    </message>
</context>
</TS>
