<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>Й</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>Ц</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>У</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>К</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>Ε</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>Н</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>Γ</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>Ш</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>Щ</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>З</translation>
    </message>
    <message>
        <source>A10</source>
        <translation>Х</translation>
    </message>
    <message>
        <source>A11</source>
        <translation>Ъ</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>Ё</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>Ф</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>Ы</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>Β</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>A</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>П</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>Р</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>О</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>Л</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>Д</translation>
    </message>
    <message>
        <source>B10</source>
        <translation>Ж</translation>
    </message>
    <message>
        <source>B11</source>
        <translation>Э</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>Я</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>Ч</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>С</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>М</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>И</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>Т</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>Ь</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>Б</translation>
    </message>
    <message>
        <source>C08</source>
        <translation>Ю</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">Й</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">Й</translation>
    </message>
</context>
</TS>
