<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>й</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>ц</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>у</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>к</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>е</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>н</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>г</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>ш</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>щ</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>з</translation>
    </message>
    <message>
        <source>A10</source>
        <translation>х</translation>
    </message>
    <message>
        <source>A11</source>
        <translation>ъ</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>ё</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>ф</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>ы</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>в</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>a</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>п</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>р</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>о</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>л</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>д</translation>
    </message>
    <message>
        <source>B10</source>
        <translation>ж</translation>
    </message>
    <message>
        <source>B11</source>
        <translation>э</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>я</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>ч</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>с</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>м</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>и</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>т</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>ь</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>б</translation>
    </message>
    <message>
        <source>C08</source>
        <translation>ю</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">й</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">й</translation>
    </message>
</context>
</TS>
