<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>Á</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>Ä</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>Ą</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>Ć</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>Č</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>Ď</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>É</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>Ę</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>Ě</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>Í</translation>
    </message>
    <message>
        <source>A10</source>
        <translation>Ł</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>Ĺ</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>Ľ</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>Ń</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>Ň</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>Ó</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>Ô</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>Ŕ</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>Ř</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>Ś</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>Š</translation>
    </message>
    <message>
        <source>B10</source>
        <translation>Ť</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>2/3</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>Ü</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>Ú</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>Ů</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>Ý</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>Ź</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>Ż</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>Ž</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">Á</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">Á</translation>
    </message>
</context>
</TS>
