<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>á</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>ä</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>ą</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>ć</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>č</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>ď</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>é</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>ę</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>ě</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>í</translation>
    </message>
    <message>
        <source>A10</source>
        <translation>ł</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>ĺ</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>ľ</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>ń</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>ň</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>ó</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>ô</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>ŕ</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>ř</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>ś</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>š</translation>
    </message>
    <message>
        <source>B10</source>
        <translation>ť</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>2/3</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>ü</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>ú</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>ů</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>ý</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>ź</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>ż</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>ž</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">á</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">á</translation>
    </message>
</context>
</TS>
