<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>1</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>2</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>3</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>4</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>5</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>6</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>7</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>8</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>9</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>0</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>&apos;</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>&quot;</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>:</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>;</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>(</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>)</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>_</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>&amp;</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>$</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>1/2  ▶</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>.</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>,</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>?</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>!</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>-</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>/</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>@</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation>1</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation>1</translation>
    </message>
</context>
</TS>
