<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ko">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>ㄱ</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>ㄴ</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>ㄷ</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>ㄹ</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>ㅁ</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>ㅂ</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>ㅅ</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>ㅏ</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>ㅑ</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>ㅓ</translation>
    </message>
    <message>
        <source>A10</source>
        <translation>ㅕ</translation>
    </message>
    <message>
        <source>A11</source>
        <translation>ㅗ</translation>
    </message>
    <message>
        <source>A12</source>
        <translation>ㅛ</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>ㅇ</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>ㅈ</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>ㅊ</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>ㅋ</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>ㅌ</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>ㅍ</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>ㅎ</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>ㅜ</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>ㅠ</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>ㅡ</translation>
    </message>
    <message>
        <source>B10</source>
        <translation>ㅣ</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>ㄲ</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>ㄸ</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>ㅃ</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>ㅆ</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>ㅉ</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>ㅐ</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>ㅔ</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>ㅒ</translation>
    </message>
    <message>
        <source>C08</source>
        <translation>ㅖ</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">ㄱ</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">ㄱ</translation>
    </message>
</context>
</TS>
