<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>A00</source>
        <translation>ض</translation>
    </message>
    <message>
        <source>A01</source>
        <translation>ص</translation>
    </message>
    <message>
        <source>A02</source>
        <translation>ث</translation>
    </message>
    <message>
        <source>A03</source>
        <translation>ق</translation>
    </message>
    <message>
        <source>A04</source>
        <translation>ف</translation>
    </message>
    <message>
        <source>A05</source>
        <translation>إ</translation>
    </message>
    <message>
        <source>A06</source>
        <translation>ع</translation>
    </message>
    <message>
        <source>A07</source>
        <translation>ه</translation>
    </message>
    <message>
        <source>A08</source>
        <translation>خ</translation>
    </message>
    <message>
        <source>A09</source>
        <translation>؛</translation>
    </message>
    <message>
        <source>A10</source>
        <translation>ج</translation>
    </message>
    <message>
        <source>A11</source>
        <translation>د</translation>
    </message>
    <message>
        <source>B00</source>
        <translation>ش</translation>
    </message>
    <message>
        <source>B01</source>
        <translation>س</translation>
    </message>
    <message>
        <source>B02</source>
        <translation>ي</translation>
    </message>
    <message>
        <source>B03</source>
        <translation>ب</translation>
    </message>
    <message>
        <source>B04</source>
        <translation>ل</translation>
    </message>
    <message>
        <source>B05</source>
        <translation>أ</translation>
    </message>
    <message>
        <source>B06</source>
        <translation>ـ</translation>
    </message>
    <message>
        <source>B07</source>
        <translation>،</translation>
    </message>
    <message>
        <source>B08</source>
        <translation>م</translation>
    </message>
    <message>
        <source>B09</source>
        <translation>ك</translation>
    </message>
    <message>
        <source>B10</source>
        <translation>ط</translation>
    </message>
    <message>
        <source>C00</source>
        <translation>ئ</translation>
    </message>
    <message>
        <source>C01</source>
        <translation>ء</translation>
    </message>
    <message>
        <source>C02</source>
        <translation>ؤ</translation>
    </message>
    <message>
        <source>C03</source>
        <translation>ر</translation>
    </message>
    <message>
        <source>C04</source>
        <translation>/</translation>
    </message>
    <message>
        <source>C05</source>
        <translation>آ</translation>
    </message>
    <message>
        <source>C06</source>
        <translation>&apos;</translation>
    </message>
    <message>
        <source>C07</source>
        <translation>و</translation>
    </message>
    <message>
        <source>C08</source>
        <translation>ز</translation>
    </message>
    <message>
        <source>C09</source>
        <translation>؟</translation>
    </message>
    <message>
        <source>U00</source>
        <translation> </translation>
    </message>
    <message>
        <source>U01</source>
        <translation> </translation>
    </message>
    <message>
        <source>U02</source>
        <translation> </translation>
    </message>
    <message>
        <source>U03</source>
        <translation> </translation>
    </message>
    <message>
        <source>U04</source>
        <translation> </translation>
    </message>
    <message>
        <source>U05</source>
        <translation> </translation>
    </message>
    <message>
        <source>U06</source>
        <translation> </translation>
    </message>
    <message>
        <source>U07</source>
        <translation> </translation>
    </message>
    <message>
        <source>U08</source>
        <translation> </translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenNumbers</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">ض</translation>
    </message>
</context>
<context>
    <name>DHAVN_QwertyKeypad_ScreenSymbols</name>
    <message>
        <source>A00</source>
        <translation type="unfinished">ض</translation>
    </message>
</context>
</TS>
