/*
* Copyright (c) 2001 Gracenote.
*
* This software may not be used in any way or distributed without
* permission. All rights reserved.
*
* Some code herein may be covered by US and international patents.
*/

/*
* gn_error_values.h - Error values, used and returned by each package.
*/

#ifndef _GN_ERROR_VALUES_H_
#define _GN_ERROR_VALUES_H_

/*
* Dependencies
*/

#include "gn_error_codes.h"


#ifdef __cplusplus
extern "C"{
#endif


/*
* Constants
*/


/* Generic errors */
#define	GENERR_NoError						0
#define	GENERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_NoMemory)
#define	GENERR_NotFound						GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_NotFound)
#define	GENERR_IOError						GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_IOError)
#define	GENERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_InvalidArg)
#define	GENERR_Busy							GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_Busy)
#define	GENERR_NotInited					GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_NotInited)
#define	GENERR_OVERFLOW						GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_OVERFLOW)
#define	GENERR_Unknown						GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_Unknown)
#define	GENERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_BufferTooSmall)
#define	GENERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_InvalidFormat)
#define	GENERR_InitFailed					GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_InitFailed)
#define	GENERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_Generic, GNERR_UnsupportedFunctionality)



/* Errors returned from the DB Engine */
#define DBERR_NoError						0
#define DBERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_InvalidArg)
#define DBERR_NotFound						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_NotFound)
#define DBERR_MemoryErr						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_NoMemory)
#define DBERR_IOErr							GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_IOError)
#define DBERR_NestedCall					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_NestedCall)
#define DBERR_PermissionError				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_PermissionError)
#define DBERR_ReadErr						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_ReadErr)
#define DBERR_WriteErr						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_WriteErr)
#define DBERR_UnknownVersion				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_UnknownVersion)
#define DBERR_InvalidFile					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_InvalidFile)
#define DBERR_AlreadyAdded					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_AlreadyAdded)
#define DBERR_InvalidBlock					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_InvalidBlock)
#define DBERR_Aborted						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_Aborted)
#define DBERR_FileExists					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_FileExists)
#define DBERR_NoSpace						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_NoSpace)
#define	DBERR_BadIndex						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_BadIndex)
#define	DBERR_BadFreeList					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_BadFreeList)
#define	DBERR_BadRecord						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_BadRecord)
#define	DBERR_BadBlock						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_BadBlock)
#define	DBERR_IndexPastEOF					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_IndexPastEOF)
#define	DBERR_RecordPastEOF					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_RecordPastEOF)
#define	DBERR_IndexInFreeList				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_IndexInFreeList)
#define	DBERR_RecordInFreeList				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_RecordInFreeList)
#define	DBERR_BlockInFreeList				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_BlockInFreeList)
#define	DBERR_IncompatibleDBs				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_IncompatibleDBs)
#define	DBERR_KeyNotRead					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_KeyNotRead)
#define	DBERR_InvalidByteOrder				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_InvalidByteOrder)
#define	DBERR_UnknownFSError				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_UnknownFSError)
#define	DBERR_InvalidIterator				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_InvalidIterator)
#define	DBERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_UnsupportedFunctionality)
#define	DBERR_BadHeader						GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_BadHeader)
#define	DBERR_CriticalSection				GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_CriticalSection)
#define	DBERR_ThreadError					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_ThreadError)
#define	DBERR_ReadLocked					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_ReadLocked)
#define	DBERR_WriteLocked					GNERR_MAKE_VALUE(GNPKG_DBEngine, GNERR_WriteLocked)

/* Errors returned from the micro XML subsystem */
#define kXMLNoError							0
#define kXMLOutOfMemoryError				GNERR_MAKE_VALUE(GNPKG_XML, GNERR_NoMemory)
#define kXMLInvalidParamError				GNERR_MAKE_VALUE(GNPKG_XML, GNERR_InvalidArg)
#define kXMLSyntaxError						GNERR_MAKE_VALUE(GNPKG_XML, GNERR_XMLSyntaxError)
#define kIllegalXMLCharacterError			GNERR_MAKE_VALUE(GNPKG_XML, GNERR_IllegalXMLCharacter)
#define kXMLUnexpectedEndOfInputError		GNERR_MAKE_VALUE(GNPKG_XML, GNERR_XMLUnexpectedEndOfInput)
#define kXMLNotFound						GNERR_MAKE_VALUE(GNPKG_XML, GNERR_NotFound)

/* Errors returned from Data Translator subsystem */
#define XLTERR_NoError						0
#define XLTERR_NotInited					GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_NotInited)
#define XLTERR_Busy							GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_Busy)
#define XLTERR_InvalidParam					GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_InvalidArg)
#define XLTERR_OutOfMemory					GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_NoMemory)
#define XLTERR_IckyError					GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_IckyError)
#define XLTERR_BadFormat					GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_BadXMLFormat)
#define XLTERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_UnsupportedFunctionality)
#define XLTERR_Unknown						GNERR_MAKE_VALUE(GNPKG_Translator, GNERR_Unknown)

/* Errors returned from Embedded Database subsystem */
#define EDBERR_NoError						0
#define EDBERR_NotInited					GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_NotInited)
#define EDBERR_Busy							GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_Busy)
#define EDBERR_NotFound						GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_NotFound)
#define EDBERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_InvalidArg)
#define EDBERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_NoMemory)
#define EDBERR_IOError						GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_IOError)
#define EDBERR_DataError					GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_DataError)
#define EDBERR_Decrypt						GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_Decrypt)
#define EDBERR_DecryptFmt					GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_DecryptFmt)
#define EDBERR_UnComp						GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_UnComp)
#define EDBERR_UnCompFmt					GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_UnCompFmt)
#define EDBERR_InitedForLookups				GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_InitedForLookups)
#define EDBERR_InitedForUpdates				GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_InitedForUpdates)
#define EDBERR_ErrorWritingData				GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_ErrorWritingData)
#define EDBERR_ErrorWritingIndex			GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_ErrorWritingIndex)
#define EDBERR_NoRecordActive				GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_NoRecordActive)
#define EDBERR_NotInitializedForUpdates		GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_NotInitializedForUpdates)
#define EDBERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_UnsupportedFunctionality)
#define EDBERR_NullHandleFromOpen			GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_NullHandleFromOpen)
#define EDBIMERR_ListModelNotSet			GNERR_MAKE_VALUE(GNPKG_EmbeddedDB, GNERR_ListModelNotSet)

/* Errors returned from TOC lookup subsystem */
#define TLERR_NoError						0
#define TLERR_NotInited						GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_NotInited)
#define TLERR_Busy							GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_Busy)
#define TLERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_NoMemory)
#define TLERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_InvalidArg)
#define TLERR_IOError						GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_IOError)
#define TLERR_NotFound						GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_NotFound)
#define TLERR_InvalidTOC					GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_InvalidTOC)
#define TLERR_BadResultFormat				GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_BadResultFormat)
#define TLERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_UnsupportedFunctionality)
#define TLERR_NoMatch						GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_NoMatch)
#define TLERR_IckyError						GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_IckyError)
#define TLERR_MissingClassicalData			GNERR_MAKE_VALUE(GNPKG_TOCLookup, GNERR_MissingClassicalData)

/* Errors returned from Cryptographic subsystem */
#define CRYPTERR_NoError					0
#define CRYPTERR_NotInited					GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_NotInited)
#define CRYPTERR_Busy						GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_Busy)
#define CRYPTERR_NotFound					GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_NotFound)
#define CRYPTERR_InvalidArg 				GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_InvalidArg)
#define CRYPTERR_MemoryError				GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_NoMemory)
#define CRYPTERR_IOError					GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_IOError)
#define CRYPTERR_UnsupportedAlg				GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_UnsupportedAlg)
#define CRYPTERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_BufferTooSmall)
#define CRYPTERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_InvalidFormat)
#define CRYPTERR_IckyError					GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_IckyError)
#define CRYPTERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_Crypto, GNERR_UnsupportedFunctionality)

/* Errors returned from the online protocol module */
#define OPERR_NoError						0
#define OPERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_InvalidArg)
#define OPERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoMemory)
#define OPERR_Busy							GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_Busy)
#define OPERR_NotRegistered					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NotRegistered)
#define OPERR_WrongServerPublicKey			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_WrongServerPublicKey)
#define OPERR_UnknownCompression			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_UnknownCompression)
#define OPERR_UnknownEncryption				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_UnknownEncryption)
#define OPERR_UnknownEncoding				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_UnknownEncoding)
#define OPERR_NotCDDBMSG					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NotCDDBMSG)
#define OPERR_NoPROTOCOLElement				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoPROTOCOLElement)
#define OPERR_NoSTATUSElement				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoSTATUSElement)
#define OPERR_NoDATAElement					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoDATAElement)
#define OPERR_NoDataContents				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoDataContents)
#define OPERR_NoENCODINGElement				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoENCODINGElement)
#define OPERR_NoENCRYPTIONElement			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoENCRYPTIONElement)
#define OPERR_NoCOMPRESSIONElement			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoCOMPRESSIONElement)
#define OPERR_NotRESULTS					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NotRESULTS)
#define OPERR_RESULTNotFound				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_RESULTNotFound)
#define OPERR_Base64Encode					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_Base64Encode)
#define OPERR_Base64Decode					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_Base64Decode)
#define OPERR_ZipCompress					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ZipCompress)
#define OPERR_ZipUncompress					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ZipUncompress)
#define OPERR_WrongEncryptionStep			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_WrongEncryptionStep)
#define OPERR_MissingCLNTKEY				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_MissingCLNTKEY)
#define OPERR_MissingSRVRKEY				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_MissingSRVRKEY)
#define OPERR_MissingKeyAlgorithm			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_MissingKeyAlgorithm)
#define OPERR_UnknownKeyAlgorithm			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_UnknownKeyAlgorithm)
#define OPERR_WrongClientPublicKey			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_WrongClientPublicKey)
#define OPERR_MissingKeyValue				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_MissingKeyValue)
#define OPERR_NoServerResponse				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoServerResponse)
#define OPERR_BadRegResultFormat			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_BadRegResultFormat)
#define OPERR_KeyTooLarge					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_KeyTooLarge)
#define OPERR_MissingSTATUSCODE				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_MissingSTATUSCODE)
#define OPERR_ServerError					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerError)
#define OPERR_NotRESULT						GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NotRESULT)
#define OPERR_MissingRESULTCODE				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_MissingRESULTCODE)
#define OPERR_NoTransaction					GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoTransaction)
#define OPERR_CRCError						GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_CRCError)
#define OPERR_IckyError						GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_IckyError)
#define OPERR_UnsupportedOption				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_UnsupportedOption)
#define OPERR_ServerChecksumMismatch		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerChecksumMismatch)
#define OPERR_ServerEncryptionError			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerEncryptionError)
#define OPERR_ServerDecryptionError			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerDecryptionError)
#define OPERR_ServerMalformedInput			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerMalformedInput)
#define OPERR_ServerConcurrencyNotInitialized	GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerConcurrencyNotInitialized)
#define OPERR_ServerUnsupportedCommand		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerUnsupportedCommand)
#define OPERR_ServerDVDLookupError			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerDVDLookupError)
#define OPERR_ServerArgumentOutOfRange		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerArgumentOutOfRange)
#define OPERR_ServerCDDBServerNotFound		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerCDDBServerNotFound)
#define OPERR_ServerSocketCreateFailed		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerSocketCreateFailed)
#define OPERR_ServerCDDBServerResponseGarbled	GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerCDDBServerResponseGarbled)
#define OPERR_ServerCDDBServerTimeout		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerCDDBServerTimeout)
#define OPERR_ServerCDDBHTTPError			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerCDDBHTTPError)
#define OPERR_ServerCDDBServiceError		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerCDDBServiceError)
#define OPERR_ServerCDDBServiceInvalidField	GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerCDDBServiceInvalidField)
#define OPERR_ServerCDDBQueryLimitReached	GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerCDDBQueryLimitReached)
#define OPERR_ServerInvalidArgument			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ServerInvalidArgument)
#define OPERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_UnsupportedFunctionality)
#define OPERR_InvalidRegFile				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_InvalidRegFile)
#define OPERR_NoRegistrationFile			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_NoRegistrationFile)
#define OPERR_InvalidRegistration			GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_InvalidRegistration)
#define	OPERR_ClientIDNotSet				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ClientIDNotSet)
#define	OPERR_ClientIDTagNotSet				GNERR_MAKE_VALUE(GNPKG_OnlineProtocol, GNERR_ClientIDTagNotSet)



/* Errors returned from the Dynamic Buffer package */
#define DYN_BUF_NO_ERROR					0
#define DYN_BUF_OUT_OF_MEMORY_ERROR			GNERR_MAKE_VALUE(GNPKG_DynBuf, GNERR_NoMemory)
#define DYN_BUF_INVALID_PARAM_ERROR			GNERR_MAKE_VALUE(GNPKG_DynBuf, GNERR_InvalidArg)

/* Errors returned from the Updater subsystem */
#define UPDERR_NotInited					GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_NotInited)
#define UPDERR_Busy							GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_Busy)
#define UPDERR_NotFound						GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_NotFound)
#define UPDERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_InvalidArg)
#define UPDERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_NoMemory)
#define UPDERR_IOError						GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_IOError)
#define UPDERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_InvalidFormat)
#define UPDERR_BadResultFormat				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_BadResultFormat)
#define UPDERR_IncompleteUpdate				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_IncompleteUpdate)
#define UPDERR_IckyError					GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_IckyError)
#define UPDERR_FileNotFound					GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_FileNotFound)
#define UPDERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_UnsupportedFunctionality)
#define UPDERR_ArrayOverflow				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_ArrayOverflow)
#define UPDERR_UpdFileBaseDBRevision		GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_UpdFileBaseDBRevision)
#define UPDERR_UpdateLevelMismatch			GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_UpdateLevelMismatch)
#define UPDERR_UpdateFileType				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_UpdateFileType)
#define UPDERR_InvalidByteOrder				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_InvalidByteOrder)
#define UPDERR_CRCError                     GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_CRCError)
#define UPDERR_BaseDataNotFound				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_BaseDataNotFound)
#define UPDERR_CorrelatesNotFound			GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_CorrelatesNotFound)
#define UPDERR_ListsNotFound				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_ListsNotFound)
#define UPDERR_ContribTblNotFound			GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_ContribTblNotFound)
#define UPDERR_GenreTblNotFound				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_GenreTblNotFound)
#define UPDERR_PCXNotFound					GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_PCXNotFound)
#define UPDERR_InventoryFileNotFound		GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_InventoryFileNotFound)
#define UPDERR_PDLPresetsNotFound			GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_PDLPresetsNotFound)
#define UPDERR_AlbumTblNotFound				GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_AlbumTblNotFound)
#define UPDERR_GenreArtBaseIndexNotFound	GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_GenreArtBaseIndexNotFound)
#define UPDERR_GenreArtBaseDataNotFound		GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_GenreArtBaseDataNotFound)
#define UPDERR_AudioWorkRecordsNotFound		GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_AudioWorkRecordsNotFound)
#define UPDERR_FPX_NotFound					GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_FPX_NotFound)
#define UPDERR_CoverArtBaseIndexNotFound	GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_CoverArtBaseIndexNotFound)
#define UPDERR_CoverArtBaseDataNotFound		GNERR_MAKE_VALUE(GNPKG_Updater, GNERR_CoverArtBaseDataNotFound)	

/* Errors returned from the utilities package */
#define UTILERR_NoError						0
#define UTILERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Utils, GNERR_InvalidArg)
#define UTILERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_Utils, GNERR_NoMemory)
#define UTILERR_UnknownChecksumAlg			GNERR_MAKE_VALUE(GNPKG_Utils, GNERR_UnknownChecksumAlg)
#define UTILERR_ChecksumMismatch			GNERR_MAKE_VALUE(GNPKG_Utils, GNERR_ChecksumMismatch)
#define UTILERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_Utils, GNERR_UnsupportedFunctionality)
#define UTILERR_IOError						GNERR_MAKE_VALUE(GNPKG_Utils, GNERR_IOError)
#define UTILERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_Utils, GNERR_InvalidFormat)

/* Errors returned from the "system" package */
#define SYSERR_NotInited					GNERR_MAKE_VALUE(GNPKG_System, GNERR_NotInited)
#define SYSERR_Busy							GNERR_MAKE_VALUE(GNPKG_System, GNERR_Busy)
#define SYSERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_System, GNERR_NoMemory)
#define SYSERR_InitError					GNERR_MAKE_VALUE(GNPKG_System, GNERR_InitFailed)
#define SYSERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_System, GNERR_UnsupportedFunctionality)
#define SYSERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_System, GNERR_InvalidArg)
#define SYSERR_NotFound						GNERR_MAKE_VALUE(GNPKG_System, GNERR_NotFound)
#define SYSERR_ArrayOverflow				GNERR_MAKE_VALUE(GNPKG_System, GNERR_ArrayOverflow)
#define SYSERR_Missing_Client_ID			GNERR_MAKE_VALUE(GNPKG_System, GNERR_Missing_Client_ID)
#define SYSERR_ClientIDNotSet				GNERR_MAKE_VALUE(GNPKG_System, GNERR_ClientIDNotSet)
#define SYSERR_ClientIDTagNotSet			GNERR_MAKE_VALUE(GNPKG_System, GNERR_ClientIDTagNotSet)
#define SYSERR_LDACKeyNotSet				GNERR_MAKE_VALUE(GNPKG_System, GNERR_LDACKeyNotSet)
#define SYSERR_LDACKeyUnsupportedVersion	GNERR_MAKE_VALUE(GNPKG_System, GNERR_LDACKeyUnsupportedVersion)
#define SYSERR_LDACKeyMagicNumber			GNERR_MAKE_VALUE(GNPKG_System, GNERR_LDACKeyMagicNumber)
#define SYSERR_LDACKeyPayloadLength			GNERR_MAKE_VALUE(GNPKG_System, GNERR_LDACKeyPayloadLength)
#define SYSERR_LDACKeyInvalidFormat     	GNERR_MAKE_VALUE(GNPKG_System, GNERR_LDACKeyInvalidFormat)
#define SYSERR_ConfigNull					GNERR_MAKE_VALUE(GNPKG_System, GNERR_ConfigNull)
#define SYSERR_InvalidFeatureConfig			GNERR_MAKE_VALUE(GNPKG_System, GNERR_InvalidFeatureConfig)


/* Errors returned from, and status codes set by, the validation module. */
#define VALIDATEERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_Validation, GNERR_InvalidArg)
#define VALIDATEERR_NoMemory				GNERR_MAKE_VALUE(GNPKG_Validation, GNERR_NoMemory)
#define VALIDATEERR_NotInited				GNERR_MAKE_VALUE(GNPKG_Validation, GNERR_NotInited)
#define VALIDATEERR_InvalidDatabase			GNERR_MAKE_VALUE(GNPKG_Validation, GNERR_InvalidDatabase)
#define VALIDATEERR_InvalidActionBaseRpl    GNERR_MAKE_VALUE(GNPKG_Validation, GNERR_InvalidActionBaseRpl)
#define VALIDATEERR_FileNameNotSet			GNERR_MAKE_VALUE(GNPKG_Validation, GNERR_FileNameNotSet)
#define VALIDATEERR_IckyError				GNERR_MAKE_VALUE(GNPKG_Validation, GNERR_IckyError)

/* Errors returned from Integrity Manager */
#define EDBIMERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoMemory)
#define EDBIMERR_NotFound					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NotFound)
#define EDBIMERR_IOError					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_IOError)
#define EDBIMERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidArg)
#define EDBIMERR_Busy						GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_Busy)
#define EDBIMERR_NotInited					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NotInited)
#define EDBIMERR_OVERFLOW					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_OVERFLOW)
#define EDBIMERR_Unknown					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_Unknown)
#define EDBIMERR_CorruptData				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_CorruptData)
#define EDBIMERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidFormat)
#define EDBIMERR_InvalidData				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidData)
#define EDBIMERR_LostBackup					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_LostBackup)
#define EDBIMERR_IckyError					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_IckyError)
#define EDBIMERR_CRCError					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_CRCError)
#define EDBIMERR_NoLiveUpdateDB				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoLiveUpdateDB)
#define EDBIMERR_NoBackupUpdateDB			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoBackupUpdateDB)
#define EDBIMERR_NoUpdateDB					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoUpdateDB)
#define EDBIMERR_BadUpdateDB				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BadUpdateDB)
#define EDBIMERR_BackupOutOfSync			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BackupOutOfSync)
#define EDBIMERR_CoreDBError				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_CoreDBError)
#define EDBIMERR_LiveUpdateDBError			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_LiveUpdateDBError)
#define EDBIMERR_BackupUpdateDBError		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BackupUpdateDBError)
#define EDBIMERR_UpdateDBError				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_UpdateDBError)
#define EDBIMERR_NoLiveCache				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoLiveCache)
#define EDBIMERR_NoBackupCache				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoBackupCache)
#define EDBIMERR_LiveCacheError				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_LiveCacheError)
#define EDBIMERR_BackupCacheError			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BackupCacheError)
#define EDBIMERR_CacheError					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_CacheError)
#define EDBIMERR_LiveUpdateCRCError			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_LiveUpdateCRCError)
#define EDBIMERR_BackupUpdateCRCError		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BackupUpdateCRCError)
#define EDBIMERR_LiveCacheCRCError			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_LiveCacheCRCError)
#define EDBIMERR_BackupCacheCRCError		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BackupCacheCRCError)
#define EDBIMERR_NotInitializedForUpdates	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NotInitializedForUpdates)
#define EDBIMERR_InvalidDataFormatVersion	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidDataFormatVersion)
#define EDBIMERR_CodeDataMismatch			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_CodeDataMismatch)
#define EDBIMERR_UpdateLevelCountTooHigh	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_UpdateLevelCountTooHigh)
#define EDBIMERR_InvalidUniversalHdrMagic	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidUniversalHdrMagic)
#define EDBIMERR_InvalidByteOrder			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidByteOrder)
#define EDBIMERR_IncorrectFileType			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_IncorrectFileType)
#define EDBIMERR_UnknownUniversalHeaderErr	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_UnknownUniversalHeaderErr)
#define EDBIMERR_NoDB						GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoDB)
#define EDBIMERR_FileNotFound				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_FileNotFound)
#define EDBIMERR_PartialDB					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_PartialDB)
#define EDBIMERR_NoLiveDB					GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_NoLiveDB)
#define EDBIMERR_IllegalEndian				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_IllegalEndian)
#define EDBIMERR_IncompleteImplementation	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_IncompleteImplementation)
#define EDBIMERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_UnsupportedFunctionality)
#define EDBIMERR_UninitializedTable			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_UninitializedTable)
#define EDBIMERR_InvalidInstallProfile		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidInstallProfile)
#define EDBIMERR_DatabaseRevisionError		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_DatabaseRevisionError)
#define EDBIMERR_MultipleBaseDBTables		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MultipleBaseDBTables)
#define EDBIMERR_MultipleUpdDBTables		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MultipleUpdDBTables)
#define EDBIMERR_MissingBaseDBTable			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MissingBaseDBTable)
#define EDBIMERR_MissingUpdDBTable			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MissingUpdDBTable)
#define EDBIMERR_BaseUpdFileTypeMismatch	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BaseUpdFileTypeMismatch)
#define EDBIMERR_MaxFileNameSize			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MaxFileNameSize)
#define EDBIMERR_MissingFilename			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MissingFilename)
#define EDBIMERR_FilesAlreadyOpen			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_FilesAlreadyOpen)
#define EDBIMERR_UnknownCollection			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_UnknownCollection)
#define EDBIMERR_RevertMissingBackup		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_RevertMissingBackup)
#define EDBIMERR_InvalidConfigXMLFile		GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_InvalidConfigXMLFile)
#define EDBIMERR_CollectionConfigSynchErr	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_CollectionConfigSynchErr)
#define EDBIMERR_FileTableNotFlatOrIndex	GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_FileTableNotFlatOrIndex)
#define EDBIMERR_MaxCollectionID			GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MaxCollectionID)
#define EDBIMERR_BadListFile				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_BadListFile)
#define EDBIMERR_MLDBFilesExist				GNERR_MAKE_VALUE(GNPKG_EmbeddedDBIM, GNERR_MLDBFilesExist)

/* Values returned from the universal header subsystem. */
#define UNIVHDRERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_InvalidArg)
#define UNIVHDRERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_NoMemory)
#define UNIVHDRERR_IOError						GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_IOError)
#define UNIVHDRERR_InvalidUniversalDataFormat	GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_InvalidUniversalDataFormat)
#define UNIVHDRERR_CRCError						GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_CRCError)
#define UNIVHDRERR_IckyError					GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_IckyError)
#define UNIVHDRERR_UpdateLevelCountTooHigh		GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_UpdateLevelCountTooHigh)
#define UNIVHDRERR_BadTimestampFormat			GNERR_MAKE_VALUE(GNPKG_UniversalHeader, GNERR_BadTimestampFormat)

/* Errors returned from Local Data Cache subsystem */
#define CACHE_ERR_NoError					0
#define CACHE_ERR_NotInited					GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_NotInited)
#define CACHE_ERR_Busy						GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_Busy)
#define CACHE_ERR_NotFound					GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_NotFound)
#define CACHE_ERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_InvalidArg)
#define CACHE_ERR_InvalidTOC				GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_InvalidTOC)
#define CACHE_ERR_BadXMLFormat				GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_BadXMLFormat)
#define CACHE_ERR_MemoryError				GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_NoMemory)
#define CACHE_ERR_IOError					GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_IOError)
#define CACHE_ERR_DataError					GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_CacheDataError)
#define CACHE_ERR_InitedForLookups			GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_CacheInitedForLookups)
#define CACHE_ERR_InitedForUpdates			GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_CacheInitedForUpdates)
#define CACHE_ERR_IckyError					GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_IckyError)
#define CACHE_ERR_NoCache					GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_NoCache)
#define CACHE_ERR_UnsupportedOption			GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_UnsupportedOption)
#define CACHE_ERR_BufferTooSmall			GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_BufferTooSmall)
#define CACHE_ERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_UnsupportedFunctionality)
#define CACHE_ERR_AlreadyAdded				GNERR_MAKE_VALUE(GNPKG_LocalDataCache, GNERR_AlreadyAdded)

/* Errors returned from DVD lookup subsystem */
#define DVDERR_NoError						0
#define DVDERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_NoMemory)
#define DVDERR_IOError						GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_IOError)
#define DVDERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_InvalidArg)
#define DVDERR_NotFound						GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_NotFound)
#define DVDERR_InvalidFile					GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_InvalidFile)
#define DVDERR_IckyError					GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_IckyError)
#define DVDERR_Unsupported					GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_Unsupported)
#define DVDERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_BufferTooSmall)
#define DVDERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_DVDEngine, GNERR_UnsupportedFunctionality)

/* Errors retured from the embedded playlist db engine */
#define	PLMDB_SUCCESS						0
#define	PLMDBERR_INVALIDARG					GNERR_MAKE_VALUE(GNPKG_PLDBEngine, GNERR_InvalidArg)
#define	PLMDBERR_BADVERSION					GNERR_MAKE_VALUE(GNPKG_PLDBEngine, GNERR_UnknownVersion)
#define	PLMDBERR_NOMEMORY					GNERR_MAKE_VALUE(GNPKG_PLDBEngine, GNERR_NoMemory)
#define	PLMDBERR_INVALIDKEY					GNERR_MAKE_VALUE(GNPKG_PLDBEngine, GNERR_InvalidKey)
#define PLMDBERR_BAD_RECORD					GNERR_MAKE_VALUE(GNPKG_PLDBEngine, GNERR_BadRecord)
#define PLMDBERR_BAD_INDEX					GNERR_MAKE_VALUE(GNPKG_PLDBEngine, GNERR_BadIndex)
#define PLMDBERR_NOTFOUND					GNERR_MAKE_VALUE(GNPKG_PLDBEngine, GNERR_NotFound)

/* Errors returned from the playlist management engine */
#define PLMERR_NoError						0
#define PLMERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_InvalidArg)
#define PLMERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_NoMemory)
#define PLMERR_NotFound						GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_NotFound)
#define PLMERR_Unknown						GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_Unknown)
#define PLMERR_NoMatch						GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_NoMatch)
#define PLMERR_NotInited					GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_NotInited)
#define PLMERR_Busy							GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_Busy)
#define PLMERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_UnsupportedFunctionality)
#define PLMERR_Exists						GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_AlreadyAdded)
#define PLMERR_IOError						GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_IOError)
#define PLMERR_NullHandleFromOpen			GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_NullHandleFromOpen)
#define PLMERR_CorruptEncryptData			GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_CorruptEncryptData)
#define PLMERR_InvalidUniversalDataFormat	GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_InvalidUniversalDataFormat)
#define PLMERR_CollectionNotOpened			GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_CollectionNotOpened)
#define PLMERR_OperationCanceled			GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_OperationCanceled)
#define PLMERR_DataError					GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_DataError)
#define PLMERR_PermissionError				GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_PermissionError)
#define PLMERR_InvalidArrayObject			GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_InvalidArrayObject)
#define PLMERR_InvalidArrayIndex			GNERR_MAKE_VALUE(GNPKG_PLMEngine, GNERR_InvalidArrayIndex)



/* Errors returned from the GCSP library */
#define GCSPERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidArg)
#define GCSPERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_NoMemory)
#define GCSPERR_IOError						GNERR_MAKE_VALUE(GNPKG_GCSP, GENERR_IOError)
#define GCSPERR_InvalidHeaderFormat			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_HTTPInvalidHeaderFormat)
#define GCSPERR_InvalidKey					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidKey)
#define GCSPERR_ExpiredKey					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_ExpiredKey)
#define GCSPERR_CorruptEncryptData			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_CorruptEncryptData)
#define GCSPERR_CorruptCompressData			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_CorruptCompressData)
#define GCSPERR_BadXMLFormat				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_BadXMLFormat)
#define GCSPERR_NotFound					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_NotFound)
#define GCSPERR_RequestError				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_RequestError)
#define GCSPERR_CommandError				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_CommandError)
#define GCSPERR_NoRegistration				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_NoRegistration)
#define GCSPERR_QuotaExceeded				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_QuotaExceeded)
#define GCSPERR_ClientCompression			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_ClientCompression)
#define GCSPERR_ClientEncryption			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_ClientEncryption)
#define GCSPERR_GEMPError					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_GEMPError)
#define GCSPERR_InvalidRequestCommand		GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidRequestCommand)
#define GCSPERR_MissingRequestCmdField		GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_MissingRequestCmdField)
#define GCSPERR_InvalidRequestCmdArg		GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidRequestCmdArg)
#define GCSPERR_RequestCmdServerError		GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_RequestCmdServerError)
#define GCSPERR_RequestCmdClientError		GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_RequestCmdClientError)
#define GCSPERR_RequestCmdNoReg				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_RequestCmdNoReg)
#define GCSPERR_RequestCmdAlreadyReg		GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_RequestCmdAlreadyReg)
#define GCSPERR_BadRequest					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_BadRequest)
#define GCSPERR_BadReqClient				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_BadReqClient)
#define GCSPERR_BadReqServer				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_BadReqServer)
#define GCSPERR_BadReqInvalidArg			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_BadReqInvalidArg)
#define GCSPERR_InvalidUser					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidUser)
#define GCSPERR_InvalidClient				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidClient)
#define GCSPERR_MissingField				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_MissingField)
#define GCSPERR_InvalidArgument				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidArgument)
#define GCSPERR_InvalidRegKey				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_InvalidRegKey)
#define GCSPERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_UnsupportedFunctionality)
#define GCSPERR_EmptyResponse				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_EmptyResponse)
#define GCSPERR_Missing_Client_ID			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_Missing_Client_ID)
#define GCSPERR_Missing_Client_ID_Tag		GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_Missing_Client_ID_Tag)
#define GCSPERR_Missing_User_ID_Tag			GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_Missing_User_ID_Tag)
#define GCSPERR_MissingSRVRKEY				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_MissingSRVRKEY)
#define GCSPERR_IckyError					GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_IckyError)
#define	GCSPERR_BadRangeSpec				GNERR_MAKE_VALUE(GNPKG_GCSP, GNERR_BadRangeSpec)

/* Errors returned from the compression library */
#define COMPERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Compression, GNERR_InvalidArg)
#define COMPERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_Compression, GNERR_NoMemory)
#define COMPERR_UnknownCompressionType		GNERR_MAKE_VALUE(GNPKG_Compression, GNERR_UnknownCompressionType)
#define COMPERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_Compression, GNERR_BufferTooSmall)
#define COMPERR_DataError					GNERR_MAKE_VALUE(GNPKG_Compression, GNERR_DataError)
#define COMPERR_BadVersion					GNERR_MAKE_VALUE(GNPKG_Compression, GNERR_UnknownVersion)

/* Errors returned from the checksum library */
#define CKSUMERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Checksum, GNERR_InvalidArg)
#define CKSUMERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_Checksum, GNERR_NoMemory)

/* Errors returned from the Music ID library */
#define GNMUSICIDERR_NoError				0
#define GNMUSICIDERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_InvalidArg)
#define GNMUSICIDERR_Unsupported			GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_UnsupportedFunctionality)
#define GNMUSICIDERR_MemoryError			GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_NoMemory)
#define GNMUSICIDERR_NotReady				GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_NotReady)
#define GNMUSICIDERR_NotInited				GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_NotInited)
#define GNMUSICIDERR_IckyError				GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_IckyError)
#define GNMUSICIDERR_UnsupportedAlg			GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_UnsupportedFPAlg)
#define GNMUSICIDERR_Busy					GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_Busy)
#define GNMUSICIDERR_FileExists				GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_FileExists)
#define GNMUSICIDERR_InvalidFormat			GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_InvalidFormat)
#define GNMUSICIDERR_IncompatibleDBs		GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_IncompatibleDBs)
#define GNMUSICIDERR_FileNotFound   		GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_FileNotFound)
#define GNMUSICIDERR_NothingToDo			GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_NothingToDo)
#define GNMUSICIDERR_ColumnHasNoZones		GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_ColumnHasNoZones)
#define GNMUSICIDERR_EndOfSearch			GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_EndOfSearch)
#define GNMUSICIDERR_IllegalFingerprint		GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_IllegalFingerprint)
#define GNMUSICIDERR_Aborted				GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_Aborted)
#define GNMUSICIDERR_NullHandleFromOpen		GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_NullHandleFromOpen)
#define GNMUSICIDERR_IOError				GNERR_MAKE_VALUE(GNPKG_MusicID, GNERR_IOError)

/* Errors returned from the Lists subsystem */
#define GNLISTSERR_NoError					0
#define GNLISTSERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_InvalidArg)
#define GNLISTSERR_UnsupportedFunctionality				GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_UnsupportedFunctionality)
#define GNLISTSERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_NoMemory)
#define GNLISTSERR_InvalidListFile			GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_InvalidListFile)
#define GNLISTSERR_IOError					GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_IOError)
#define GNLISTSERR_NotInited				GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_NotInited)
#define GNLISTSERR_NotFound					GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_NotFound)
#define GNLISTSERR_InvalidFormat			GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_InvalidFormat)
#define GNLISTSERR_Unavailable				GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_Unavailable)
#define GNLISTSERR_Busy						GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_Busy)
#define GNLISTSERR_NullHandleFromOpen		GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_NullHandleFromOpen)
#define GNLISTSERR_IckyError				GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_IckyError)
#define GNLISTSERR_BadCategoryLevel			GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_BadCategoryLevel)
#define GNLISTSERR_BadDispHierType			GNERR_MAKE_VALUE(GNPKG_Lists, GNERR_BadDispHierType)

/* Errors returned from the LINK subsystem */
#define GNLINKERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_LINK, GNERR_InvalidArg)
#define GNLINKERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_LINK, GNERR_NoMemory)
#define GNLINKERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_LINK, GNERR_UnsupportedFunctionality)

/* Errors returned from the Unicode String Conversion subsystem */
#define GNSTRCONV_ERR_NoError				0
#define GNSTRCONV_ERR_BufferTooSmall		GNERR_MAKE_VALUE(GNPKG_StrConv, GNERR_BufferTooSmall)
#define GNSTRCONV_ERR_InvalidArg			GNERR_MAKE_VALUE(GNPKG_StrConv, GNERR_InvalidArg)
#define GNSTRCONV_ERR_ERange				GNERR_MAKE_VALUE(GNPKG_StrConv, GNERR_ERange)
#define GNSTRCONV_ERR_InvalidCharacter		GNERR_MAKE_VALUE(GNPKG_StrConv, GNERR_InvalidCharacter)
#define GNSTRCONV_ERR_NoBOM					GNERR_MAKE_VALUE(GNPKG_StrConv, GNERR_NoBOM)

/* Errors returned from the GNFAPI subsystem */
#define GNFAPIERR_NoError					0
#define GNFAPIERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_FAPI, GNERR_InvalidArg)
#define GNFAPIERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_FAPI, GNERR_NoMemory)
#define GNFAPIERR_IckyError					GNERR_MAKE_VALUE(GNPKG_FAPI, GNERR_IckyError)

/* Errors returned from the Cantametrix subsystem */
#define GNCMERR_NoError						0
#define GNCMERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Cantametrix, GNERR_InvalidArg)
#define GNCMERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_Cantametrix, GNERR_NoMemory)
#define GNCMERR_FingerprintAcquired			GNERR_MAKE_VALUE(GNPKG_Cantametrix, GNERR_FingerprintAcquired)
#define GNCMERR_FingerprintNotAcquired		GNERR_MAKE_VALUE(GNPKG_Cantametrix, GNERR_FingerprintNotAcquired)
#define GNCMERR_IckyError					GNERR_MAKE_VALUE(GNPKG_Cantametrix, GNERR_IckyError)

/* Errors returned from the FPX library */
#define FPXERR_NoError						0
#define FPXERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_InvalidArg)
#define FPXERR_Unsupported					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_UnsupportedFunctionality)
#define FPXERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_NoMemory)
#define FPXERR_NotReady						GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_NotReady)
#define FPXERR_NotInited					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_NotInited)
#define FPXERR_IckyError					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_IckyError)
#define FPXERR_UnsupportedAlg				GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_UnsupportedFPAlg)
#define FPXERR_Busy							GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_Busy)
#define FPXERR_FileExists					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_FileExists)
#define FPXERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_InvalidFormat)
#define FPXERR_IncompatibleDBs				GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_IncompatibleDBs)
#define FPXERR_FileNotFound   				GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_FileNotFound)
#define FPXERR_NothingToDo					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_NothingToDo)
#define FPXERR_ColumnHasNoZones				GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_ColumnHasNoZones)
#define FPXERR_EndOfSearch					GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_EndOfSearch)
#define FPXERR_IllegalFingerprint			GNERR_MAKE_VALUE(GNPKG_FPX, GNERR_IllegalFingerprint)

/* Errors returned from the TextID subsystem */
#define GNTEXTIDERR_NoError						0
#define GNTEXTIDERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidArg)
#define GNTEXTIDERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_NoMemory)
#define GNTEXTIDERR_Busy						GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_Busy)
#define GNTEXTIDERR_InvalidDataFormatVersion	GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidDataFormatVersion)
#define	GNTEXTIDERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_BufferTooSmall)
#define GNTEXTIDERR_NotFound					GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_NotFound)
#define	GNTEXTIDERR_NotInited					GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_NotInited)
#define	GNTEXTIDERR_TextidResultNotAvailable	GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_TextidResultNotAvailable)
#define GNTEXTIDERR_TextidResultOutOfRange		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_TextidResultOutOfRange)
#define GNTEXTIDERR_UnknownMatchType			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_UnknownMatchType)
#define GNTEXTIDERR_UnknownLookupOption			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_UnknownLookupOption)
#define GNTEXTIDERR_ExactLookupFailed			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_ExactLookupFailed)
#define GNTEXTIDERR_InternalError				GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InternalError)
#define GNTEXTIDERR_InconsistentState			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InconsistentState)
#define GNTEXTIDERR_NullHandleFromOpen			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_NullHandleFromOpen)
#define GNTEXTIDERR_InvalidTextidFile			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidTextidFile)
#define GNTEXTIDERR_InvalidContributorInfo		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidContributorInfo)
#define GNTEXTIDERR_InvalidAlbumInfo			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidAlbumInfo)
#define GNTEXTIDERR_InvalidStateSetup			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidStateSetup)
#define GNTEXTIDERR_MediavocsDataPresent		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_MediavocsDataPresent)
#define GNTEXTIDERR_InvalidUpdateFileRecordVersion GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidUpdateFileRecordVersion)
#define GNTEXTIDERR_InvalidUpdateFileRecord		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidUpdateFileRecord)
#define GNTEXTIDERR_UnknownFileSystemError		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_UnknownFileSystemError)
#define GNTEXTIDERR_InvalidTextDBRecord			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidTextDBRecord)
#define GNTEXTIDERR_NoTextDBData				GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_NoTextDBData)
#define GNTEXTIDERR_MGRInvalidHandle			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_MGRInvalidHandle)
#define GNTEXTIDERR_MGRHandleHasNoOpenDBs		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_MGRHandleHasNoOpenDBs)
#define GNTEXTIDERR_BadMatchSource              GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_BadMatchSource)
#define GNTEXTIDERR_BadAlbumV1Genre             GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_BadAlbumV1Genre)
#define GNTEXTIDERR_UnknownVersion				GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_UnknownVersion)
#define GNTEXTIDERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_UnsupportedFunctionality)
#define GNTEXTIDERR_InvalidEntitlementKey		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidEntitlementKey)
#define GNTEXTIDERR_InvalidRecordType			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_InvalidRecordType)
#define GNTEXTIDERR_MinimizedFileHandles		GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_MinimizedFileHandles)
#define GNTEXTIDERR_IDFetchNotFound				GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_IDFetchNotFound)
#define GNTEXTIDERR_BadResultIDValue			GNERR_MAKE_VALUE(GNPKG_TextID, GNERR_BadResultIDValue)


/* Errors returned from DataEncode subsystem */
#define GNDATAENCODEERR_NoError						0
#define GNDATAENCODEERR_InvalidArg 					GNERR_MAKE_VALUE(GNPKG_DataEncode, GNERR_InvalidArg)
#define GNDATAENCODEERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_DataEncode, GNERR_NoMemory)
#define GNDATAENCODEERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_DataEncode, GNERR_InvalidFormat)
#define GNDATAENCODEERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_DataEncode, GNERR_UnsupportedFunctionality)
#define GNDATAENCODEERR_IncorrectBufferType			GNERR_MAKE_VALUE(GNPKG_DataEncode, GNERR_IncorrectBufferType)

/* Errors returned from the Content subsystem. */
#define CONTENTERR_NoError							0
#define CONTENTERR_InvalidArg						GNERR_MAKE_VALUE(GNPKG_Content, GNERR_InvalidArg)
#define CONTENTERR_NotFound							GNERR_MAKE_VALUE(GNPKG_Content, GNERR_NotFound)
#define CONTENTERR_NoMemory							GNERR_MAKE_VALUE(GNPKG_Content, GNERR_NoMemory)
#define CONTENTERR_UnsupportedFunctionality			GNERR_MAKE_VALUE(GNPKG_Content, GNERR_UnsupportedFunctionality)
#define CONTENTERR_BadXMLFormat						GNERR_MAKE_VALUE(GNPKG_Content, GNERR_BadXMLFormat)
#define CONTENTERR_IOError							GNERR_MAKE_VALUE(GNPKG_Content, GNERR_IOError)
#define CONTENTERR_FileNotFound						GNERR_MAKE_VALUE(GNPKG_Content, GNERR_FileNotFound)
#define CONTENTERR_Busy								GNERR_MAKE_VALUE(GNPKG_Content, GNERR_Busy)
#define CONTENTERR_NotInited						GNERR_MAKE_VALUE(GNPKG_Content, GNERR_NotInited)
#define CONTENTERR_IckyError						GNERR_MAKE_VALUE(GNPKG_Content, GNERR_IckyError)
#define CONTENTERR_Overflow							GNERR_MAKE_VALUE(GNPKG_Content, GNERR_OVERFLOW)					/* No longer used */
#define CONTENTERR_NeedsLookup						GNERR_MAKE_VALUE(GNPKG_Content, GNERR_ContentNeedsLookup)
#define CONTENTERR_NeedsResolution					GNERR_MAKE_VALUE(GNPKG_Content, GNERR_ContentNeedsResolution)
#define CONTENTERR_UnsupportedContentType			GNERR_MAKE_VALUE(GNPKG_Content, GNERR_ContentUnsupportedContentType)

/* Errors returned from Random subsystem */
#define	GNRANDOMERR_NoError							0
#define	GNRANDOMERR_InvalidArg						GNERR_MAKE_VALUE(GNPKG_Random, GNERR_InvalidArg)
#define GNRANDOMERR_MemoryError						GNERR_MAKE_VALUE(GNPKG_Random, GNERR_NoMemory)
#define GNRANDOMERR_Busy							GNERR_MAKE_VALUE(GNPKG_Random, GNERR_Busy)

/* Errors returned from Encode subsystem */
#define GNENCODEERR_NoError						0
#define GNENCODEERR_InvalidArg 					GNERR_MAKE_VALUE(GNPKG_Encode, GNERR_InvalidArg)
#define GNENCODEERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_Encode, GNERR_NoMemory)
#define GNENCODEERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_Encode, GNERR_InvalidFormat)
#define GNENCODEERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_Encode, GNERR_UnsupportedFunctionality)

/* Errors returned from data accessor functions. */
#define GNDACCERR_NoError						0
#define GNDACCERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_InvalidArg)
#define GNDACCERR_NotFound						GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_NotFound)
#define GNDACCERR_MissingField					GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_MissingField)
#define GNDACCERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_NoMemory)
#define GNDACCERR_ArrayOverflow					GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_ArrayOverflow)
#define GNDACCERR_InvalidFormat					GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_InvalidFormat)
#define GNDACCERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_UnsupportedFunctionality)
#define GNDACCERR_IckyError						GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_IckyError)
#define GNDACCERR_NoEntitlement					GNERR_MAKE_VALUE(GNPKG_DataAccess, GNERR_NoEntitlement)

/* Errors returned from altphrase mapper subsystem. */
#define GNAPMERR_NoError						0
#define GNAPMERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_UnsupportedFunctionality)
#define GNAPMERR_InvalidArg						GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_InvalidArg)
#define GNAPMERR_NotFound						GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_NotFound)
#define GNAPMERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_NoMemory)
#define GNAPMERR_InvalidFormat					GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_InvalidFormat)
#define GNAPMERR_IckyError						GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_IckyError)
#define GNAPMERR_Busy							GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_Busy)
#define GNAPMERR_NotInited						GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_NotInited)
#define GNAPMERR_NullHandleFromOpen				GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_NullHandleFromOpen)
#define GNAPMERR_NoOfficialRepresentation		GNERR_MAKE_VALUE(GNPKG_AltPhrase, GNERR_NoOfficialRepresentation)

/* Errors returned from the transcript (phonetic transcription) subsystem. */
#define	GNTRANSCRIPTERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_InvalidArg)
#define	GNTRANSCRIPTERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_NoMemory)
#define GNTRANSCRIPTERR_IckyError					GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_IckyError)
#define GNTRANSCRIPTERR_ArrayOverflow				GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_ArrayOverflow)
#define GNTRANSCRIPTERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_InvalidFormat)
#define GNTRANSCRIPTERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_UnsupportedFunctionality)
#define GNTRANSCRIPTERR_Busy						GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_Busy)
#define GNTRANSCRIPTERR_NotInited					GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_NotInited)
#define GNTRANSCRIPTERR_BadConfigurationData		GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_BadConfigurationData)
#define GNTRANSCRIPTERR_InvalidSpokenLanguageID		GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_InvalidSpokenLanguageID)
#define GNTRANSCRIPTERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_BufferTooSmall)
#define GNTRANSCRIPTERR_Unavailable					GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_Unavailable)		/* required list is unavailable */
#define GNTRANSCRIPTERR_NullHandleFromOpen			GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_NullHandleFromOpen)
#define GNTRANSCRIPTERR_UnknownPhonemeMapFileVersion	GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_UnknownPhonemeMapFileVersion)
#define GNTRANSCRIPTERR_UnrecognizedPhonemeMapFileFlag	GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_UnrecognizedPhonemeMapFileFlag)
#define GNTRANSCRIPTERR_NoTargetLangaugesInPhonemeMapFile  GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_NoTargetLangaugesInPhonemeMapFile) 
#define GNTRANSCRIPTERR_MissingPhonemeMapData		GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_MissingPhonemeMapData)
#define GNTRANSCRIPTERR_InvalidUnencryptedSizeForMap GNERR_MAKE_VALUE(GNPKG_Transcript, GNERR_InvalidUnencryptedSizeForMap)


/* Errors returned from the coverart db subsystem */
#define GNCOVERARTERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_CoverArt, GNERR_InvalidArg)
#define GNCOVERARTERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_CoverArt, GNERR_NoMemory)
#define GNCOVERARTERR_InvalidUniversalDataFormat	GNERR_MAKE_VALUE(GNPKG_CoverArt, GNERR_InvalidUniversalDataFormat)
#define GNCOVERARTERR_InvalidFormat					GNERR_MAKE_VALUE(GNPKG_CoverArt, GNERR_InvalidFormat)
#define GNCOVERARTERR_NullHandleFromOpen			GNERR_MAKE_VALUE(GNPKG_CoverArt, GNERR_NullHandleFromOpen)
#define GNCOVERARTERR_Busy							GNERR_MAKE_VALUE(GNPKG_CoverArt, GNERR_Busy)

/* Errors returned from the lookup cache subsystem */
#define GNLOOKUPCACHEERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_InvalidArg)
#define GNLOOKUPCACHEERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_UnsupportedFunctionality)
#define GNLOOKUPCACHEERR_Busy						GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_Busy)
#define GNLOOKUPCACHEERR_NotInited					GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_NotInited)
#define GNLOOKUPCACHEERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_InvalidFormat)
#define GNLOOKUPCACHEERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_InvalidFormat)
#define GNLOOKUPCACHEERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_NoMemory)
#define GNLOOKUPCACHEERR_InvalidUniversalDataFormat GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_InvalidUniversalDataFormat)
#define GNLOOKUPCACHEERR_FileExists					GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_FileExists)
#define GNLOOKUPCACHEERR_NoSpace					GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_NoSpace)
#define GNLOOKUPCACHEERR_ArrayOverflow				GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_ArrayOverflow)
#define GNLOOKUPCACHEERR_BadConfigurationData		GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_BadConfigurationData)
#define GNLOOKUPCACHEERR_IckyError					GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_IckyError)
#define GNLOOKUPCACHEERR_AlreadyAdded				GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_AlreadyAdded)
#define GNLOOKUPCACHEERR_IncompleteRecord			GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_IncompleteRecord)
#define GNLOOKUPCACHEERR_LookupNotReady				GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_LookupNotReady)
#define GNLOOKUPCACHEERR_LookupNoMatch				GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_LookupNoMatch)
#define GNLOOKUPCACHEERR_NullHandleFromOpen			GNERR_MAKE_VALUE(GNPKG_LookupCache, GNERR_NullHandleFromOpen)

/* Errors returned from the OnDemand Lookups subsystem */
#define ODLERR_NotInited						GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_NotInited)
#define ODLERR_Busy								GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_Busy)
#define ODLERR_NotFound							GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_NotFound)
#define ODLERR_AlreadyAdded						GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_AlreadyAdded)
#define ODLERR_InvalidArg						GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_InvalidArg)
#define ODLERR_InvalidTOC						GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_InvalidTOC)
#define ODLERR_DatabaseRevisionError			GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_DatabaseRevisionError)
#define ODLERR_NoMemory							GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_NoMemory)
#define ODLERR_IOError							GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_IOError)
#define ODLERR_InvalidFormat					GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_InvalidFormat)
#define ODLERR_BadResultFormat					GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_BadResultFormat)
#define ODLERR_IncompleteUpdate					GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_IncompleteUpdate)
#define ODLERR_IckyError						GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_IckyError)
#define ODLERR_FileNotFound						GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_FileNotFound)
#define ODLERR_UnsupportedFunctionality			GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_UnsupportedFunctionality)
#define	ODLERR_ClientIDNotSet					GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_ClientIDNotSet)
#define	ODLERR_ClientIDTagNotSet				GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_ClientIDTagNotSet)
#define ODLERR_ObjectDataMissing				GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_ObjectDataMissing)
#define ODLERR_ServerError						GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_ServerError)
#define ODLERR_InconsistentState				GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_InconsistentState)
#define ODLERR_InvalidArrayIndex				GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_InvalidArrayIndex)
#define ODLERR_MissingClassicalData             GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_MissingClassicalData)
#define ODLERR_BadXMLFormat                     GNERR_MAKE_VALUE(GNPKG_OnDemandLookups, GNERR_BadXMLFormat)
	
/* Online subsystem errors. */
#define ONLINEERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Online, GNERR_InvalidArg)
#define ONLINEERR_NotInited						GNERR_MAKE_VALUE(GNPKG_Online, GNERR_NotInited)
#define ONLINEERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_Online, GNERR_NoMemory)
#define ONLINEERR_InvalidMetadataLanguageID		GNERR_MAKE_VALUE(GNPKG_Online, GNERR_InvalidMetadataLanguageID)
#define ONLINEERR_MatchResolutionFailed			GNERR_MAKE_VALUE(GNPKG_Online, GNERR_MatchResolutionFailed)
#define ONLINEERR_MemoryError					GNERR_MAKE_VALUE(GNPKG_Online, GNERR_NoMemory)
#define ONLINEERR_Busy							GNERR_MAKE_VALUE(GNPKG_Online, GNERR_Busy)
#define ONLINEERR_Overflow						GNERR_MAKE_VALUE(GNPKG_Online, GNERR_OVERFLOW)
#define ONLINEERR_Missing_Client_ID				GNERR_MAKE_VALUE(GNPKG_Online, GNERR_Missing_Client_ID)
#define ONLINEERR_Missing_Client_ID_Tag			GNERR_MAKE_VALUE(GNPKG_Online, GNERR_Missing_Client_ID_Tag)
#define ONLINEERR_NotFound						GNERR_MAKE_VALUE(GNPKG_Online, GNERR_NotFound)
#define ONLINEERR_BadResultFormat				GNERR_MAKE_VALUE(GNPKG_Online, GNERR_BadResultFormat)
#define ONLINEERR_BufferTooSmall				GNERR_MAKE_VALUE(GNPKG_Online, GNERR_BufferTooSmall)
#define ONLINEERR_IDNotFound					GNERR_MAKE_VALUE(GNPKG_Online, GNERR_IDNotFound)
#define ONLINEERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_Online, GNERR_UnsupportedFunctionality)
#define ONLINEERR_IckyError						GNERR_MAKE_VALUE(GNPKG_Online, GNERR_IckyError)
#define ONLINEERR_InvalidFile					GNERR_MAKE_VALUE(GNPKG_Online, GNERR_InvalidFile)
#define ONLINEERR_InvalidFormat					GNERR_MAKE_VALUE(GNPKG_Online, GNERR_InvalidFormat)
#define ONLINEERR_ServerError					GNERR_MAKE_VALUE(GNPKG_Online, GNERR_ServerError)
#define ONLINEERR_Missing_User_ID				GNERR_MAKE_VALUE(GNPKG_Online, GNERR_Missing_User_ID)
#define ONLINEERR_Missing_User_ID_Tag			GNERR_MAKE_VALUE(GNPKG_Online, GNERR_Missing_User_ID_Tag)
#define ONLINEERR_MissingClassicalData			GNERR_MAKE_VALUE(GNPKG_Online, GNERR_MissingClassicalData)
#define	ONLINEERR_BadRangeSpec					GNERR_MAKE_VALUE(GNPKG_Online, GNERR_BadRangeSpec)

#define GNUTIL_ERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Util, GNERR_InvalidArg)
#define GNUTIL_ERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_Util, GNERR_NoMemory)
#define GNUTIL_ERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_Util, GNERR_UnsupportedFunctionality)
#define GNUTIL_ERR_InvalidFormat				GNERR_MAKE_VALUE(GNPKG_Util, GNERR_InvalidFormat)
#define GNUTIL_ERR_InvalidArrayObject			GNERR_MAKE_VALUE(GNPKG_Util, GNERR_InvalidArrayObject)
#define GNUTIL_ERR_InvalidArrayIndex			GNERR_MAKE_VALUE(GNPKG_Util, GNERR_InvalidArrayIndex)
#define GNUTIL_ERR_CallbackValue				GNERR_MAKE_VALUE(GNPKG_Util, GNERR_CallbackValue)
#define GNUTIL_ERR_KeyExists					GNERR_MAKE_VALUE(GNPKG_Util, GNERR_KeyExists)
#define GNUTIL_ERR_NotFound						GNERR_MAKE_VALUE(GNPKG_Util, GNERR_NotFound)
#define GNUTIL_ERR_TooManyDigits				GNERR_MAKE_VALUE(GNPKG_Util, GNERR_TooManyDigits)
#define GNUTIL_ERR_ERange						GNERR_MAKE_VALUE(GNPKG_Util, GNERR_ERange)
#define GNUTIL_ERR_NotNumeric					GNERR_MAKE_VALUE(GNPKG_Util, GNERR_NotNumeric)

#define GNMAN_ERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Manifest, GNERR_InvalidArg)
#define GNMAN_ERR_InvalidArrayIndex				GNERR_MAKE_VALUE(GNPKG_Manifest, GNERR_InvalidArrayIndex)
#define GNMAN_ERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_Manifest, GNERR_NoMemory)
#define GNMAN_ERR_IckyError						GNERR_MAKE_VALUE(GNPKG_Manifest, GNERR_IckyError)
#define GNMAN_ERR_NotFound						GNERR_MAKE_VALUE(GNPKG_Manifest, GNERR_NotFound)

#define GNTEXTCORR_ERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_TextCorr, GNERR_InvalidArg)
#define GNTEXTCORR_ERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_TextCorr, GNERR_NoMemory)
#define GNTEXTCORR_ERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_TextCorr, GNERR_UnsupportedFunctionality)
#define GNTEXTCORR_ERR_NothingToDo				GNERR_MAKE_VALUE(GNPKG_TextCorr, GNERR_NothingToDo)
#define GNTEXTCORR_ERR_IckyError				GNERR_MAKE_VALUE(GNPKG_TextCorr, GNERR_IckyError)
	
#define INSTALLERR_ConfigNull					GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_ConfigNull)
#define INSTALLERR_LFSNotFound					GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_LFSNotFound)
#define INSTALLERR_ProductNotFound				GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_ProductNotFound)
#define INSTALLERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_InvalidArg)
#define INSTALLERR_ManifestNotFound				GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_ManifestNotFound)
#define INSTALLERR_BadInitState					GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_BadInitState)
#define INSTALLERR_BadInstallPath				GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_BadInstallPath)
#define INSTALLERR_IckyError					GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_IckyError)
#define INSTALLERR_BaseDataNotFound				GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_BaseDataNotFound)
#define INSTALLERR_BaseIndexNotFound			GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_BaseIndexNotFound)
#define INSTALLERR_PCXNotFound					GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_PCXNotFound)
#define INSTALLERR_ListsNotFound				GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_ListsNotFound)
#define INSTALLERR_CorrelatesNotFound			GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_CorrelatesNotFound)
#define INSTALLERR_CoverArtBaseDataNotFound		GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_CoverArtBaseDataNotFound)
#define INSTALLERR_CoverArtBaseIndexNotFound	GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_CoverArtBaseIndexNotFound)
#define INSTALLERR_InventoryFileNotFound		GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_InventoryFileNotFound)
#define INSTALLERR_PDLPresetsNotFound			GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_PDLPresetsNotFound)
#define INSTALLERR_ContribTblNotFound			GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_ContribTblNotFound)
#define INSTALLERR_GenreTblNotFound				GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_GenreTblNotFound)
#define INSTALLERR_AlbumTblNotFound				GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_AlbumTblNotFound)
#define INSTALLERR_GenreArtBaseDataNotFound		GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_GenreArtBaseDataNotFound)
#define INSTALLERR_GenreArtBaseIndexNotFound	GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_GenreArtBaseIndexNotFound)
#define INSTALLERR_FPX_NotFound					GNERR_MAKE_VALUE(GNPKG_Installer, GNERR_FPX_NotFound)

#define GNPB_ERR_NoMemory						GNERR_MAKE_VALUE(GNPKG_PB, GNERR_NoMemory)
#define GNPB_ERR_IckyError						GNERR_MAKE_VALUE(GNPKG_PB, GNERR_IckyError)
#define GNPB_ERR_InvalidArg						GNERR_MAKE_VALUE(GNPKG_PB, GNERR_InvalidArg)
#define GNPB_ERR_UnsupportedFunctionality		GNERR_MAKE_VALUE(GNPKG_PB, GNERR_UnsupportedFunctionality)
#define GNPB_ERR_InvalidMessageFormat			GNERR_MAKE_VALUE(GNPKG_PB, GNERR_InvalidMessageFormat)
#define GNPB_ERR_InvalidType					GNERR_MAKE_VALUE(GNPKG_PB, GNERR_InvalidType)
#define GNPB_ERR_InvalidWireType				GNERR_MAKE_VALUE(GNPKG_PB, GNERR_InvalidWireType)
#define GNPB_ERR_InvalidInt						GNERR_MAKE_VALUE(GNPKG_PB, GNERR_InvalidInt)
#define GNPB_ERR_InvalidMember					GNERR_MAKE_VALUE(GNPKG_PB, GNERR_InvalidMember)
#define GNPB_ERR_DataTooShort					GNERR_MAKE_VALUE(GNPKG_PB, GNERR_DataTooShort)
#define GNPB_ERR_BadHeader          			GNERR_MAKE_VALUE(GNPKG_PB, GNERR_BadHeader)
#define GNPB_ERR_UnterminatedVarInt   			GNERR_MAKE_VALUE(GNPKG_PB, GNERR_UnterminatedVarInt)
#define GNPB_ERR_ParsingError   				GNERR_MAKE_VALUE(GNPKG_PB, GNERR_ParsingError)

#define DBHEADERERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_DBHeader, GNERR_InvalidArg)
#define DBHEADERERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_DBHeader, GNERR_NoMemory)
#define DBHEADERERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_DBHeader, GNERR_UnsupportedFunctionality)

#define GNCACHE_ERR_InvalidArg					GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_InvalidArg)
#define GNCACHE_ERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_NoMemory)
#define GNCACHE_ERR_UnsupportedFunctionality	GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_UnsupportedFunctionality)
#define GNCACHE_ERR_NotFound					GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_NotFound)
#define GNCACHE_ERR_AlreadyAdded				GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_AlreadyAdded)
#define GNCACHE_ERR_InvalidTOC					GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_InvalidTOC)
#define GNCACHE_ERR_NotInited					GNERR_MAKE_VALUE(GNPKG_Cache, GENERR_NotInited)
#define GNCACHE_ERR_NoError						GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_NoError)
#define GNCACHE_ERR_Busy						GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_Busy)
#define GNCACHE_ERR_CacheDataError				GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_CacheDataError)
#define GNCACHE_ERR_CacheInitedForLookups		GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_CacheInitedForLookups)
#define GNCACHE_ERR_CacheInitedForUpdates		GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_CacheInitedForUpdates)
#define GNCACHE_ERR_NoCache						GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_NoCache)
#define	GNCACHE_ERR_IOError						GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_IOError)
#define	GNCACHE_ERR_UnsupportedOption			GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_UnsupportedOption)
#define	GNCACHE_ERR_DataError					GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_DataError)
#define GNCACHE_ERR_NullHandleFromOpen			GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_NullHandleFromOpen)
#define GNCACHE_ERR_UnknownVersion				GNERR_MAKE_VALUE(GNPKG_Cache, GNERR_UnknownVersion)

#define GNPHOCVRT_ERR_InvalidArg				GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_InvalidArg)
#define GNPHOCVRT_ERR_NoMemory					GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_NoMemory)
#define GNPHOCVRT_ERR_InvalidPhonemeFile		GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_InvalidPhonemeFile)
#define GNPHOCVRT_ERR_InvalidConversionFile		GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_InvalidConversionFile)
#define GNPHOCVRT_ERR_InvalidConversion			GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_InvalidConversion)
#define GNPHOCVRT_ERR_MapNotFound				GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_MapNotFound)
#define GNPHOCVRT_ERR_GroupNotFound				GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_GroupNotFound)
#define GNPHOCVRT_ERR_InvalidAlgID				GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_InvalidAlgID)
#define GNPHOCVRT_ERR_ValidationFailed			GNERR_MAKE_VALUE(GNPKG_PhonemeConversion, GNERR_ValidationFailed)


#ifdef __cplusplus
}
#endif

#endif /* _GN_ERROR_VALUES_H_ */

