#!/bin/bash
#
# standby-triggerd
#
# chkconfig:   345 90 88
# description: daemon for triggering STANDBY_IMMEDIATE
#
### BEGIN INIT INFO
# Provides: standby-triggerd
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions


exec="/usr/sbin/standby-trigger"
prog=$(basename $exec)
lockfile=/var/lock/subsys/$prog

start() {
	echo -n $"Starting $prog:"
	$prog 
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

stop() {
	echo -n $"Stopping $prog: "
	killproc $prog
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
	return $retval
}

restart() {
	stop
	start
}

reload() {
	restart
}

force_reload() {
	restart
}

fdr_status() {
	status $prog
}


case "$1" in
	start|stop|restart|reload)
		$1
		;;
	force-reload)
		force_reload
		;;
	status)
		fdr_status
		;;
	condrestart|try-restart)
		[ -f $lockfile ] || restart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
		exit 1
esac
