.pragma library

/**General*/
var const_SPIN_CTRL_SETTINGS_WIDTH = 368
var const_SPIN_CTRL_INFO_WIDTH = 603
var const_SPIN_CTRL_VIDEO_WIDTH = 453

var const_SPIN_CTRL_SETTINGS_HEIGHT = 62
var const_SPIN_CTRL_INFO_HEIGHT = 71
var const_SPIN_CTRL_VIDEO_HEIGHT = 71
var const_SPIN_CTRL_VIDEO_PLUS_MINUS_HEIGHT = 68

var const_SPIN_CTRL_BTN_PREV_WIDTH = 75
var const_SPIN_CTRL_BTN_PREV_WIDTH_L = 83
var const_SPIN_CTRL_BTN_PREV_PLUS_MINUS_WIDTH = 81
var const_SPIN_CTRL_BTN_NEXT_WIDTH = 75
var const_SPIN_CTRL_BTN_NEXT_WIDTH_L = 83
var const_SPIN_CTRL_BTN_NEXT_PLUS_MINUS_WIDTH = 81

var const_SPIN_CTRL_RECTANGLE_WIDTH = 125
var const_SPIN_CTRL_RECTANGLE_HEIGHT = 39
var const_SPIN_CTRL_RECTANGLE_LEFT_MARGIN = 164
var const_SPIN_CTRL_RECTANGLE_TOP_MARGIN = 15

var const_SPIN_CTRL_FONT_SIZE_TEXT_36PT = 36
var const_SPIN_CTRL_FONT_FAMILY_HDR = "HDR"
var const_SPIN_CTRL_FONT_FAMILY_HDB = "HDB"
var const_SPIN_CTRL_FONT_FAMILY_NEW_HDR = "DH_HDR"
var const_SPIN_CTRL_FONT_FAMILY_NEW_HDB = "DH_HDB"

var const_COLOR_TEXT_DIMMED_GREY = "#9E9E9E"
var const_SPIN_CTRL_COLOR_TEXT_BRIGHT_GREY = "#FAFAFA"
var const_SPIN_CTRL_COLOR_TEXT_BLACK = "#000000"

var const_SPIN_CTRL_LANGCONTEXT = "main"
