.pragma library

var  const_TEXT_PROGRESS_BAR_FULLSCREEN_WIDTH = 1280
var  const_TEXT_PROGRESS_BAR_NOT_FULLSCREEN_WIDTH = 1280
var  const_TEXT_PROGRESS_BAR_FULLSCREEN_HEIGHT = 80
var  const_TEXT_PROGRESS_BAR_NOT_FULLSCREEN_HEIGHT = 162

var  const_TEXT_PROGRESS_BAR_MUSIC_FULLSCREEN_CURRENT_TIME_WIDTH = 102-28
var  const_TEXT_PROGRESS_BAR_MUSIC_FULLSCREEN_CURRENT_TIME_LEFT_MARGIN = 28
var  const_TEXT_PROGRESS_BAR_MUSIC_NOT_FULLSCREEN_CURRENT_TIME_WIDTH = 159-83
var  const_TEXT_PROGRESS_BAR_MUSIC_NOT_FULLSCREEN_CURRENT_TIME_LEFT_MARGIN = 83
var  const_TEXT_PROGRESS_BAR_VIDEO_CURRENT_TIME_WIDTH = 124-26
var  const_TEXT_PROGRESS_BAR_VIDEO_CURRENT_TIME_LEFT_MARGIN = 26
var  const_TEXT_PROGRESS_BAR_SOUND_THERAPY_CURRENT_TIME_WIDTH = 101-28
var  const_TEXT_PROGRESS_BAR_SOUND_THERAPY_CURRENT_TIME_LEFT_MARGIN = 28

var  const_TEXT_PROGRESS_BAR_MUSIC_FULLSCREEN_TOTAL_TIME_WIDTH = 73
var  const_TEXT_PROGRESS_BAR_MUSIC_NOT_FULLSCREEN_TOTAL_TIME_WIDTH  = 566
var  const_TEXT_PROGRESS_BAR_VIDEO_TOTAL_TIME_WIDTH = 124-24
var  const_TEXT_PROGRESS_BAR_VIDEO_TOTAL_TIME_RIGHT_MARGIN  = 24
var  const_TEXT_PROGRESS_BAR_SOUND_THERAPY_TOTAL_TIME_WIDTH = 73
var  const_TEXT_PROGRESS_BAR_SOUND_THERAPY_TOTAL_TIME_RIGHT_MARGIN  = 17
var  const_TEXT_PROGRESS_BAR_MUSIC_FULLSCREEN_TOTAL_TIME_LEFT_MARGIN = 13

var  const_TEXT_PROGRESS_BAR_MUSIC_FULLSCREEN_REPEAT_ITEM_RIGHT_MARGIN = 1
var  const_TEXT_PROGRESS_BAR_MUSIC_NOT_FULLSCREEN_REPEAT_ITEM_RIGHT_MARGIN = 7
var  const_TEXT_PROGRESS_BAR_MUSIC_SOUND_THERAPY_REPEAT_ITEM_RIGHT_MARGIN = 7
var  const_TEXT_PROGRESS_BAR_VIDEO_REPEAT_ITEM_TOP_MARGIN = 8

var  const_TEXT_PROGRESS_BAR_CURRENT_TIME_HEIGHT = 50
var  const_TEXT_PROGRESS_BAR_HIGHLIGHT_ITEM_HEIGHT = 3
var  const_TEXT_PROGRESS_BAR_CURRENT_TIME_RIGHT_MARGIN = 13

var  const_TEXT_PROGRESS_BAR_MUSIC_FULLSCREEN_PROGRESSBAR_ITEM_WIDTH = 1048
var  const_TEXT_PROGRESS_BAR_MUSIC_NOT_FULLSCREEN_PROGRESSBAR_ITEM_WIDTH = 555
var  const_TEXT_PROGRESS_BAR_VIDEO_PROGRESSBAR_ITEM_WIDTH = 1032
var  const_TEXT_PROGRESS_BAR_SOUND_THERAPY_PROGRESSBAR_ITEM_WIDTH = 1088

var  const_TEXT_PROGRESS_BAR_MUSIC_FULLSCREEN_PROGRESSBAR_ITEM_LEFT_MARGIN = 115 //116
var  const_TEXT_PROGRESS_BAR_MUSIC_NOT_FULLSCREEN_PROGRESSBAR_ITEM_LEFT_MARGIN = 167//159
var  const_TEXT_PROGRESS_BAR_VIDEO_PROGRESSBAR_ITEM_LEFT_MARGIN = 139//124
var  const_TEXT_PROGRESS_BAR_SOUND_THERAPY_PROGRESSBAR_ITEM_LEFT_MARGIN = 94//101

var  const_TEXT_PROGRESS_BAR_TEXT1_RIGHT_MARGIN = 16
var  const_TEXT_PROGRESS_BAR_SOUND_THERAPY_TEXT1_RIGHT_MARGIN = 12
var  const_TEXT_PROGRESS_BAR_TEXT1_BOTTOM_MARGIN = 4
var  const_TEXT_PROGRESS_BAR_TEXT1_LEFT_MARGIN = 3

var const_FONT_SIZE_TEXT_SUN_FONT = 31 //28
var const_FONT_SIZE_TEXT_INDEX_FONT = 23
var const_FONT_SIZE_TEXT_BUTTON_FONT = 36 //34
var const_FONT_SIZE_TEXT_36PT = 36
var const_FONT_SIZE_TEXT_52PT = 52
var const_FONT_SIZE_TEXT_24PT = 24
var const_FONT_SIZE_TEXT_26PT = 26

var const_COLOR_TEXT_PROGRESS_BLUE = "#0087EF"
var const_COLOR_TEXT_PROGRESS_RED = "#800000"
var const_COLOR_TEXT_DIMMED_GREY = "#9E9E9E"
var const_COLOR_TEXT_BRIGHT_GREY = "#FAFAFA"
var const_COLOR_TEXT_GREY = "#C1C1C1"
var const_COLOR_TEXT_WHITE = "#FFFFFF"

var const_FONT_FAMILY_HDB = "HDB"
var const_FONT_FAMILY_HDR = "HDR"
var const_FONT_FAMILY_NEW_HDB = "DH_HDB"
var const_FONT_FAMILY_NEW_HDR = "DH_HDR"


var const_TIMER_INTERVAL = 1000
