.pragma library

/** General*/
var const_ACTIVITY_SCROLL_SMAL_SWITCH =  34

var const_ACTIVITY_SCROLL_BIG_SWITCH =  64

var const_ACTIVITY_SCROLL_SMAL_SLIDER_WIDTH =  405

var const_ACTIVITY_SCROLL_BIG_SLIDER_WIDTH =  730

var const_ACTIVITY_SCROLL_DOUBLE_PNG_LEVEI =  43

var const_ACTIVITY_SCROLL_X =  100
var const_ACTIVITY_SCROLL_Y =  100

var const_ACTIVITY_SCROLL_CURSOR_SHIFT_HOR =  15
var const_ACTIVITY_SCROLL_CURSOR_SHIFT_VERT =  23

var const_ACTIVITY_SCROLL_Y_TEXT_HOR =  14
var const_ACTIVITY_SCROLL_Y_TEXT_VERT =  86

var const_ACTIVITY_SCROLL_INVALID_VALUE =  -1

var const_ACTIVITY_SCROLL_TEXT_FONT_FAMILY = "HDR"
var const_ACTIVITY_SCROLL_TEXT_FONT_FAMILY_NEW = "DH_HDR"
var const_ACTIVITY_SCROLL_TEXT_PIXEL_SIZE = 35
var const_ACTIVITY_SCROLL_TEXT_PIXEL_SIZE_OVER = 36
var const_ACTIVITY_SCROLL_TEXT_COLOR = "#C1C1C1"
