.pragma library

/**
 * DHAVN_AppSettings_General.js
 */

var FONT_BOLD = "DH_HDB"
var FONT_REGULAR = "DH_HDR"

var depthInfo = 1
var onDepth23 = 0

var const_APP_STANDBYCLOCK_FOCUSINDEX_NONE = -1
var const_APP_STANDBYCLOCK_FOCUSINDEX_STANDBY_MAIN = 0
var const_APP_STANDBYCLOCK_FOCUSINDEX_STANDBY_LANGUAGE = 1
var const_APP_STANDBYCLOCK_FOCUSINDEX_STANDBY_ELSE = 2
var const_APP_STANDBYCLOCK_FOCUSINDEX_CLOCK = 3

var const_APP_SETTINGS_MAIN_SCREEN_WIDTH = 1280
var const_APP_SETTINGS_MAIN_SCREEN_HEIGHT = 720 - 93
var const_APP_SETTINGS_STATUSBAR_HEIGHT = 93

var const_APP_SETTINGS_MAIN_MENU_HEIGHT = 720 - 168 - 50 + 93
var const_APP_SETTINGS_MAIN_MENU_WIDTH = 489
var const_APP_SETTINGS_MAIN_MENU_TOP_MARGIN = 168 - 93
var const_APP_SETTINGS_MAIN_MENU_BOTTOM_MARGIN = 50
var const_APP_SETTINGS_CAUTIONTEXT_TOP_MARGIN = 100
var const_APP_SETTINGS_CAUTIONICON_TOP_MARGIN = 10
var const_APP_SETTINGS_BUTTONS_MARGIN = 18
var const_APP_SETTINGS_BUTTON_SPACING = 3

var const_APP_SETTINGS_MAIN_POPUP_LOADER_VERTICAL = -93

var const_APP_SETTINGS_MAIN_TITLEBAR_BUTTONGROUP_X = 757
//var const_APP_SETTINGS_MAIN_TITLEBAR_BUTTONGROUP_Y =

var const_APP_SETTINGS_MAIN_MENU_ITEM_HEIGHT = 90
var const_APP_SETTINGS_KEYBOARD_MENU_ITEM_HEIGHT = 108
var const_APP_SETTINGS_SLIDER_MENU_ITEM_HEIGHT = 111
var const_APP_SETTINGS_MAIN_MENU_ITEM_TIME_PICKER_HEIGHT = 287
var const_APP_SETTINGS_MAIN_MENU_TEXT_LEFT_MARGIN = 42
var const_APP_SETTINGS_MAIN_MENU_LINE_LEFT_MARGIN = 13

var const_COLOR_TEXT_BRIGHT_GREY = Qt.rgba(250/255, 250/255, 250/255, 1)
var const_COLOR_TEXT_DIMMED_GREY = Qt.rgba(158/255, 158/255, 158/255, 1)
var const_COLOR_TEXT_COMMON_GREY = Qt.rgba(193/255, 193/255, 193/255, 1)
var const_COLOR_TEXT_DISABLE_GREY =  Qt.rgba(91/255, 91/255, 91/255, 1)
var const_COLOR_TEXT_SELECT_RED =  Qt.rgba(255/255, 126/255, 0/255, 1)
var const_COLOR_TEXT_SELECT_BLUE =  Qt.rgba(124/255, 189/255, 255/255, 1)
var const_APP_SETTINGS_COLOR_TEXT_BLACK = "#000000"
var const_APP_SETTINGS_COLOR_TEXT_WHITE = "white"
var const_APP_SETTINGS_COLOR_TEXT_TRANSPARENT = "transparent"


var const_APP_SETTINGS_AUTO_DISAPPEAR = "5000"

var const_FONT_SIZE_TEXT_LIST_FONT = 36
var const_FONT_SIZE_TEXT_SUN_FONT = 21
var const_FONT_SIZE_TEXT_INDEX_FONT = 21
var const_FONT_SIZE_TEXT_HDR_32_FONT = 30
var const_FONT_SIZE_TEXT_HDR_22_FONT = 22
var const_APP_SETTINGS_FONT_SIZE_TEXT_43PT = 43
var const_APP_SETTINGS_FONT_SIZE_TEXT_40PT = 40
var const_APP_SETTINGS_FONT_SIZE_TEXT_36PT = 36
var const_APP_SETTINGS_FONT_SIZE_TEXT_34PT = 34
var const_APP_SETTINGS_FONT_SIZE_TEXT_32PT = 32
var const_APP_SETTINGS_FONT_SIZE_TEXT_30PT = 30
var const_APP_SETTINGS_FONT_SIZE_TEXT_28PT = 28
var const_APP_SETTINGS_FONT_SIZE_TEXT_26PT = 26
var const_APP_SETTINGS_FONT_SIZE_TEXT_25PT = 25
var const_APP_SETTINGS_FONT_SIZE_TEXT_24PT = 24
var const_APP_SETTINGS_FONT_SIZE_TEXT_22PT = 22
var const_APP_SETTINGS_FONT_SIZE_TEXT_20PT = 20
var const_APP_SETTINGS_FONT_SIZE_TEXT_18PT = 18
var const_APP_SETTINGS_FONT_SIZE_TEXT_17PT = 17
var const_FONT_SIZE_TEXT_CELL = 22
var const_FONT_SIZE_TEXT_50PT = 50
var const_FONT_SIZE_TEXT_44PT = 44
var const_APP_SETTINGS_LANGCONTEXT = "main"
var const_APP_SETTINGS_STATUSBAR_LANGCONTEXT = "statusBar"

// visual Cue

var const_AppUserManual_Cue_X = 560
var const_AppUserManual_Cue_Y = 357
var const_AppUserManual_Cue_Margin_1 = 23
var const_AppUserManual_Cue_Margin_2 = 29
