/**
 * DHAVN_AppFileManager_General.js
 */

.pragma library

var const_APP_FILE_MANAGER_SCREEN_WIDTH = 1280
var const_APP_FILE_MANAGER_BOTTOM_BAR_HEIGHT = 81
var const_APP_FILE_MANAGER_RIGHT_BAR_HEIGHT = 554
var const_APP_FILE_MANAGER_RIGHT_BAR_WIDTH = 250
var const_APP_FILE_MANAGER_SCREEN_HEIGHT = 720
var const_APP_FILE_MANAGER_STATUS_BAR_HEIGHT = 93 // modified by eugeny.novikov 2012.11.26 for CR 15770
var const_APP_FILE_MANAGER_MODE_AREA_TOP_MERGIN = 83
var const_APP_FILE_MANAGER_MODE_AREA_HEIGHT = 77
var const_APP_FILE_MANAGER_CONTENT_AREA_TOP_MARGIN = 164
var const_APP_FILE_MANAGER_CONTENT_AREA_LEF_MARGIN = 29
var const_APP_FILE_MANAGER_CONTENT_AREA_RIGHT_MARGIN = 8 // added by Dmitry 03.05.13
var const_APP_FILE_MANAGER_FILEVIEW_LEFT_MARGIN = 250
var const_APP_FILE_MANAGER_FILEVIEW_TOP_MARGIN = 5
var const_APP_FILE_MANAGER_MUSIC_SUB_TAB_WIDTH = 148
var const_APP_FILE_MANAGER_MUSIC_SUB_TAB_RIGTH_MERGIN = 36
var const_APP_FILE_MANAGER_MUSIC_SUB_TAB_TOP_MERGIN = 19
var const_APP_FILE_MANAGER_SEPARATOR_WIDTH
var const_APP_FILE_MANAGER__BOTTOM_BAR_HEIGHT = 81
var const_APP_FILE_MANAGER_LANGCONTEXT = "main"

var const_APP_FILE_MANAGER_AUDIO_LIST_WIDTH = 820
var const_APP_FILE_MANAGER_AUDIO_ARTIST_LIST_ITEM_HEIGHT = 90
var const_APP_FILE_MANAGER_AUDIO_ALBUM_LIST_ITEM_HEIGHT = 90
var const_APP_FILE_MANAGER_AUDIO_SONG_LIST_ITEM_HEIGHT = 90

var const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN = 50
var const_APP_FILE_MANAGER_AUDIO_LIST_DELIMETER_LEFT_MERGIN = const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN + 5
var const_APP_FILE_MANAGER_AUDIO_LIST_ICON_SIZE = 50
var const_APP_FILE_MANAGER_AUDIO_ARTIST_ICON_LEFT_MERGIN = const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN
var const_APP_FILE_MANAGER_AUDIO_ALBUM_ICON_LEFT_MERGIN = const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN
var const_APP_FILE_MANAGER_AUDIO_SONG_ICON_LEFT_MERGIN = const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN
var const_APP_FILE_MANAGER_AUDIO_LIST_ITEM_ICON_TOP_MERGIN = 26
var const_APP_FILE_MANAGER_AUDIO_LIST_ITEM_TEXT_TOP_MERGIN = 47
var const_APP_FILE_MANAGER_AUDIO_ARTIST_TEXT_LEFT_MERGIN = const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN
var const_APP_FILE_MANAGER_AUDIO_ALBUM_TEXT_LEFT_MERGIN = const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN + 61
var const_APP_FILE_MANAGER_AUDIO_SONG_TEXT_LEFT_MERGIN = const_APP_FILE_MANAGER_AUDIO_LIST_COMMON_LEFT_MERGIN + 61
var const_APP_FILE_MANAGER_AUDIO_TEXT_WIDTH = 648

var const_APP_FILE_MANAGER_AUDIO_LIST_ITEM_FONT_SIZE = 40
var const_APP_FILE_MANAGER_AUDIO_LIST_ITEM_FONT_COLOR = "#FAFAFA"
var const_APP_FILE_MANAGER_AUDIO_LIST_ITEM_TOP_MERGIN = 26

/** resourcea for DHAVN_AppFileManager_PictureWidget */

var const_PICTURE_WIDGET_WIDTH =  247
var const_PICTURE_WIDGET_ANIMATION_WIDTH =  170
var const_PICTURE_WIDGET_HIGHT =  247
var const_PICTURE_WIDGET_BG_X =  14
var const_PICTURE_WIDGET_ROTATED_VERT_X =  78
var const_PICTURE_WIDGET_ROTATED_VERT_Y =  29
var const_PICTURE_WIDGET_ROTATED_HOR_X =  55
var const_PICTURE_WIDGET_ROTATED_HOR_Y =  41
var const_PICTURE_WIDGET_ROTATED_VERT_WIDTH =  107
var const_PICTURE_WIDGET_ROTATED_VERT_HEIGHT =  141
var const_PICTURE_WIDGET_ROTATED_HOR_WIDTH =  141
var const_PICTURE_WIDGET_ROTATED_HOR_HEIGHT =  106
var const_PICTURE_WIDGET_ROTATED_VERT_ORIGIN_Y =  20
var const_PICTURE_WIDGET_ROTATED_HOR_ORIGIN_Y =  44
var const_PICTURE_WIDGET_ROTATED_VERT_ANGLE =  5
var const_PICTURE_WIDGET_ROTATED_HOR_ANGLE =  -5
var const_PICTURE_WIDGET_COVER_FOLDER_VERT_X =  62
var const_PICTURE_WIDGET_COVER_FOLDER_VERT_Y =  24
var const_PICTURE_WIDGET_COVER_FOLDER_HOR_X =  48
var const_PICTURE_WIDGET_COVER_FOLDER_HOR_Y =  44
var const_PICTURE_WIDGET_CHECKBOX_Y =  10
var const_PICTURE_WIDGET_TEXT_NAME_FOLDER_WIDTH = 176
var const_PICTURE_WIDGET_TEXT_NAME_FOLDER_Y_NORMAL =  207
var const_PICTURE_WIDGET_TEXT_NAME_FOLDER_Y_SELECT =  175
var const_PICTURE_WIDGET_TEXT_NAME_FOLDER_COLOR =  "#FAFAFA"
var const_PICTURE_WIDGET_TEXT_NAME_FOLDER_PIXEL_SIZE =  24
var const_APP_FILE_MANAGER_PICTUREWIDGET_VERT_LINE_RIGHT_MARGIN = 5
var const_APP_FILE_MANAGER_PICTUREWIDGET_HORIZ_LINE_BOTTOM_MARGIN = 5

var const_PICTURE_WIDGET_ITEM_WIDTH =  245
var const_PICTURE_WIDGET_ITEM_HIGHT =  188
var const_PICTURE_WIDGET_COVER_MARGIN =  9
var const_PICTURE_WIDGET_COVER_WIDTH =  212
var const_PICTURE_WIDGET_COVER_FOLDER_HIGHT =  121
var const_PICTURE_WIDGET_COVER_PHOTO_HIGHT =  150
var const_PICTURE_WIDGET_CHECKBOX_TOP_MARGIN =  11
var const_PICTURE_WIDGET_CHECKBOX_LEFT_MARGIN =  180
var const_PICTURE_WIDGET_CHECKBOX_LEFT_MARGIN_MIDDLE_EAST =  11
var const_PICTURE_WIDGET_NAME_FOLDER_TOP_MARGIN =  149
var const_PICTURE_WIDGET_NAME_FOLDER_LEFT_MARGIN =  9
var const_PICTURE_WIDGET_NAME_FOLDER_WIDTH =  212
var const_APP_FILE_MANAGER_PIXEL_SIZE_22 = 22
var const_APP_FILE_MANAGER_FONT_HDB = "HDB"
var const_APP_FILE_MANAGER_FONT_HDR = "HDR"
//modified by aettie.ji for ME font 20131015
var const_APP_FILE_MANAGER_FONT_NEW_HDB = "DH_HDB"
var const_APP_FILE_MANAGER_FONT_NEW_HDR = "DH_HDR"
var const_APP_FILE_MANAGER_COLOR_BUTTON_GREY = "#2F2F2F"
var const_APP_FILE_MANAGER_PICTURE_FILE_MANAGER_FOCUS_WIDTH = 245
var const_APP_FILE_MANAGER_PICTURE_FILE_MANAGER_FOCUS_HIGHT = 188

var const_APP_FILE_MANAGER_PICTURE_GRID_VIEW__WIDTH = 248
var const_APP_FILE_MANAGER_PICTURE_GRID_VIEW__HIGHT = 237 // modified by Dmitry Bykov 05.04.13

// UsbJukebox widget
var const_APP_FILE_MANAGER_USBJUKEBOX_WIDTH = 250
var const_APP_FILE_MANAGER_USBJUKEBOX_TOP_MERGIN = 160
var const_APP_FILE_MANAGER_USBJUKEBOX_ITEM_WIDTH = 250
var const_APP_FILE_MANAGER_USBJUKEBOX_ITEM_HEIGHT = 240
var const_APP_FILE_MANAGER_USBJUKEBOX_ITEM_ICON_TOP_MARGIN = 67
var const_APP_FILE_MANAGER_USBJUKEBOX_ITEM_ICON_LEFT_MARGIN = 85
var const_APP_FILE_MANAGER_USBJUKEBOX_ITEM_TEXT_TOP_MARGIN = 164
var const_APP_FILE_MANAGER_USBJUKEBOX_TEXT_COLOR_N = "#9E9E9E"
var const_APP_FILE_MANAGER_USBJUKEBOX_TEXT_COLOR_S = "#FAFAFA"
var const_APP_FILE_MANAGER_USBJUKEBOX_FONT_SIZE = 24

// VideoWidget
var const_APP_FILE_MANAGER_PIXEL_SIZE_40 = 40
//var const_APP_FILE_MANAGER_VIDEOWIDGET_HEIGHT = 110
var const_APP_FILE_MANAGER_VIDEOWIDGET_HEIGHT = 110 //modified by Dmitry 02.08.2013 according 05Jul spec
var const_APP_FILE_MANAGER_VIDEOWIDGET_EDIT_HEIGHT = 112 //added by aettie 2013.03.05 for New UX
var const_APP_FILE_MANAGER_VIDEOWIDGET_LIST_WIDTH = 967
var const_APP_FILE_MANAGER_VIDEOWIDGET_LIST_LEFT_MARGIN = 15
//var const_APP_FILE_MANAGER_VIDEOWIDGET_EDIT_LIST_LEFT_MARGIN = 37
var const_APP_FILE_MANAGER_VIDEOWIDGET_EDIT_LIST_LEFT_MARGIN = 14 //modified by aettie 2013.03.05 for New UX
//by aettie for NEW GUI
//var const_APP_FILE_MANAGER_VIDEOWIDGET_FRAME_LEFT_MARGIN = 105
var const_APP_FILE_MANAGER_VIDEOWIDGET_FRAME_LEFT_MARGIN = 67
var const_APP_FILE_MANAGER_VIDEOWIDGET_FRAME_TOP_MARGIN = 10
var const_APP_FILE_MANAGER_VIDEOWIDGET_COVER_HEIGHT = 85
var const_APP_FILE_MANAGER_VIDEOWIDGET_COVER_WIDTH = 114
//var const_APP_FILE_MANAGER_VIDEOWIDGET_ICON_PLAY_LEFT_MARGIN = 145
var const_APP_FILE_MANAGER_VIDEOWIDGET_ICON_PLAY_LEFT_MARGIN = 183
var const_APP_FILE_MANAGER_VIDEOWIDGET_ICON_PLAY_TOP_MARGIN = 18
//var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_LEFT_MARGIN = 218
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_LEFT_MARGIN = 257
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_TOP_MARGIN = 47
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_WIDTH = 893
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_EDIT_WIDTH = 596
var const_APP_FILE_MANAGER_VIDEOWIDGET_CHECK_LEFT_MARGIN = 939
var const_APP_FILE_MANAGER_VIDEOWIDGET_CHECK_TOP_MARGIN = 32
var const_APP_FILE_MANAGER_VIDEOWIDGET_LIST_VIEW_EDIT_WIDTH = 1030

var const_APP_FILE_MANAGER_SCROLL_BIG_TYPE = 1
var const_APP_FILE_MANAGER_SCROLL_SMALL_TYPE= 0


var const_VIDEO_WIDGET_ANIMATION_WIDTH =  170
var const_APP_FILE_MANAGER_VIDEOWIDGET_WIDTH = 239
var const_APP_FILE_MANAGER_VIDEOWIDGET_BG_FRAME_LEFT_MARGIN = 22
var const_APP_FILE_MANAGER_VIDEOWIDGET_BG_FRAME_TOP_MARGIN = 43
var const_APP_FILE_MANAGER_VIDEOWIDGET_THUMBNAIL_LEFT_MARGIN = 22 + 5
var const_APP_FILE_MANAGER_VIDEOWIDGET_THUMBNAIL_TOP_MARGIN = 47
var const_APP_FILE_MANAGER_VIDEOWIDGET_THUMBNAIL_WIDTH = 180
var const_APP_FILE_MANAGER_VIDEOWIDGET_THUMBNAIL_HEIGHT = 130
var const_APP_FILE_MANAGER_VIDEOWIDGET_VERT_LINE_RIGHT_MARGIN = 5
var const_APP_FILE_MANAGER_VIDEOWIDGET_HORIZ_LINE_BOTTOM_MARGIN = 5
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_WITHOUT_PLAY_ICON_LEFT_MARGIN = 30
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_WITH_PLAY_ICON_LEFT_MARGIN = 63
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_COLOR = "#FAFAFA"
var const_APP_FILE_MANAGER_VIDEOWIDGET_TEXT_PIXEL_SIZE = 24
var const_APP_FILE_MANAGER_VIDEOWIDGET_ROW_COUNT_OF_ELEMENTS = 4

// BottomArea
var const_APP_FILE_MANAGER_BOTTOMAREA_WIDTH = 1280
var const_APP_FILE_MANAGER_BOTTOMAREA_HEIGHT = 81
var const_APP_FILE_MANAGER_BOTTOMAREA_TEXT_COLOR = "#FAFAFA"
var const_APP_FILE_MANAGER_BOTTOMAREA_FONT_SIZE = 24

// MusicFilter
var const_APP_FILE_MANAGER_MUSIC_FILTER_WIDTH = 148
var const_APP_FILE_MANAGER_MUSIC_FILTER_TOP_MARGIN = 14
var const_APP_FILE_MANAGER_MUSIC_FILTER_RIGHT_MARGIN = 36
var const_APP_FILE_MANAGER_MUSIC_FILTER_ITEM_WIDTH = 148
var const_APP_FILE_MANAGER_MUSIC_FILTER_ITEM_HEIGHT = 150
var const_APP_FILE_MANAGER_MUSIC_FILTER_ITEM_ICON_TOP_MARGIN = 20
var const_APP_FILE_MANAGER_MUSIC_FILTER_ITEM_ICON_LEFT_MARGIN = 46
var const_APP_FILE_MANAGER_MUSIC_FILTER_ITEM_TEXT_BOTTOM_MARGIN = 39
var const_APP_FILE_MANAGER_MUSIC_FILTER_ITEM_TEXT_COLOR_N = "#9E9E9E"
var const_APP_FILE_MANAGER_MUSIC_FILTER_ITEM_TEXT_COLOR_S = "#FAFAFA"
var const_APP_FILE_MANAGER_MUSIC_FILTER_TEXT_PIXEL_SIZE = 28

//
var const_APP_FILE_MANAGER_SCROLL_HEIGHT = 476
var const_APP_FILE_MANAGER_SCROLL_EDIT_HEIGHT = 522
var const_APP_FILE_MANAGER_SCROLL_LEFT_MARGIN = 1261
// removed by Dmitry 03.05.13
var const_APP_FILE_MANAGER_RIGHT_BOTTOMAREA_WIDTH = 250
var const_APP_FILE_MANAGER_SCROLL_EDIT_MODE_LEFT_MARGIN = 1261 - const_APP_FILE_MANAGER_CONTENT_AREA_LEF_MARGIN - const_APP_FILE_MANAGER_RIGHT_BOTTOMAREA_WIDTH
var const_APP_FILE_MANAGER_SCROLL_TOP_MARGIN = 17
var const_APP_FILE_MANAGER_SCROLL_RIGHT_MARGIN = 9 // added by Dmitry 03.05.13
var const_APP_FILE_MANAGER_LIST_TOP_MARGIN = 70
var const_APP_FILE_MANAGER_LIST_BOTTOM_MARGIN = 10 // added by Dmitry Bykov 05.04.13

//Navigator element
//var const_APP_FILE_MANAGER__PIXEL_SIZE_26 =  26
var const_APP_FILE_MANAGER__PIXEL_SIZE_30 = 30 // modified by eunhye 2013.02.28 for New UX
var const_APP_FILE_MANAGER__COLOR_BRIGHT_GREY =  "#FAFAFA"
var const_APP_FILE_MANAGER__COLOR_BLUE = "#7CBDFF"

var const_APP_FILE_MANAGER_NAVIGATOR_TOP_MARGIN = 164
var const_APP_FILE_MANAGER_NAVIGATOR_HEIGHT = 54
var const_APP_FILE_MANAGER_NAVIGATOR_WIDTH = 1186
var const_APP_FILE_MANAGER_NAVIGATOR_ICO_FOLDER_TOP_MARGIN = 12
//var const_APP_FILE_MANAGER_NAVIGATOR_ICO_FOLDER_LEFT_MARGIN = 30
var const_APP_FILE_MANAGER_NAVIGATOR_ICO_FOLDER_LEFT_MARGIN = 25 // modified by eunhye 2013.03.02 for New UX
var const_APP_FILE_MANAGER_NAVIGATOR_TEXT_TOP_MARGIN = 29 //modifed by aettie 20131017 UX fix
//var const_APP_FILE_MANAGER_NAVIGATOR_TEXT_LEFT_MARGIN = 83
var const_APP_FILE_MANAGER_NAVIGATOR_TEXT_LEFT_MARGIN = 71 // modified by eunhye 2013.03.02 for New UX
//{added by edo.lee 2012.08.21 for UX Photo(LGE) #5
var const_APP_FILE_MANAGER_SCROOL_MIN_COUNT = 10
//}added by edo.lee
//IMAGE_DRS
var const_APP_FILE_MANAGER_LOCKOUT_ICON_TOP_OFFSET = 124
var const_APP_FILE_MANAGER_LOCKOUT_ICON_N_TOP_OFFSET = const_APP_FILE_MANAGER_LOCKOUT_ICON_TOP_OFFSET - const_APP_FILE_MANAGER_NAVIGATOR_HEIGHT
