//display
var const_DISPLAY_WIDHT = 1280
var const_DISPLAY_HEIGTH = 720
//backgrounds
var const_TYPE_B_WIDHT = 1066
var const_TYPE_B_HEIGTH = 456
var const_TOP_BORDER = 13
var const_LEFT_BORDER = 13
var const_RIGHT_BORDER = 15
var const_BOTTOM_BORDER = 19

/** Popup settings */
var const_TITLE_HEIGHT = 113
var const_POPUP_BORDER_WIDTH = 15
var const_POPUP_DIMMED_Y = 477
var const_POPUP_BLACKOUT = 0.8
var const_BASE_POPUP_X_INDENT = 110

/** Title text */
var const_TITLE_TEXT_PT = 44
var const_TITLE_TEXT_COLOR = "#B6C9FF"
var const_TITLE_TEXT_COLOR_BG = "#000000"
var const_TITLE_X = 45
var const_TITLE_MY = 59
var const_CONTENT_TEXT_PT = 28

//buttons
var const_TEXT_BUTTON_MY = 42

//popup types
var const_POPUPTYPE_A =0
var const_POPUPTYPE_B =1

//popup margin
var const_POPUPTYPE_A_TOP_MARGIN = 208
var const_POPUPTYPE_A_LEFT_MARGIN = 93
var const_POPUPTYPE_B_TOP_MARGIN = 171
var const_POPUPTYPE_B_LEFT_MARGIN = 93
var const_POPUPTYPE_C_TOP_MARGIN = 454 - 83
var const_POPUPTYPE_C_LEFT_MARGIN = 250
var const_POPUPTYPE_D_TOP_MARGIN = 168
var const_POPUPTYPE_D_LEFT_MARGIN = 93
var const_POPUPTYPE_E_TOP_MARGIN = 131
var const_POPUPTYPE_E_LEFT_MARGIN = 93
var const_POPUPTYPE_F_TOP_MARGIN = 404
var const_POPUPTYPE_F_LEFT_MARGIN = 250

var const_POPUPTYPE_D_CONTEXT_TOP_MARGIN = 80
var const_POPUPTYPE_G_TOP_MARGIN = 130

var const_POPUPTYPE_ETC01_TOP_MARGIN = 119
var const_POPUPTYPE_ETC01_LEFT_MARGIN = 93
//warning
var const_FIRST_LINE_MY = 185
var const_SECOND_LINE_MY = 53 + const_FIRST_LINE_MY
var const_BUTTON_Y = 69 + const_SECOND_LINE_MY
var const_FIRST_LINE_MY_ALONG = 197

//loading
var const_LOADING_TOP_MARGIN = 50
var const_LOADING_LEFT_MARGIN = 309

/** Vertical Scrollbar */
var const_V_SCROLLBAR_RIGHT_MARGIN = 0
var const_V_SCROLLBAR_TOP_MARGIN   = 13
var const_V_SCROLLBAR_3LINE_HEIGHT = 216
var const_V_SCROLLBAR_4LINE_HEIGHT = 304
var const_V_SCROLLBAR_WIDTH = 53

/** Popup content */
var const_TEXT_COLOR = "#FAFAFA"
var const_TEXT_COLOR_BG = "#000000"
var const_TEXT_COLOR_HIGHLIGHT = "#0087EF"
var const_TEXT_PT = 32
var const_TEXT_LIST_PT = 32
var const_TEXTONLY_SPACING = 51 - const_TEXT_PT
var const_TEXT_FONT_FAMILY = "DH_HDB"
var const_TEXT_TOAST_PT = 36

var const_TEXT_SPACING = 70 - const_TEXT_PT
var const_TEXT_SPACING_32 = 46 - const_TEXT_PT

var const_TEXT_LEFTALIGN_LEFT_MARGIN = 78
var const_TEXT_CENTERALIGN_LEFT_MARGIN = 57
var const_TEXT_AREA_WIDTH_LEFT_ALIGN = 780
var const_TEXT_AREA_WIDTH_CENTER_ALIGN = 710
var const_POPUP_TYPE_A_CONTENT_AREA_WIDTH_WITH_BUTTON = 679
var const_POPUP_TYPE_A_CONTENT_AREA_WIDTH_WITH_NOBUTTON = 439 + 541
var const_POPUP_TYPE_B_CONTENT_AREA_WIDTH_WITH_BUTTON = 740 + 69

var const_BUTTON_SPACING = 3
var const_BUTTON_TEXT_PT = 36
var const_BUTTON_TEXT_PT_2LINE = 32

var const_BUTTON_TEXT_COLOR = "#FAFAFA"
var const_BUTTON_TEXT_COLOR_BG = "#000000"
//Button margin
var const_BUTTON_LEFT_MARGIN = 780
//var const_BUTTON_LEFT_MARGIN_REVERSE = 25
var const_BUTTON_LEFT_MARGIN_REVERSE = 18

var const_BUTTON_A_1_FOCUS_ICON_LEFT_MARGIN = -2
var const_BUTTON_B_1_FOCUS_ICON_LEFT_MARGIN = -2
var const_BUTTON_A_2_FOCUS_ICON_LEFT_MARGIN = -6
var const_BUTTON_B_2_FOCUS_ICON_LEFT_MARGIN = -7
var const_BUTTON_3_FOCUS_ICON_LEFT_MARGIN = -14
var const_BUTTON_4_FOCUS_ICON_LEFT_MARGIN = -17



var const_BUTTON_A_1_FOCUS_ICON_LEFT_MARGIN_REVERSE = 246-18
//var const_BUTTON_B_1_FOCUS_ICON_LEFT_MARGIN_REVERSE = -2
var const_BUTTON_A_2_FOCUS_ICON_LEFT_MARGIN_REVERSE = 246+4-18
var const_BUTTON_B_2_FOCUS_ICON_LEFT_MARGIN_REVERSE = 246+5-18

var const_BUTTON_3_FOCUS_ICON_LEFT_MARGIN_REVERSE = 246+12-18
var const_BUTTON_4_FOCUS_ICON_LEFT_MARGIN_REVERSE = 248+13-18

var const_TEXT_1LINE_BUTTON_SPACING = 131
var const_TEXT_2LINE_BUTTON_SPACING = 89
var const_TEXT_3LINE_BUTTON_SPACING = 54

var const_DIMMED_TEXT_PT = 34
var const_DIMMED_TEXT_PT_FOR_PHOTO_1_TYPE = 80
var const_DIMMED_TEXT_SPACING = 60 - const_DIMMED_TEXT_PT
var const_DIMMED_DEFAULT_TYPE = 0
var const_DIMMED_PHOTO_1_TYPE = 1
var const_DIMMED_PHOTO_2_TYPE = 2

var const_THUMBNAIL_TEXT_PT = 28
var const_THUMBNAIL_IMG_X = 46
var const_THUMBNAIL_IMG_Y = 130
var const_THUMBNAIL_IMG_SPACING_Y = 8
var const_THUMBNAIL_LIST_X = 329
var const_THUMBNAIL_LIST_Y = 113
var const_THUMBNAIL_LIST_ITEM_HEIGHT = 80
var const_THUMBNAIL_LIST_ITEM_WIDTH = 708
var const_THUMBNAIL_ALBUM_IMAGE_WIDTH = 241
var const_THUMBNAIL_ALBUM_IMAGE_HEIGHT = 241
var const_THUMBNAIL_ALBUM_NAME_INDENT = 12

var const_PROGRESS_BAR_BTN_SPACING = 44

var const_LIST_LIST_ITEM_HEIGHT = 102
var const_LIST_LIST_X = 39
var const_LIST_LIST_Y = 110
var const_LIST_1_LINE_TOP_MARGIN = 110
var const_LIST_2_LINE_TOP_MARGIN = 69
var const_LIST_3_LINE_TOP_MARGIN = 28
var const_LIST_4_LINE_TOP_MARGIN = 24
var const_LIST_LEFT_MARGIN = 26

var const_TOAST_1_LINE_TOP_MARGIN = 103 - 18
var const_TOAST_2_LINE_TOP_MARGIN = 73 - 18
var const_TOAST_LEFT_MARGIN = 34
var const_TOAST_TEXTAREA_WIDTH = 712
var const_TOAST_TEXTAREA_HEIGHT = 60
var const_TOAST_SPACING = 24

var const_CHECKLIST_TEXT_WIDTH = 610

var const_RADIO_LIST_ITEM_HEIGHT = 82
var const_RADIO_LIST_X = 39
var const_RADIO_LIST_Y = 110
var const_RADIO_BTN_IMG_X = 945
var const_RADIO_TEXT_BUTTON_SPACING = 20
var const_SLIDER_BTN_SPACING = 45

var const_RADIO_BTN_SPACING = 12
var const_RADIO_TEXT_UNDER_SPACING = 20
var const_POPUP_RADIO_ITEM_SPACING = 53
var const_POPUP_RADIO_BTN_SPACING = const_RADIO_TEXT_UNDER_SPACING + const_TEXT_PT + 45
var const_RADIO_CONTENT_TEXT_COLOR = "#9E9E9E"
var const_RADIO_CONTENT_TEXT_SIZE = 50
var const_RADIO_CONTENT_TEXT_FAMILY = "DH_HDB"
var const_RADIO_CONTENT_TEXT_SPACING = 0

var const_POPUP_GUIDELINE_ITEM_SPACING = 47
var const_POPUP_GUIDELINE_BTN_SPACING = 19

var const_JOG_EVENT_ARROW_UP = 0
var const_JOG_EVENT_ARROW_DOWN = 1
var const_JOG_EVENT_ARROW_LEFT = 2
var const_JOG_EVENT_ARROW_RIGHT = 3
var const_JOG_EVENT_WHEEL_LEFT = 4
var const_JOG_EVENT_WHEEL_RIGHT = 5
var const_JOG_EVENT_CENTER = 6
var const_JOG_EVENT_HOLD_LEFT = 7
var const_JOG_EVENT_HOLD_RIGHT = 8

var const_LIST_AND_BUTTONS_ITEM_HEIGHT = 82
var const_LIST_AND_BUTTONS_ITEM_HEIGHT_1 = 90

var const_GRID_ITEM_HEIGHT = 130
var const_GRID_ITEM_WIDTH = 130
var const_GRID_ROWS_COUNT = 2
var const_GRID_ITEM_SPACING = 10
var const_GRID_SPACING_TO_BTNS = 50

var const_LANGCONTEXT = "main"

var RADIO_LIST_POP_UP_LIST = 0;
var RADIO_LIST_POP_UP_LEFT_BTN = 1;
var RADIO_LIST_POP_UP_RIGHT_BTN = 2;

var const_POPUP_DIMMED_X_OFFSET = 259;
var const_POPUP_DIMMED_Y_OFFSET = 463;


//Time Picker Constants
var const_TIME_PICKER_FONT_FAMILY_HDR = "DH_HDR"
var const_TIME_PICKER_FONT_FAMILY_HDB = "DH_HDB"
var const_TIME_PICKER_FONT_SIZE_TEXT_32PT = 32
var const_TIME_PICKER_FONT_SIZE_TEXT_44PT = 44
var const_COLOR_TEXT_GREY = "#C1C1C1"


var const_TIME_PICKER_CLOCK_MIN_YEAR = 2012
var const_TIME_PICKER_CLOCK_MAX_YEAR = 2036
var const_TIME_PICKER_CLOCK_MIN_MONTH = 1
var const_TIME_PICKER_CLOCK_MAX_MONTH = 12
var const_TIME_PICKER_CLOCK_MIN_DAY = 1
var const_TIME_PICKER_CLOCK_MIN_HOUR = 1
var const_TIME_PICKER_CLOCK_MIN_HOUR_24H = 0
var const_TIME_PICKER_CLOCK_MAX_HOUR = 12
var const_TIME_PICKER_CLOCK_MAX_HOUR_24H = 23
var const_TIME_PICKER_CLOCK_MIN_MINUTE = 0
var const_TIME_PICKER_CLOCK_MAX_MINUTE = 59

var const_TIME_PICKER_START_POSITION_X = 46
var const_TIME_PICKER_START_POSITION_Y = 51
var const_TIME_PICKER_YEAR_WIDTH =165
var const_TIME_PICKER_OTHER_WIDTH =107
var const_TIME_PICKER_VERT_SPIN_START_POSITION_Y = 47
var const_TIME_PICKER_ELEMENTS_MARGIN = 4
//var const_TIME_PICKER_START_POSITION_X_REVERSE = 329 + 111 + 111 + 111 + 111 + 111
var const_TIME_PICKER_START_POSITION_X_REVERSE = 329 + 111 + 111 + 169 + 111 + 111

var const_TIME_PICKER_BUTTON_TOP_MARGIN = 446
var const_TIME_PICKER_OK_BUTTON_LEFT_MARGIN = 118
var const_TIME_PICKER_CANCEL_BUTTON_LEFT_MARGIN = 546

var const_TIME_PICKER_BORDER_MARGIN = 5

var const_PROPERTY_TABLE_ITEM_MAX_WIDTH = 488
var const_PROPERTY_TABLE_DIVIDER_WIDTH = 20
var const_PROPERTY_TABLE_MAX_WIDTH = 661
var const_PROPERTY_TABLE_TEXT_MAX_WIDTH = const_PROPERTY_TABLE_MAX_WIDTH - const_PROPERTY_TABLE_DIVIDER_WIDTH
