/** Path to resource */
var const_POPUP_RES_PATH = "/app/share/images/popup/"
var const_POPUP_RES_PATH_LOADING = "/app/share/images/popup/loading/"
var const_POPUP_RES_PATH_REVERSE= "/app/share/images/popup/arab/"
var const_POPUP_LOAD_RES_PATH = "/app/share/images/popup/loading/"
var const_MUSIC_RES_PATH = "/app/share/images/music/"
var const_GENERAL_RES_PATH = "/app/share/images/general/"
var const_SETTINGS_RES_PATH = "/app/share/images/settings/"
var const_VIDEO_RES_PATH = "/app/share/images/video/"
var const_PHOTO_RES_PATH = "/app/share/images/photo/"

/** PopUp types */
var const_POPUP_TYPE_A = const_POPUP_RES_PATH + "bg_type_a.png"
var const_POPUP_TYPE_B = const_POPUP_RES_PATH + "bg_type_b.png"
var const_POPUP_TYPE_C = const_POPUP_RES_PATH + "bg_type_c.png"
var const_POPUP_TYPE_D = const_POPUP_RES_PATH + "bg_type_d.png"
var const_POPUP_TYPE_E = const_POPUP_RES_PATH + "bg_type_e.png"
var const_POPUP_TYPE_F = const_POPUP_RES_PATH + "bg_type_f.png"
var const_POPUP_TYPE_G = const_POPUP_RES_PATH + "bg_type_g.png"

var const_POPUP_TYPE_B_FOCUS_REVERSE = const_POPUP_RES_PATH_REVERSE + "bg_type_b_f.png"
var const_POPUP_TYPE_B_FOCUS = const_POPUP_RES_PATH + "bg_type_b_f.png"

//var const_POPUP_TYPE_C_01 = const_POPUP_RES_PATH + "popup_c_01_bg.png"
//var const_POPUP_TYPE_C_02 = const_POPUP_RES_PATH + "popup_c_02_bg.png"
var const_POPUP_TYPE_ETC_01 = const_POPUP_RES_PATH + "bg_type_etc_01.png"
var const_POPUP_TYPE_ETC_01_f = const_POPUP_RES_PATH + "bg_type_etc_01_f.png"
var const_POPUP_TYPE_ETC_02 = const_POPUP_RES_PATH + "popup_etc_02_bg.png"
var const_POPUP_TYPE_ETC_03 = const_POPUP_RES_PATH + "popup_etc_03_bg.png"
var const_POPUP_TYPE_ETC_04 = const_POPUP_RES_PATH + "popup_etc_04_bg.png"
var const_POPUP_TYPE_ETC_05 = const_POPUP_RES_PATH + "popup_etc_05_bg.png"
var const_POPUP_TYPE_ETC_06 = const_POPUP_RES_PATH + "popup_etc_06_bg.png"

var const_POPUP_TYPE_DIMMED = const_POPUP_RES_PATH + "popup_dim_bg.png"
var const_POPUP_TYPE_DIMMED_PHOTO_1 = const_VIDEO_RES_PATH + "bg_ff.png"
var const_POPUP_TYPE_DIMMED_PHOTO_2 = const_PHOTO_RES_PATH + "popup_dimmed_photo_bg.png"
var const_POPUP_TYPE_PHOTO_ZOOM = const_VIDEO_RES_PATH + "popup_video.png"

/** Button list */
var const_POPUP_BUTTON_ICON_F = const_POPUP_RES_PATH + "light.png"
var const_POPUP_BUTTON_LINE = const_POPUP_RES_PATH + "line_type_a.png"

var const_POPUP_A_01_BUTTON_N = const_POPUP_RES_PATH + "btn_type_a_01_n.png"
var const_POPUP_A_01_BUTTON_P = const_POPUP_RES_PATH + "btn_type_a_01_p.png"
var const_POPUP_A_01_BUTTON_F = const_POPUP_RES_PATH + "btn_type_a_01_f.png"

var const_POPUP_A_01_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_01_n.png"
var const_POPUP_A_01_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_01_p.png"
var const_POPUP_A_01_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_01_f.png"

var const_POPUP_A_02_01_BUTTON_N = const_POPUP_RES_PATH + "btn_type_a_02_n.png"
var const_POPUP_A_02_01_BUTTON_P = const_POPUP_RES_PATH + "btn_type_a_02_p.png"
var const_POPUP_A_02_01_BUTTON_F = const_POPUP_RES_PATH + "btn_type_a_02_f.png"
var const_POPUP_A_02_02_BUTTON_N = const_POPUP_RES_PATH + "btn_type_a_03_n.png"
var const_POPUP_A_02_02_BUTTON_P = const_POPUP_RES_PATH + "btn_type_a_03_p.png"
var const_POPUP_A_02_02_BUTTON_F = const_POPUP_RES_PATH + "btn_type_a_03_f.png"

var const_POPUP_A_02_01_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_02_n.png"
var const_POPUP_A_02_01_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_02_p.png"
var const_POPUP_A_02_01_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_02_f.png"
var const_POPUP_A_02_02_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_03_n.png"
var const_POPUP_A_02_02_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_03_p.png"
var const_POPUP_A_02_02_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_a_03_f.png"

var const_POPUP_B_01_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_01_n.png"
var const_POPUP_B_01_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_01_p.png"
var const_POPUP_B_01_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_01_f.png"

var const_POPUP_B_01_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_01_n.png"
var const_POPUP_B_01_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_01_p.png"
var const_POPUP_B_01_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_01_f.png"

var const_POPUP_B_02_01_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_02_n.png"
var const_POPUP_B_02_01_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_02_p.png"
var const_POPUP_B_02_01_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_02_f.png"
var const_POPUP_B_02_02_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_03_n.png"
var const_POPUP_B_02_02_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_03_p.png"
var const_POPUP_B_02_02_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_03_f.png"

var const_POPUP_B_02_01_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_02_n.png"
var const_POPUP_B_02_01_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_02_p.png"
var const_POPUP_B_02_01_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_02_f.png"
var const_POPUP_B_02_02_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_03_n.png"
var const_POPUP_B_02_02_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_03_p.png"
var const_POPUP_B_02_02_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_03_f.png"

var const_POPUP_B_03_01_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_04_n.png"
var const_POPUP_B_03_01_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_04_p.png"
var const_POPUP_B_03_01_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_04_f.png"
var const_POPUP_B_03_02_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_05_n.png"
var const_POPUP_B_03_02_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_05_p.png"
var const_POPUP_B_03_02_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_05_f.png"
var const_POPUP_B_03_03_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_06_n.png"
var const_POPUP_B_03_03_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_06_p.png"
var const_POPUP_B_03_03_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_06_f.png"

var const_POPUP_B_03_01_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_04_n.png"
var const_POPUP_B_03_01_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_04_p.png"
var const_POPUP_B_03_01_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_04_f.png"
var const_POPUP_B_03_02_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_05_n.png"
var const_POPUP_B_03_02_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_05_p.png"
var const_POPUP_B_03_02_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_05_f.png"
var const_POPUP_B_03_03_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_06_n.png"
var const_POPUP_B_03_03_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_06_p.png"
var const_POPUP_B_03_03_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_06_f.png"

var const_POPUP_B_04_01_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_07_n.png"
var const_POPUP_B_04_01_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_07_p.png"
var const_POPUP_B_04_01_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_07_f.png"
var const_POPUP_B_04_02_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_08_n.png"
var const_POPUP_B_04_02_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_08_p.png"
var const_POPUP_B_04_02_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_08_f.png"
var const_POPUP_B_04_03_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_09_n.png"
var const_POPUP_B_04_03_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_09_p.png"
var const_POPUP_B_04_03_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_09_f.png"
var const_POPUP_B_04_04_BUTTON_N = const_POPUP_RES_PATH + "btn_type_b_10_n.png"
var const_POPUP_B_04_04_BUTTON_P = const_POPUP_RES_PATH + "btn_type_b_10_p.png"
var const_POPUP_B_04_04_BUTTON_F = const_POPUP_RES_PATH + "btn_type_b_10_f.png"

var const_POPUP_B_04_01_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_07_n.png"
var const_POPUP_B_04_01_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_07_p.png"
var const_POPUP_B_04_01_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_07_f.png"
var const_POPUP_B_04_02_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_08_n.png"
var const_POPUP_B_04_02_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_08_p.png"
var const_POPUP_B_04_02_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_08_f.png"
var const_POPUP_B_04_03_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_09_n.png"
var const_POPUP_B_04_03_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_09_p.png"
var const_POPUP_B_04_03_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_09_f.png"
var const_POPUP_B_04_04_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_10_n.png"
var const_POPUP_B_04_04_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_10_p.png"
var const_POPUP_B_04_04_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_type_b_10_f.png"

var const_POPUP_ETC01_02_01_BUTTON_N = const_POPUP_RES_PATH + "btn_sxm_01_n.png"
var const_POPUP_ETC01_02_01_BUTTON_P = const_POPUP_RES_PATH + "btn_sxm_01_p.png"
var const_POPUP_ETC01_02_01_BUTTON_F = const_POPUP_RES_PATH + "btn_sxm_01_f.png"
var const_POPUP_ETC01_02_02_BUTTON_N = const_POPUP_RES_PATH + "btn_sxm_02_n.png"
var const_POPUP_ETC01_02_02_BUTTON_P = const_POPUP_RES_PATH + "btn_sxm_02_p.png"
var const_POPUP_ETC01_02_02_BUTTON_F = const_POPUP_RES_PATH + "btn_sxm_02_f.png"

var const_POPUP_ETC01_02_01_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_sxm_01_n.png"
var const_POPUP_ETC01_02_01_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_sxm_01_p.png"
var const_POPUP_ETC01_02_01_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_sxm_01_f.png"
var const_POPUP_ETC01_02_02_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_sxm_02_n.png"
var const_POPUP_ETC01_02_02_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_sxm_02_p.png"
var const_POPUP_ETC01_02_02_BUTTON_F_REVERSE = const_POPUP_RES_PATH_REVERSE + "btn_sxm_02_f.png"

//var const_POPUP_02_BUTTON_N = const_POPUP_RES_PATH + "btn_popup_l_n.png"
//var const_POPUP_02_BUTTON_P = const_POPUP_RES_PATH + "btn_popup_l_p.png"
//var const_POPUP_03_BUTTON_N = const_POPUP_RES_PATH + "btn_popup_s_n.png"
//var const_POPUP_03_BUTTON_P = const_POPUP_RES_PATH + "btn_popup_s_p.png"
var const_POPUP_04_BUTTON_N = const_POPUP_RES_PATH + "popup_d_btn_n.png"
var const_POPUP_04_BUTTON_P = const_POPUP_RES_PATH + "popup_d_btn_p.png"

var const_POPUP_04_BUTTON_N_REVERSE = const_POPUP_RES_PATH_REVERSE + "popup_d_btn_n.png"
var const_POPUP_04_BUTTON_P_REVERSE = const_POPUP_RES_PATH_REVERSE + "popup_d_btn_p.png"


var const_POPUP_LIST_LINE_699 = const_POPUP_RES_PATH + "list_line_699.png"
var const_POPUP_LIST_LINE = const_POPUP_RES_PATH + "list_line.png"
var const_POPUP_LINE = const_POPUP_RES_PATH + "line_popup.png"
//var const_WARNING_IMG = const_POPUP_RES_PATH + "ico_warning.png"

var const_LOADING_IMG = const_POPUP_RES_PATH + "loading_01.png"
var const_LOADING_IMG_01 = const_POPUP_RES_PATH_LOADING + "loading_01.png"
var const_LOADING_IMG_02 = const_POPUP_RES_PATH_LOADING + "loading_02.png"
var const_LOADING_IMG_03 = const_POPUP_RES_PATH_LOADING + "loading_03.png"
var const_LOADING_IMG_04 = const_POPUP_RES_PATH_LOADING + "loading_04.png"
var const_LOADING_IMG_05 = const_POPUP_RES_PATH_LOADING + "loading_05.png"
var const_LOADING_IMG_06 = const_POPUP_RES_PATH_LOADING + "loading_06.png"
var const_LOADING_IMG_07 = const_POPUP_RES_PATH_LOADING + "loading_07.png"
var const_LOADING_IMG_08 = const_POPUP_RES_PATH_LOADING + "loading_08.png"
var const_LOADING_IMG_09 = const_POPUP_RES_PATH_LOADING + "loading_09.png"
var const_LOADING_IMG_10 = const_POPUP_RES_PATH_LOADING + "loading_10.png"
var const_LOADING_IMG_11 = const_POPUP_RES_PATH_LOADING + "loading_11.png"
var const_LOADING_IMG_12 = const_POPUP_RES_PATH_LOADING + "loading_12.png"
var const_LOADING_IMG_13 = const_POPUP_RES_PATH_LOADING + "loading_13.png"
var const_LOADING_IMG_14 = const_POPUP_RES_PATH_LOADING + "loading_14.png"
var const_LOADING_IMG_15 = const_POPUP_RES_PATH_LOADING + "loading_15.png"
var const_LOADING_IMG_16 = const_POPUP_RES_PATH_LOADING + "loading_16.png"
var const_POPUP_PHOTO_ZOOM_X = const_VIDEO_RES_PATH + "popup_video_x.png"

var const_LIST_HIGHLIGHT_IMG = const_MUSIC_RES_PATH + "icon_list_play.png"
var const_THUMBNAIL_UNDEFINED_IMG = const_MUSIC_RES_PATH + "undefined.jpg"
var const_THUMBNAIL_BG_ALBUM_IMG = const_POPUP_RES_PATH + "bg_album_img.png"

var const_LIST_SCROLL_IMG_T = const_POPUP_RES_PATH + "scroll.png"
var const_LIST_SCROLL_IMG_M = const_POPUP_RES_PATH + "scroll.png"
var const_LIST_SCROLL_IMG_B = const_POPUP_RES_PATH + "scroll.png"
var const_LIST_SCROLL_BG_IMG_3Lines = const_POPUP_RES_PATH + "scroll_bell_bg.png"
var const_LIST_SCROLL_BG_IMG_4Lines = const_POPUP_RES_PATH + "scroll_bg.png"

var const_LIST_SCROLL_IMG_T_REVERSE = const_POPUP_RES_PATH_REVERSE + "scroll.png"
var const_LIST_SCROLL_IMG_M_REVERSE = const_POPUP_RES_PATH_REVERSE + "scroll.png"
var const_LIST_SCROLL_IMG_B_REVERSE = const_POPUP_RES_PATH_REVERSE + "scroll.png"
var const_LIST_SCROLL_BG_IMG_3Lines_REVERSE = const_POPUP_RES_PATH_REVERSE + "scroll_bell_bg.png"
var const_LIST_SCROLL_BG_IMG_4Lines_REVERSE = const_POPUP_RES_PATH_REVERSE + "scroll_bg.png"

var const_PROGRESS_BG_IMG = const_POPUP_RES_PATH + "progress_n.png"
var const_PROGRESS_BAR_IMG = const_POPUP_RES_PATH + "progress_s.png"
var const_PROGRESS_BAR_IMG_RED = const_POPUP_RES_PATH + "progress_s_red.png"

var const_BTN_RADIO_ON_IMG = const_SETTINGS_RES_PATH + "btn_radio_s.png"
var const_BTN_RADIO_OFF_IMG = const_SETTINGS_RES_PATH + "btn_radio_n.png"

var const_BTN_CHECK_ON_IMG = const_POPUP_RES_PATH + "checkbox_s.png"
var const_BTN_CHECK_OFF_IMG = const_POPUP_RES_PATH + "checkbox_n.png"

var const_POPUP_SLIDER_N_IMG = const_POPUP_RES_PATH + "popup_silder_n.png"
var const_POPUP_SLIDER_P_IMG = const_POPUP_RES_PATH + "popup_silder_p.png"
var const_SLIDER_CURSOR_N_IMG = const_SETTINGS_RES_PATH + "slider_cursor_n.png"
var const_SLIDER_CURSOR_S_IMG = const_SETTINGS_RES_PATH + "slider_cursor_s.png"

var const_RADIO_ON_IMG = const_SETTINGS_RES_PATH + "btn_radio_on.png"
var const_RADIO_OFF_IMG = const_SETTINGS_RES_PATH + "btn_radio_off.png"
var const_RADIO_FOCUS_IMG = const_GENERAL_RES_PATH + "radio_f.png"
var const_POPUP_RADIO_BG_IMG = const_POPUP_RES_PATH + "bg_view_mode.png"

var const_POPUP_GUIDELINE_ITEM_1_IMG = const_POPUP_RES_PATH + "guide_line_01.png"
var const_POPUP_GUIDELINE_ITEM_2_IMG = const_POPUP_RES_PATH + "guide_line_02.png"
var const_POPUP_GUIDELINE_ITEM_3_IMG = const_POPUP_RES_PATH + "guide_line_03.png"
var const_POPUP_GUIDELINE_ITEM_4_IMG = const_POPUP_RES_PATH + "guide_line_04.png"

/** Focused Item */
var const_POPUP_LIST_ITEM_FOCUSED_IMG = const_POPUP_RES_PATH + "list_f.png"
var const_POPUP_LIST_ITEM_PRESSSED_IMG = const_POPUP_RES_PATH + "list_p.png"

/** Time Picker Border image */
var const_POPUP_TIME_PICKER_FRAME_L_n = const_POPUP_RES_PATH + "bg_timeset_l_n.png"
var const_POPUP_TIME_PICKER_FRAME_S_n = const_POPUP_RES_PATH + "bg_timeset_s_n.png"
var const_POPUP_TIME_PICKER_FRAME_L_f = const_POPUP_RES_PATH + "bg_timeset_l_f.png"
var const_POPUP_TIME_PICKER_FRAME_S_f = const_POPUP_RES_PATH + "bg_timeset_s_f.png"
var const_POPUP_TIME_PICKER_SPINER_DISABLE_MASK = const_POPUP_RES_PATH + "bg_timeset_s_d.png"

var const_POPUP_TIME_PICKER_BUTTON_L_N = const_POPUP_RES_PATH + "btn_timeset_l_n.png"
var const_POPUP_TIME_PICKER_BUTTON_L_F = const_POPUP_RES_PATH + "btn_timeset_l_f.png"
var const_POPUP_TIME_PICKER_BUTTON_L_P = const_POPUP_RES_PATH + "btn_timeset_l_p.png"
var const_POPUP_TIME_PICKER_BUTTON_s_N = const_POPUP_RES_PATH + "btn_timeset_s_n.png"
var const_POPUP_TIME_PICKER_BUTTON_s_F = const_POPUP_RES_PATH + "btn_timeset_s_f.png"
var const_POPUP_TIME_PICKER_BUTTON_s_P = const_POPUP_RES_PATH + "btn_timeset_s_p.png"

var const_POPUP_TIME_PICKER_ARROW_U_n = const_POPUP_RES_PATH + "ico_timeset_arw_u_n.png"
var const_POPUP_TIME_PICKER_ARROW_U_f = const_POPUP_RES_PATH + "ico_timeset_arw_u_f.png"
var const_POPUP_TIME_PICKER_ARROW_D_n = const_POPUP_RES_PATH + "ico_timeset_arw_d_n.png"
var const_POPUP_TIME_PICKER_ARROW_D_f = const_POPUP_RES_PATH + "ico_timeset_arw_d_f.png"
