import QtQuick 1.0

Item {
    id:stringInfo

    //************************ List Strings ***//
    property string strRDSPtyAll: qsTr("")
    property string strRDSPtyNews:  qsTr("STR_RDS_PTY_NEWS")
    property string strRDSPtyCurrentAffairs:  qsTr("STR_RDS_PTY_CURRENT_AFFAIRS")
    property string strRDSPtyInfomation:  qsTr("STR_RDS_PTY_INFORMATION")
    property string strRDSPtySport:  qsTr("STR_RDS_PTY_SPORT")
    property string strRDSPtyEducation:  qsTr("STR_RDS_PTY_EDUCATION")
    property string strRDSPtyDrama:  qsTr("STR_RDS_PTY_DRAMA")
    property string strRDSPtyCulture:  qsTr("STR_RDS_PTY_CULTURE")
    property string strRDSPtyScience:  qsTr("STR_RDS_PTY_SCIENCE")
    property string strRDSPtyVaried:  qsTr("STR_RDS_PTY_VARIED")
    property string strRDSPtyPopMusic:  qsTr("STR_RDS_PTY_POP_MUSIC")
    property string strRDSPtyRockMusic:  qsTr("STR_RDS_PTY_ROCK_MUSIC")
    property string strRDSPtyEasyListeningMusic:  qsTr("STR_RDS_PTY_EASY_LISTENING_MUSIC")
    property string strRDSPtyLightClassicalMusic:  qsTr("STR_RDS_PTY_LIGHT_CLASSICAL_MUSIC")
    property string strRDSPtySeriousClassicalMusic:  qsTr("STR_RDS_PTY_SERIOUS_CLASSICAL_MUSIC")
    property string strRDSPtyOtherMusic:  qsTr("STR_RDS_PTY_OTHER_MUSIC")
    property string strRDSPtyWeather:  qsTr("STR_RDS_PTY_WEATHER")
    property string strRDSPtyFinance:  qsTr("STR_RDS_PTY_FINANCE")
    property string strRDSPtyChildrensProgram:  qsTr("STR_RDS_PTY_CHINDRENS_PROGRAME")
    property string strRDSPtySocialAffairs:  qsTr("STR_RDS_PTY_SOCIAL_AFFAIRS")
    property string strRDSPtyReligion:  qsTr("STR_RDS_PTY_RELIGION")
    property string strRDSPtyPhoneIn:  qsTr("STR_RDS_PTY_PHONE_IN")
    property string strRDSPtyTravle:  qsTr("STR_RDS_PTY_TRAVEL")
    property string strRDSPtyLeisure:  qsTr("STR_RDS_PTY_LEISURE")
    property string strRDSPtyJazzMusic:  qsTr("STR_RDS_PTY_JAZZ_MUSIC")
    property string strRDSPtyCountryMusic:  qsTr("STR_RDS_PTY_COUNTRY_MUSIC")
    property string strRDSPtyNationalMusic:  qsTr("STR_RDS_PTY_NATIONAL_MUSIC")
    property string strRDSPtyOldiesMusic:  qsTr("STR_RDS_PTY_OLDIES_MUSIC")
    property string strRDSPtyFolkMusic:  qsTr("STR_RDS_PTY_FOLK_MUSIC")
    property string strRDSPtyDocumentary:  qsTr("STR_RDS_PTY_DOCUMENTARY")
    property string strRDSPtyAlarmText:  qsTr("STR_RDS_PTY_ALARM_TEST")
    property string strRDSPtyAlarm:  qsTr("STR_RDS_PTY_ALARM")

    //************************ Strings ***//
    property string strRDSBandFm: qsTr("STR_RDS_BAND_FM")
    property string strRDSBandMw: qsTr("STR_RDS_BAND_AM")
    property string strRDSBandDab: qsTr("STR_RDS_BAND_DAB")
//    property string strRDSBandDab1: qsTr("STR_RDS_BAND_DAB1")
//    property string strRDSBandDab2: qsTr("STR_RDS_BAND_DAB2")
//    property string strRDSBandDab3: qsTr("STR_RDS_BAND_DAB3")

//    property string strRDSLabelHome: qsTr("STR_RDS_LABEL_HOME")
//    property string strRDSLabelRdsRadio: qsTr("STR_RDS_LABEL_RDS_RADIO")
    property string strRDSLabelSave: qsTr("STR_RDS_LABEL_SAVE")
//    property string strRDSLabelSeek: qsTr("STR_RDS_LABEL_SEEK")
    property string strRDSLabelPreset: qsTr("STR_RDS_LABEL_PRESET")
    property string strRDSLabelPresetSelectNumber: qsTr("STR_RDS_LABEL_PRESET_SELECT_NUMBER")
//    property string strRDSLabelEmpty: qsTr("STR_RDS_LABEL_EMPTY")
    property string strRDSLabelREG: qsTr("STR_RDS_LABEL_REG")
//    property string strRDSLabelAVOFF: qsTr("STR_RDS_LABEL_AV_OFF")

    property string strRDSMenuPresetList: qsTr("STR_RDS_MENU_PRESET_LIST")
    property string strRDSMenuSaveAsPreset: qsTr("STR_RDS_MENU_SAVE_AS_PRESET")
    property string strRDSMenuScan: qsTr("STR_RDS_MENU_SCAN_ALL_CHANNELS") //qsTr("STR_RDS_MENU_SCAN") KSW 130928
    property string strRDSMenuPresetScan: qsTr("STR_RDS_MENU_PRESET_SCAN")
//    property string strRDSMenuAutostore: qsTr("STR_RDS_MENU_AUTOSTORE")
//    property string strRDSMenuNews: qsTr("STR_RDS_MENU_NEWS")
    property string strRDSMenuRegion: qsTr("STR_RDS_MENU_REGION")
    property string strRDSMenuOff: qsTr("STR_RDS_MENU_OFF")
    property string strRDSMenuAuto: qsTr("STR_RDS_MENU_AUTO")
//    property string strRDSMenuTa: qsTr("STR_RDS_MENU_TA")
    property string strRDSMenuStationList: qsTr("STR_RDS_MENU_STATION_LIST")
    property string strRDSMenuRefresh: qsTr("STR_RDS_MENU_REFRESH")
    property string strRDSMenuSortBy: qsTr("STR_RDS_MENU_SORT_BY")
    property string strRDSMenuMenu: qsTr("STR_RDS_MENU_MENU")
    property string strRDSMenuInfo: qsTr("STR_RDS_MENU_INFO")
    property string strRDSMenuSoundSetting: qsTr("STR_RDS_MENU_SOUND_SETTING")
    property string strRDSMenuNowBroadcasting: qsTr("STR_RDS_MENU_NOW_BROADCASTING")
    property string strRDSMenuPty: qsTr("STR_RDS_MENU_PTY")
    property string strRDSMenuAlphabet: qsTr("STR_RDS_MENU_ALPHABET")
    property string strRDSMenuList: qsTr("STR_RDS_MENU_LIST")
    property string strRDSMenuStation: qsTr("STR_RDS_MENU_STATION")

    property string strRDSPopupOk: qsTr("STR_RDS_POPUP_OK")
    property string strRDSPopupCancel: qsTr("STR_RDS_POPUP_CANCEL")
//    property string strRDSPopupTpStationTitle: qsTr("STR_RDS_POPUP_TP_STATION_TITLE")
//    property string strRDSPopupTpStation: qsTr("STR_RDS_POPUP_TP_STATION")
    property string strRDSPopupTrafficAnnouncement: qsTr("STR_RDS_POPUP_TRAFFIC_ANNOUNCEMENT")
    property string strRDSPopupNewsAnnouncement: qsTr("STR_RDS_POPUP_NEWS_ANNOUNCEMENT")
    property string strRDSPopupAlarmAnnouncement: qsTr("STR_RDS_POPUP_ALARM_ANNOUNCEMENT")
//    property string strRDSPopupHide: qsTr("STR_RDS_POPUP_HIDE")
//    property string strRDSPopupListen: qsTr("STR_RDS_POPUP_LISTEN")
    property string strRDSPopupTaOff: qsTr("STR_RDS_POPUP_TA_OFF")
    property string strRDSPopupNewsOff: qsTr("STR_RDS_POPUP_NEWS_OFF")
    property string strRDSPopupAlarmOff: qsTr("STR_RDS_POPUP_ALARM_OFF")
    property string strRDSPopupBeingUpdated1: qsTr("STR_RDS_POPUP_BEING_UPDATED1")
    property string strRDSPopupBeingUpdated2: qsTr("STR_RDS_POPUP_BEING_UPDATED2")
//    property string strRDSPopupPresetAlreadySave: qsTr("STR_RDS_POPUP_PRESET_ALREADY_SAVE")
//    property string strRDSPopupClose: qsTr("STR_RDS_POPUP_CLOSE")
//    property string strRDSPopupPresetTitle1: qsTr("STR_RDS_POPUP_PRESET_TITLE1")
//    property string strRDSPopupPresetTitle2: qsTr("STR_RDS_POPUP_PRESET_TITLE2")

    property string strRDSMenuStopScan : qsTr("STR_RDS_MENU_STOP_SCAN") // JSH 131027
    property string strRDSTAOn : qsTr("STR_RDS_TA_ON")
    property string strRDSTAOff : qsTr("STR_RDS_TA_OFF")

    //************************ Translate Strings ***//
    function retranslateUi(languageId)
    {
        //console.log("RDS retranslateUi")

        //************************ List Strings ***//
        strRDSPtyAll = qsTr("")
        strRDSPtyNews = qsTr("STR_RDS_PTY_NEWS")
        strRDSPtyCurrentAffairs = qsTr("STR_RDS_PTY_CURRENT_AFFAIRS")
        strRDSPtyInfomation = qsTr("STR_RDS_PTY_INFORMATION")
        strRDSPtySport = qsTr("STR_RDS_PTY_SPORT")
        strRDSPtyEducation =qsTr("STR_RDS_PTY_EDUCATION")
        strRDSPtyDrama = qsTr("STR_RDS_PTY_DRAMA")
        strRDSPtyCulture = qsTr("STR_RDS_PTY_CULTURE")
        strRDSPtyScience = qsTr("STR_RDS_PTY_SCIENCE")
        strRDSPtyVaried = qsTr("STR_RDS_PTY_VARIED")
        strRDSPtyPopMusic = qsTr("STR_RDS_PTY_POP_MUSIC")
        strRDSPtyRockMusic = qsTr("STR_RDS_PTY_ROCK_MUSIC")
        strRDSPtyEasyListeningMusic = qsTr("STR_RDS_PTY_EASY_LISTENING_MUSIC")
        strRDSPtyLightClassicalMusic = qsTr("STR_RDS_PTY_LIGHT_CLASSICAL_MUSIC")
        strRDSPtySeriousClassicalMusic = qsTr("STR_RDS_PTY_SERIOUS_CLASSICAL_MUSIC")
        strRDSPtyOtherMusic = qsTr("STR_RDS_PTY_OTHER_MUSIC")
        strRDSPtyWeather = qsTr("STR_RDS_PTY_WEATHER")
        strRDSPtyFinance = qsTr("STR_RDS_PTY_FINANCE")
        strRDSPtyChildrensProgram = qsTr("STR_RDS_PTY_CHINDRENS_PROGRAME")
        strRDSPtySocialAffairs = qsTr("STR_RDS_PTY_SOCIAL_AFFAIRS")
        strRDSPtyReligion = qsTr("STR_RDS_PTY_RELIGION")
        strRDSPtyPhoneIn = qsTr("STR_RDS_PTY_PHONE_IN")
        strRDSPtyTravle = qsTr("STR_RDS_PTY_TRAVEL")
        strRDSPtyLeisure = qsTr("STR_RDS_PTY_LEISURE")
        strRDSPtyJazzMusic = qsTr("STR_RDS_PTY_JAZZ_MUSIC")
        strRDSPtyCountryMusic = qsTr("STR_RDS_PTY_COUNTRY_MUSIC")
        strRDSPtyNationalMusic = qsTr("STR_RDS_PTY_NATIONAL_MUSIC")
        strRDSPtyOldiesMusic = qsTr("STR_RDS_PTY_OLDIES_MUSIC")
        strRDSPtyFolkMusic = qsTr("STR_RDS_PTY_FOLK_MUSIC")
        strRDSPtyDocumentary = qsTr("STR_RDS_PTY_DOCUMENTARY")
        strRDSPtyAlarmText = qsTr("STR_RDS_PTY_ALARM_TEST")
        strRDSPtyAlarm = qsTr("STR_RDS_PTY_ALARM")

        //************************ Strings ***//
        strRDSBandFm = qsTr("STR_RDS_BAND_FM")
        strRDSBandMw = qsTr("STR_RDS_BAND_AM")
        strRDSBandDab = qsTr("STR_RDS_BAND_DAB")
//        strRDSBandDab1 = qsTr("STR_RDS_BAND_DAB1")
//        strRDSBandDab2 = qsTr("STR_RDS_BAND_DAB2")
//        strRDSBandDab3 = qsTr("STR_RDS_BAND_DAB3")

//        strRDSLabelHome = qsTr("STR_RDS_LABEL_HOME")
//        strRDSLabelRdsRadio = qsTr("STR_RDS_LABEL_RDS_RADIO")
        strRDSLabelSave = qsTr("STR_RDS_LABEL_SAVE")
//        strRDSLabelSeek = qsTr("STR_RDS_LABEL_SEEK")
        strRDSLabelPreset = qsTr("STR_RDS_LABEL_PRESET")
        strRDSLabelPresetSelectNumber = qsTr("STR_RDS_LABEL_PRESET_SELECT_NUMBER")
//        strRDSLabelEmpty = qsTr("STR_RDS_LABEL_EMPTY")
        strRDSLabelREG = qsTr("STR_RDS_LABEL_REG")
//        strRDSLabelAVOFF = qsTr("STR_RDS_LABEL_AV_OFF")

        strRDSMenuPresetList = qsTr("STR_RDS_MENU_PRESET_LIST")
        strRDSMenuSaveAsPreset = qsTr("STR_RDS_MENU_SAVE_AS_PRESET")
        strRDSMenuScan = qsTr("STR_RDS_MENU_SCAN_ALL_CHANNELS") //qsTr("STR_RDS_MENU_SCAN") KSW 130928
        strRDSMenuPresetScan = qsTr("STR_RDS_MENU_PRESET_SCAN")
//        strRDSMenuAutostore = qsTr("STR_RDS_MENU_AUTOSTORE")
//        strRDSMenuNews = qsTr("STR_RDS_MENU_NEWS")
        strRDSMenuRegion = qsTr("STR_RDS_MENU_REGION")
        strRDSMenuOff = qsTr("STR_RDS_MENU_OFF")
        strRDSMenuAuto = qsTr("STR_RDS_MENU_AUTO")
//        strRDSMenuTa = qsTr("STR_RDS_MENU_TA")
        strRDSMenuStationList = qsTr("STR_RDS_MENU_STATION_LIST")
        strRDSMenuRefresh = qsTr("STR_RDS_MENU_REFRESH")
        strRDSMenuSortBy = qsTr("STR_RDS_MENU_SORT_BY")
        strRDSMenuMenu = qsTr("STR_RDS_MENU_MENU")
        strRDSMenuInfo = qsTr("STR_RDS_MENU_INFO")
        strRDSMenuSoundSetting = qsTr("STR_RDS_MENU_SOUND_SETTING")
        strRDSMenuNowBroadcasting = qsTr("STR_RDS_MENU_NOW_BROADCASTING")
        strRDSMenuPty = qsTr("STR_RDS_MENU_PTY")
        strRDSMenuAlphabet = qsTr("STR_RDS_MENU_ALPHABET")
        strRDSMenuList = qsTr("STR_RDS_MENU_LIST")
        strRDSMenuStation = qsTr("STR_RDS_MENU_STATION")

        strRDSPopupOk = qsTr("STR_RDS_POPUP_OK")
        strRDSPopupCancel = qsTr("STR_RDS_POPUP_CANCEL")
//        strRDSPopupTpStationTitle = qsTr("STR_RDS_POPUP_TP_STATION_TITLE")
//        strRDSPopupTpStation = qsTr("STR_RDS_POPUP_TP_STATION")
        strRDSPopupTrafficAnnouncement = qsTr("STR_RDS_POPUP_TRAFFIC_ANNOUNCEMENT")
        strRDSPopupNewsAnnouncement = qsTr("STR_RDS_POPUP_NEWS_ANNOUNCEMENT")
        strRDSPopupAlarmAnnouncement = qsTr("STR_RDS_POPUP_ALARM_ANNOUNCEMENT")
//        strRDSPopupHide = qsTr("STR_RDS_POPUP_HIDE")
//        strRDSPopupListen = qsTr("STR_RDS_POPUP_LISTEN")
        strRDSPopupTaOff = qsTr("STR_RDS_POPUP_TA_OFF")
        strRDSPopupNewsOff = qsTr("STR_RDS_POPUP_NEWS_OFF")
        strRDSPopupAlarmOff = qsTr("STR_RDS_POPUP_ALARM_OFF")
        strRDSPopupBeingUpdated1 = qsTr("STR_RDS_POPUP_BEING_UPDATED1")
        strRDSPopupBeingUpdated2 = qsTr("STR_RDS_POPUP_BEING_UPDATED2")
//        strRDSPopupPresetAlreadySave = qsTr("STR_RDS_POPUP_PRESET_ALREADY_SAVE")
//        strRDSPopupClose = qsTr("STR_RDS_POPUP_CLOSE")
//        strRDSPopupPresetTitle1 = qsTr("STR_RDS_POPUP_PRESET_TITLE1")
//        strRDSPopupPresetTitle2 = qsTr("STR_RDS_POPUP_PRESET_TITLE2")
        strRDSMenuStopScan = qsTr("STR_RDS_MENU_STOP_SCAN") // JSH 131027
        strRDSTAOn = qsTr("STR_RDS_TA_ON")
        strRDSTAOff = qsTr("STR_RDS_TA_OFF")
    }
    //************************ Language Changed ***//
    Connections {
        target: UIListener
        onRetranslateUi: {
            //console.log("DHRDSMain: retranslateUi : " + languageId);
            stringInfo.retranslateUi(languageId);
//// 2013.11.01 added by qutiguy - ITS 0205006 : Update pty string each LanguageID
            QmlController.retranslatePtyName(languageId);
        }
    }
}
