.pragma library

/** Sound*/
var const_APP_SETTINGS_DEFAULT_SOUND_TONES = 0
var const_APP_SETTINGS_DEFAULT_SOUND_BEEP = 0
var const_APP_SETTINGS_DEFAULT_SOUND_DESIGN = 0
var const_APP_SETTINGS_DEFAULT_SOUND_SPEED = 0
var const_APP_SETTINGS_DEFAULT_SOUND_VEQ = 0
var const_APP_SETTINGS_DEFAULT_SOUND_VIRTUAL_LOW = 0
var const_APP_SETTINGS_DEFAULT_SOUND_VIRTUAL_MID = 0
var const_APP_SETTINGS_DEFAULT_SOUND_VIRTUAL_HIGH = 0
var const_APP_SETTINGS_DEFAULT_SOUND_VOLUMERATIO = 0
var const_APP_SETTINGS_DEFAULT_SOUND_BALANCE = 0
var const_APP_SETTINGS_DEFAULT_SOUND_FADER = 0
var const_APP_SETTINGS_DEFAULT_SOUND_SURROUND = 0

/** Screen */
var const_APP_SETTINGS_DEFAULT_VIDEO_BRIGHTNESS = 0
var const_APP_SETTINGS_DEFAULT_VIDEO_SATURATION = 0
var const_APP_SETTINGS_DEFAULT_VIDEO_HUE = 0
var const_APP_SETTINGS_DEFAULT_VIDEO_CONTRAST = 0
var const_APP_SETTINGS_DEFAULT_IMAGE_BRIGHTNESS = 10
var const_APP_SETTINGS_DEFAULT_EXPOSURE = "Auto"
var const_APP_SETTINGS_DEFAULT_ASPECT_RADIO = "Full"
