.pragma library

/**
 * DHAVN_AppSettings_General.js
 */

var DO_NOT_WRAPPING_AROUND = 100

var const_APP_SETTINGS_MAIN_SCREEN_WIDTH = 1280
var const_APP_SETTINGS_MAIN_SCREEN_HEIGHT = 720 - 93

var const_COLOR_TEXT_BRIGHT_GREY = "#FAFAFA"
var const_COLOR_TEXT_DISABLE_GREY = "#5B5B5B"
var const_COLOR_TEXT_DIMMED_GREY = "#9E9E9E"
var const_COLOR_TEXT_DIMMED_BLUE = "#447CAD"

var const_APP_SETTINGS_COLOR_TEXT_BLACK = "#000000"
var const_APP_SETTINGS_COLOR_TEXT_WHITE = "white"

var const_APP_SETTINGS_FONT_FAMILY_HDR = "HDR"
var const_APP_SETTINGS_FONT_FAMILY_HDB = "HDR"

var const_APP_SETTINGS_FONT_SIZE_TEXT_43PT = 43
var const_APP_SETTINGS_FONT_SIZE_TEXT_40PT = 40
var const_APP_SETTINGS_FONT_SIZE_TEXT_36PT = 36
var const_APP_SETTINGS_FONT_SIZE_TEXT_34PT = 34
var const_APP_SETTINGS_FONT_SIZE_TEXT_32PT = 32
var const_APP_SETTINGS_FONT_SIZE_TEXT_30PT = 30
var const_APP_SETTINGS_FONT_SIZE_TEXT_28PT = 28
var const_APP_SETTINGS_FONT_SIZE_TEXT_26PT = 26
var const_APP_SETTINGS_FONT_SIZE_TEXT_25PT = 25
var const_APP_SETTINGS_FONT_SIZE_TEXT_24PT = 24
var const_APP_SETTINGS_FONT_SIZE_TEXT_22PT = 22
var const_APP_SETTINGS_FONT_SIZE_TEXT_20PT = 20
var const_APP_SETTINGS_FONT_SIZE_TEXT_18PT = 18
var const_APP_SETTINGS_FONT_SIZE_TEXT_17PT = 17
var const_FONT_SIZE_TEXT_CELL = 22
var const_FONT_SIZE_TEXT_50PT = 50
var const_FONT_SIZE_TEXT_44PT = 44
var const_APP_SETTINGS_LANGCONTEXT = "main"
var const_APP_SETTINGS_STATUSBAR_LANGCONTEXT = "statusBar"

//settings general
var const_APP_SETTINGS_GENERAL_ITEM_ID_FHOTOFRAME = 0
var const_APP_SETTINGS_GENERAL_ITEM_ID_CLOCK = 1
var const_APP_SETTINGS_GENERAL_ITEM_ID_LANGUAGE = 2
var const_APP_SETTINGS_GENERAL_ITEM_ID_TEMPERATURE = 3
var const_APP_SETTINGS_GENERAL_ITEM_ID_APPROVAL = 4

//system settings
var const_APP_SETTINGS_SYSTEMSETTINGS_ITEM_ID_SYSTEMINFO = 0
var const_APP_SETTINGS_SYSTEMSETTINGS_ITEM_ID_UPDATE= 1
var const_APP_SETTINGS_SYSTEMSETTINGS_ITEM_ID_LOCKREARMONITOR = 2
var const_APP_SETTINGS_SYSTEMSETTINGS_ITEM_ID_JUKEBOXINFO = 3

//time picker
var const_TIME_PICKER_12_HOURS = 12
var const_TIME_PICKER_60_SECONDS = 60
var const_TIME_PICKER_TOP_SHIFT = 3
var const_TIME_PICKER_ZERO = "0"
var const_TIME_PICKER_PATH_VIEW_Y = -4
var const_TIME_PICKER_HOUR_PATH_COUNT = 6
var const_TIME_PICKER_AMPM_PATH_COUNT = 3
var const_TIME_PICKER_AMPM_PATH_VIEW_ANGLE_1 = 60
var const_TIME_PICKER_AMPM_PATH_VIEW_ANGLE_2 = 161

//photo frame

var const_APP_SETTINGS_PHOTO_FRAME_CONTENTAREA_HEIGHT = 555
var const_APP_SETTINGS_PHOTO_FRAME_CONTENTAREA_X = 0
var const_APP_SETTINGS_PHOTO_FRAME_CONTENTAREA_Y = 168
var const_APP_SETTINGS_PHOTO_FRAME_PHOTOFRAMEAREA_X = 489
var const_APP_SETTINGS_PHOTO_FRAME_RADIOLIST_LEFT_MARGIN = 13
//var const_APP_SETTINGS_PHOTO_FRAME_PHOTOIMAGE_LEFT_MARGIN = 20
//var const_APP_SETTINGS_PHOTO_FRAME_PHOTOIMAGE_TOP_MARGIN = 274
var const_APP_SETTINGS_PHOTO_FRAME_BROWSEIMAGEBUTTON_X = 518 + 258 - 489
var const_APP_SETTINGS_PHOTO_FRAME_BROWSEIMAGEBUTTON_WIDTH = 434
var const_APP_SETTINGS_PHOTO_FRAME_BROWSEIMAGEBUTTON_HEIGHT = 69
var const_APP_SETTINGS_TEXT_BROWSE_IMAGE= "Browse Image"
var const_APP_SETTINGS_PHOTO_FRAME_PATH_MAX_LENGHT = 1024

//BT VOLUME
var const_APP_SETTINGS_BT_SCREEN_WIDTH = 1280 - 520
var const_APP_SETTINGS_BT_SCREEN_HEIGHT = 720 - 168
var const_APP_SETTINGS_BT_BOTTOM_MARGIN = 502
var const_APP_SETTINGS_BT_TOP_MARGIN = 168
var const_APP_SETTINGS_BT_LEFT_MARGIN = 502
var const_APP_SETTINGS_BT_RIGHT_MARGIN = 25
var const_APP_SETTINGS_BT_SCROOLBAR_MARGIN = 14
var const_APP_SETTINGS_BT_VOLUME_MAX_VALUE = 45
var const_APP_SETTINGS_BT_VOLUME_MIN_VALUE = 0
var const_APP_SETTINGS_VR_VOLUME_MAX_VALUE = 45
var const_APP_SETTINGS_VR_VOLUME_MIN_VALUE = 0
var const_APP_SETTINGS_BT_TEXT_RING_MARGIN = 120
var const_APP_SETTINGS_BT_BUTTON_MARGIN = 40

//clock
var const_APP_SETTINGS_CLOCK_SCREEN_WIDTH = 1280 - 520
var const_APP_SETTINGS_CLOCK_SCREEN_HEIGHT = 720 - 168
var const_APP_SETTINGS_CLOCK_LEFT_MARGIN = 502   /**520**/
var const_APP_SETTINGS_CLOCK_TOP_MARGIN = 168
var const_APP_SETTINGS_CLOCK_RIGHT_MARGIN = 25
var const_APP_SETTINGS_CLOCK_BOTTOM_MARGIN = 11
var const_APP_SETTINGS_CLOCK_MENU_TEXT_LEFT_MARGIN = 18

var const_APP_SETTINGS_CLOCK_TIME_PICKER_YEAR_MARGIN = 0
var const_APP_SETTINGS_CLOCK_TIME_PICKER_MONTH_MARGIN = 2
var const_APP_SETTINGS_CLOCK_TIME_PICKER_DAY_MARGIN = 2
var const_APP_SETTINGS_CLOCK_TIME_PICKER_CLOCK_TYPE_MARGIN = 20
var const_APP_SETTINGS_CLOCK_TIME_PICKER_HOUR_MARGIN = 2
var const_APP_SETTINGS_CLOCK_TIME_PICKER_TIME_DIVIDER_MARGIN = 95
var const_APP_SETTINGS_CLOCK_TIME_PICKER_TIME_DIVIDER_TOP = 88
var const_APP_SETTINGS_CLOCK_TIME_PICKER_MINUTE_MARGIN = 2

var const_APP_SETTINGS_CLOCK_TIME_PICKER_TEXT_WIDTH = 322
var const_APP_SETTINGS_CLOCK_TIME_PICKER_TEXT_HEIGHT = 34
var const_APP_SETTINGS_CLOCK_TIME_PICKER_TEXT_TOP_MARGIN = 64

//windows interlocking
var const_APP_SETTINGS_WINDOWS_INTERLOCKING_SCREEN_WIDTH = const_APP_SETTINGS_CLOCK_SCREEN_WIDTH
var const_APP_SETTINGS_WINDOWS_INTERLOCKING_SCREEN_HEIGHT = const_APP_SETTINGS_CLOCK_SCREEN_HEIGHT
var const_APP_SETTINGS_WINDOWS_INTERLOCKING_RIGHT_MARGIN = const_APP_SETTINGS_CLOCK_RIGHT_MARGIN
var const_APP_SETTINGS_WINDOWS_INTERLOCKING_BOTTOM_MARGIN = const_APP_SETTINGS_CLOCK_BOTTOM_MARGIN
var const_APP_SETTINGS_WINDOWS_INTERLOCKING_LEFT_MARGIN = const_APP_SETTINGS_CLOCK_LEFT_MARGIN
var const_APP_SETTINGS_WINDOWS_INTERLOCKING_TOP_MARGIN = const_APP_SETTINGS_CLOCK_TOP_MARGIN
var const_APP_SETTINGS_WINDOWS_INTERLOCKING_MENU_TEXT_LEFT_MARGIN = const_APP_SETTINGS_CLOCK_MENU_TEXT_LEFT_MARGIN

var const_APP_SETTINGS_APPROACH_SENSOR_SCREEN_WIDTH = const_APP_SETTINGS_CLOCK_SCREEN_WIDTH
var const_APP_SETTINGS_APPROACH_SENSOR_SCREEN_HEIGHT = const_APP_SETTINGS_CLOCK_SCREEN_HEIGHT
var const_APP_SETTINGS_APPROACH_SENSOR_RIGHT_MARGIN = const_APP_SETTINGS_CLOCK_RIGHT_MARGIN
var const_APP_SETTINGS_APPROACH_SENSOR_BOTTOM_MARGIN = const_APP_SETTINGS_CLOCK_BOTTOM_MARGIN
var const_APP_SETTINGS_APPROACH_SENSOR_LEFT_MARGIN = const_APP_SETTINGS_CLOCK_LEFT_MARGIN
var const_APP_SETTINGS_APPROACH_SENSOR_TOP_MARGIN = const_APP_SETTINGS_CLOCK_TOP_MARGIN
var const_APP_SETTINGS_APPROACH_SENSOR_MENU_TEXT_LEFT_MARGIN = const_APP_SETTINGS_CLOCK_MENU_TEXT_LEFT_MARGIN

//language
var const_APP_SETTINGS_PHOTO_FRAME_LANGUAGEAREA_X = 489

//temperature
var const_APP_SETTINGS_PHOTO_FRAME_TEMPERATURE_X = 489

//keypad & Distance Unit
var const_APP_SETTINGS_STANDART_RADIO_CONTENTAREA_HEIGHT = 555
var const_APP_SETTINGS_STANDART_RADIO_CONTENTAREA_X = 0
var const_APP_SETTINGS_STANDART_RADIO_CONTENTAREA_Y = 168
var const_APP_SETTINGS_STANDART_RADIO_AREA_X = 489
var const_APP_SETTINGS_STANDART_RADIO_RADIOLIST_LEFT_MARGIN = 13
var const_APP_SETTINGS_STANDART_KEYPAD_FIRST_LINE_TEXT_OFFSET = 35
var const_APP_SETTINGS_STANDART_KEYPAD_SECOND_LINE_TEXT_OFFSET = 75

//approval
var const_APP_SETTINGS_APPROVAL_SCREEN_WIDTH = const_APP_SETTINGS_MAIN_SCREEN_WIDTH
var const_APP_SETTINGS_APPROVAL_SCREEN_HEIGHT = const_APP_SETTINGS_MAIN_SCREEN_HEIGHT
var const_APP_SETTINGS_APPROVAL_TOP_MARGIN = 263
var const_APP_SETTINGS_APPROVAL_LEFT_MARGIN = 551

var const_APP_SETTINGS_APPROVAL_TEXT_1_HEIGHT = 46
var const_APP_SETTINGS_APPROVAL_TEXT_2_HEIGHT = 54
var const_APP_SETTINGS_APPROVAL_TEXT_3_HEIGHT = 28
var const_APP_SETTINGS_APPROVAL_TEXT_4_HEIGHT = 36
var const_APP_SETTINGS_APPROVAL_TEXT_ITEM_WIDTH = 208+418
var const_APP_SETTINGS_APPROVAL_TEXT_ITEM_HEIGHT = 46+54+28+36
var const_APP_SETTINGS_APPROVAL_ACTIVITY_SLIDER_LEFT_MARGIN = 208

//system info
var const_APP_SETTINGS_SYSTEM_INFO_SCREEN_WIDTH = 552
var const_APP_SETTINGS_SYSTEM_INFO_SCREEN_HEIGHT = 720 - 168
var const_APP_SETTINGS_SYSTEM_INFO_TOP_MARGIN = 80 //215 - 38
var const_APP_SETTINGS_SYSTEM_INFO_LEFT_MARGIN = 713
var const_APP_SETTINGS_SYSTEM_INFO_VARIABLE_COLUMN_WIDTH = 221
var const_APP_SETTINGS_SYSTEM_INFO_ITEM_HEIGHT = 70
var const_APP_SETTINGS_SYSTEM_INFO_ITEM_DUBLE_HEIGHT = 200
var const_APP_SETTINGS_SYSTEM_INFO_ITEM_TITLE_WIDTH = 199
var const_APP_SETTINGS_SYSTEM_INFO_ITEM_TEXT_LEFT_MARGIN = 211
var const_APP_SETTINGS_SYSTEM_INFO_ITEM_TEXT_WIDTH = 330

var const_APP_SETTINGS_SYSTEM_INFO_VARIABLE_COLUMN_ITEM_HEIGHT = 70

//Update
var const_APP_SETTINGS_UPDATE_LEFT_MARGIN = const_APP_SETTINGS_CLOCK_LEFT_MARGIN
var const_APP_SETTINGS_UPDATE_TOP_MARGIN = const_APP_SETTINGS_CLOCK_TOP_MARGIN
var const_APP_SETTINGS_UPDATE_SCREEN_WIDTH = const_APP_SETTINGS_CLOCK_SCREEN_WIDTH
var const_APP_SETTINGS_UPDATE_SCREEN_HEIGHT = const_APP_SETTINGS_CLOCK_SCREEN_HEIGHT
var const_APP_SETTINGS_UPDATE_BOTTOM_MARGIN = const_APP_SETTINGS_CLOCK_BOTTOM_MARGIN

//system lock
var const_APP_SETTINGS_SYSTEM_LOCK_SCREEN_WIDTH = 648
var const_APP_SETTINGS_SYSTEM_LOCK_SCREEN_HEIGHT = 227+50+50+50+50+70
var const_APP_SETTINGS_SYSTEM_LOCK_TOP_MARGIN = 227
var const_APP_SETTINGS_SYSTEM_LOCK_LEFT_MARGIN = 543
var const_APP_SETTINGS_SYSTEM_LOCK_TEXT_ITEM_WIDTH = 97+83+288+180
var const_APP_SETTINGS_SYSTEM_LOCK_TEXT_HEIGHT = 50
var const_APP_SETTINGS_SYSTEM_LOCK_CHANGEBUTTON_TEXT_WIDTH = 288
var const_APP_SETTINGS_SYSTEM_LOCK_CHANGEBUTTON_TEXT_LEFT_MATGIN = 83
var const_APP_SETTINGS_SYSTEM_LOCK_CHANGEBUTTON_X = 543 + 97 - 489
var const_APP_SETTINGS_SYSTEM_LOCK_CHANGEBUTTON_HEIGHT = 69
var const_APP_SETTINGS_SYSTEM_LOCK_CHANGEBUTTON_WIDHT = 454

//JUKE BOX Info
var const_APP_SETTINGS_JUKE_BOX_INFO_TEXT1_X = 740
var const_APP_SETTINGS_JUKE_BOX_INFO_TEXT1_Y = 300
var const_APP_SETTINGS_JUKE_BOX_INFO_TEXT1_WIDTH = 446
var const_APP_SETTINGS_JUKE_BOX_INFO_TEXT2_Y = 400
var const_APP_SETTINGS_JUKE_BOX_INFO_TEXT2_WIDTH = 200
var const_APP_SETTINGS_JUKE_BOX_INFO_PROGRESSBAR_ITEM_HEIGHT = 26
var const_APP_SETTINGS_JUKE_BOX_INFO_PROGRESSBAR_ITEM_WIDTH = 459
var const_APP_SETTINGS_JUKE_BOX_INFO_PROGRESSBAR_ITEM_X = 734
var const_APP_SETTINGS_JUKE_BOX_INFO_PROGRESSBAR_ITEM_Y = 350
var const_APP_SETTINGS_JUKE_BOX_INFO_BUTTON_TOP_MARGIN = 135
var const_APP_SETTINGS_JUKE_BOX_INFO_BUTTON_LEFT_MARGIN = 40

//main screen
var const_APP_SETTINGS_MAIN_TOP_MARGIN = 112
var const_APP_SETTINGS_MAIN_LEFT_MARGIN = 80
var const_FONT_SIZE_TEXT_SETTINGS = 30

var const_APP_SETTINGS_MAIN_CELL_WIDTH = 247
var const_APP_SETTINGS_MAIN_CELL_HEIGHT = 180


var const_APP_SETTINGS_MAIN_LINE_1_X = 36
var const_APP_SETTINGS_MAIN_LINE_1_Y = 168
var const_APP_SETTINGS_MAIN_BG_LEFT_MARGIN = 36
var const_APP_SETTINGS_MAIN_BG_TOP_MARGIN = 168
var const_APP_SETTINGS_MAIN_TEXT_TOP_MARGIN = 145

var const_APP_SETTINGS_MAIN_APPLICATION_ID_SOUND = 0
var const_APP_SETTINGS_MAIN_APPLICATION_ID_SCREEN = 1
var const_APP_SETTINGS_MAIN_APPLICATION_ID_NAVIGATION = 2
var const_APP_SETTINGS_MAIN_APPLICATION_ID_BLIETOOTH = 3
var const_APP_SETTINGS_MAIN_APPLICATION_ID_VOICECONTROL = 4
var const_APP_SETTINGS_MAIN_APPLICATION_ID_GENERAL = 5
var const_APP_SETTINGS_MAIN_APPLICATION_ID_SYSTEM = 6
var const_APP_SETTINGS_MAIN_APPLICATION_ID_NETWORK = 7
var const_APP_SETTINGS_MAIN_APPLICATION_ID_DVD = 8

//settings general
var const_APP_SETTINGS_PHOTOFRAME_MENU_ITEM = 0
var const_APP_SETTINGS_CLOCK_MENU_ITEM = 1
var const_APP_SETTINGS_LANGUAGE_MENU_ITEM = 2
var const_APP_SETTINGS_TEMPERATURE_MENU_ITEM = 3
var const_APP_SETTINGS_APPROVAL_MENU_ITEM = 4

var const_APP_SETTINGS_FOCUS_TOP_MARGIN = -6
var const_APP_SETTINGS_TEXT_TOP_MARGIN = 23

// Settings Id
var const_APP_SETTINGS_CLOCK_TYPE_ANALOG_ID = 0
var const_APP_SETTINGS_CLOCK_TYPE_DIGITAL_ID = 1
var const_APP_SETTINGS_TIME_TYPE_12H_ID = 0
var const_APP_SETTINGS_TIME_TYPE_24H_ID = 1
var const_APP_SETTINGS_CALENDAR_TYPE_SOLAR_ID = 0
var const_APP_SETTINGS_CALENDAR_TYPE_LUNAR_ID = 1
var const_APP_SETTINGS_CALENDAR_TYPE_NOTSEE_ID = 2
var const_APP_SETTINGS_EXPOSE_ID = 0
var const_APP_SETTINGS_ASPECTRADIO_FULL_ID = 0
var const_APP_SETTINGS_ASPECTRADIO_16_9_ID = 1
var const_APP_SETTINGS_ASPECTRADIO_4_3_ID = 2

//sound settings
var const_APP_SETTINGS_SOUND_TOP_OFFSET = 354
var const_APP_SETTINGS_SOUND_LEFT_OFFSET = 516
var const_APP_SETTINGS_SOUND_WIDTH = 722

var const_APP_SETTINGS_SOUND_AVC_SCREEN_TEXT_TOP_OFFSET = 320
var const_APP_SETTINGS_SOUND_AVC_SCREEN_CONTENTAREA_WIDTH = 510

var const_APP_SETTINGS_SOUND_VIRUAL_LEFT_MARGIN = 30
var const_APP_SETTINGS_SOUND_VIRUAL_TOP_MARGIN = 20
var const_APP_SETTINGS_SOUND_VIRUAL_POWERBASS_SUBTEXT = 73
var const_APP_SETTINGS_SOUND_VIRUAL_SEPARATOR_LEFT = 13
var const_APP_SETTINGS_SOUND_VIRUAL_SEPARATOR_TOP = 110
var const_APP_SETTINGS_SOUND_VIRUAL_SLIDER_LEFT = 500
var const_APP_SETTINGS_SOUND_VIRUAL_POWERBASS_SLIDER_Y = 25
var const_APP_SETTINGS_SOUND_VIRUAL_POWERTREBLE_Y = 20 + 105
var const_APP_SETTINGS_SOUND_VIRUAL_POWERTREBLE_SUBTEXT = 73 + 95
var const_APP_SETTINGS_SOUND_VIRUAL_POWERTREBLE_SUBTEXT2 =  73 + 115
var const_APP_SETTINGS_SOUND_VIRUAL_SEPARATOR2_Y = 110 + 115
var const_APP_SETTINGS_SOUND_VIRUAL_POWERTREBLE_SLIDER_Y = 25 + 113
var const_APP_SETTINGS_SOUND_VIRUAL_SURROUND_Y = 20 + 105 + 120
var const_APP_SETTINGS_SOUND_VIRUAL_SURROUND_SUBTEXT = 73 + 115 + 110
var const_APP_SETTINGS_SOUND_VIRUAL_SURROUND_SLIDER =  25 + 113 + 115

var const_APP_SETTINGS_SOUND_CONTENTAREA_HEIGHT = 554
var const_APP_SETTINGS_SOUND_CONTENTAREA_X = 0
var const_APP_SETTINGS_SOUND_CONTENTAREA_Y = 168
var const_APP_SETTINGS_SOUND_SOUNDFRAMEAREA_X = 489

var const_APP_SETTINGS_SOUND_TONES_TOP_MARGIN = 85
var const_APP_SETTINGS_SOUND_TONES_TEXT_HEIGHT = 90
var const_APP_SETTINGS_SOUND_TONES_LEFT_MARGIN = 40
var const_APP_SETTINGS_SOUND_TONES_SLIDER_X = 390
var const_APP_SETTINGS_SOUND_TONES_RESET_BTN_X = 74 /* 150*/
var const_APP_SETTINGS_SOUND_TONES_RESET_BTN_Y = 455 /*350*/
var const_APP_SETTINGS_SOUND_TONES_MAX_VALUE = 10
var const_APP_SETTINGS_SOUND_TONES_MIN_VALUE = -10

var const_SETTINGS_SOUND_BALANCE_TOP_MARGIN = 166-93
var const_SETTINGS_SOUND_BALANCE_LEFT_MARGIN = 653

var const_SETTINGS_SOUND_BALANCE_SEAT_X = 190  /*156*/
var const_SETTINGS_SOUND_BALANCE_SEAT_Y = 124 /*102*/
var const_SETTINGS_SOUND_BALANCE_SEAT_WIDTH = 344/*344*/
var const_SETTINGS_SOUND_BALANCE_SEAT_HEIGHT = 344/*344*/

var const_SETTINGS_SOUND_BALANCE_BUTTON_L_X = 80
var const_SETTINGS_SOUND_BALANCE_BUTTON_R_X = 510
var const_SETTINGS_SOUND_BALANCE_BUTTON_L_Y = 217
var const_SETTINGS_SOUND_BALANCE_FADER_BUTTON_X = 266
var const_SETTINGS_SOUND_BALANCE_FADER_BUTTON_U_Y = 27
var const_SETTINGS_SOUND_BALANCE_FADER_BUTTON_D_Y = 460

var const_SETTINGS_SOUND_BALANCE_VL_Y = 102 /*96 , 268 -166 */
var const_SETTINGS_SOUND_BALANCE_VL_X = 357 /*323 , 855 + 171 - 669*/
var const_SETTINGS_SOUND_BALANCE_HL_X = 180 /* 855 - 669 */
var const_SETTINGS_SOUND_BALANCE_HL_Y = 273 /*268 + 171 - 166 */


var const_SETTINGS_SOUND_BALANCE_VL_SHIFT = 6/*6*/
var const_SETTINGS_SOUND_BALANCE_HL_SHIFT = 6/*6*/

var const_SETTINGS_SOUND_BALANCE_TEXT_X = 0 /*16*/
var const_SETTINGS_SOUND_BALANCE_TEXT_Y = 50 /*10*/
var const_SETTINGS_SOUND_BALANCE_VALUE_X = 120 /*150*/
var const_SETTINGS_SOUND_BALANCE_FADER_TEXT_Y = 94 /*70*/
var const_SETTINGS_SOUND_BALANCE_FADER_VALUE_X = 90 /*120*/

var const_SETTINGS_SOUND_BALANCE_CURSOR_X_MIN = 163 /*127*/
var const_SETTINGS_SOUND_BALANCE_CURSOR_X_MAX = 500 /*464*/
var const_SETTINGS_SOUND_BALANCE_CURSOR_Y_MIN = 79 /* 78*/
var const_SETTINGS_SOUND_BALANCE_CURSOR_Y_MAX = 412 /* 412*/

var const_SETTINGS_SOUND_BALANCE_CURSOR_X_CENTER = 366/*328*/
var const_SETTINGS_SOUND_BALANCE_CURSOR_Y_CENTER = 278

var const_SETTINGS_SOUND_BALANCE_CURSOR_X_SHIFT = 33
var const_SETTINGS_SOUND_BALANCE_CURSOR_Y_SHIFT = 33
var const_SETTINGS_SOUND_BALANCE_RESET_BTN_Y = 460
var const_SETTINGS_BALANCE_VALUE_MAX = 10
var const_SETTINGS_BALANCE_VALUE_MIN = -10
var const_SETTINGS_BALANCE_VALUE_FADER_MAX = 10
var const_SETTINGS_BALANCE_VALUE_FADER_MIN = -10
var const_SETTINGS_BALANCE_CURSOR_MULTIPLY_X = 290
var const_SETTINGS_BALANCE_CURSOR_MULTIPLY_Y = 335
var const_SETTINGS_BALANCE_CURSOR_FADER_SHIFT = 55
var const_SETTINGS_BALANCE_CURSOR_LINE_SHIFT = 25
var const_SETTINGS_BALANCE_CURSOR_LINE_X_SHIFT = 27
var const_SETTINGS_BALANCE_CURSOR_LINE_Y_SHIFT = 27
var const_SETTINGS_BEEP_TEXT1_TOP_OFFSET = 50
var const_SETTINGS_BEEP_TEXT2_TOP_OFFSET = 100
var const_SETTINGS_BEEP_SLIDER_TOP_OFFSET = 170
var const_SETTINGS_VARIABLEEQ_IMAGE_X = 160
var const_SETTINGS_VARIABLEEQ_IMAGE_Y = 350
var const_SETTINGS_VARIABLEEQ_IMAGE_HEIGHT = 150
var const_SETTINGS_VARIABLEEQ_IMAGE_WIDTH = 450
var const_SETTINGS_RESETBTN_WIDTH = 250
var const_SETTINGS_RESETBTN_TEXT_LEFT_MARGIN = 30
var const_SETTINGS_RESETBTN_TEXT_TOP_MARGIN = 10
var const_SETTINGS_SURROUND_SLIDER_TOP_OFFSET = 70


//
var const_APP_SETTINGS_MENU_TOP_MARGIN = 166 - 93
var const_APP_SETTINGS_MENU_WIDTH = 498
var const_APP_SETTINGS_MENU_HEIGHT = const_APP_SETTINGS_MAIN_SCREEN_HEIGHT - const_APP_SETTINGS_MENU_TOP_MARGIN
var const_APP_SETTINGS_MENU_BG_TOP_MERGIN = 5
var const_APP_SETTINGS_MENU_LIST_TOP_MARGIN = 6
var const_APP_SETTINGS_MENU_LIST_BOTTOM_MARGIN = 8
//var const_APP_SETTINGS_MENU_LIST_TOP_MARGIN = 9
//var const_APP_SETTINGS_MENU_LIST_TOP_MARGIN = 11

//var const_APP_SETTINGS_MENU_ITEM_TEXT_LEFT_MARGIN = 42
var const_APP_SETTINGS_MENU_ITEM_TEXT_LEFT_MARGIN = 14
//{modified by aettie.ji 2012.11.20 for ISV 59871
var const_APP_SETTINGS_MENU_ITEM_FONT_FAMILY_HDR = "HDR"
var const_APP_SETTINGS_MENU_ITEM_FONT_FAMILY_HDB = "HDR"
//}//{modified by aettie.ji 2012.11.20 for ISV 59871
var const_APP_SETTINGS_MENU_ITEM_TEXT_SIZE = 40
var const_APP_SETTINGS_MENU_ITEM_NORMAL_TEXT_COLOR = "#FAFAFA"
var const_APP_SETTINGS_MENU_ITEM_PRESSED_TEXT_COLOR = "#FAFAFA"
var const_APP_SETTINGS_MENU_ITEM_SELECTED_TEXT_COLOR = "#7CBDFF"
//var const_APP_SETTINGS_MENU_ITEM_SELECTED_TEXT_COLOR = "#80BFFF"
var const_APP_SETTINGS_MENU_ITEM_DISABLE_TEXT_COLOR = "#5B5B5B"
var const_APP_SETTINGS_MENU_ITEM_PRESSED_BG_TOP_MARGIN = 0
var const_APP_SETTINGS_MENU_ITEM_SELECTED_BG_TOP_MARGIN = -4
var const_APP_SETTINGS_MENU_ITEM_FOCUSED_BG_TOP_MARGIN = -9
var const_APP_SETTINGS_MENU_ITEM_LINE_LEFT_MARGIN = 27
var const_APP_SETTINGS_MENU_ANIMATION_WIDTH = 425
var const_APP_SETTINGS_MENU_ANIMATION_SPEED = 2000


//General
var const_APP_SETTINGS_MENU_ITEM_TEXT_BOTTOM_MARGIN = 43

//Main States
var const_APP_SETTINGS_MAIN_STATE_SOUND = "sound"
var const_APP_SETTINGS_MAIN_STATE_SCREEN = "screen"
var const_APP_SETTINGS_MAIN_STATE_SCREEN_DRS = "screen_drs" //added for DHPE DRS
var const_APP_SETTINGS_MAIN_STATE_VOICE = "voice"
var const_APP_SETTINGS_MAIN_STATE_GENERAL = "general"
var const_APP_SETTINGS_MAIN_STATE_CLOCK = "clock"
var const_APP_SETTINGS_MAIN_STATE_SYSTEM = "system"
var const_APP_SETTINGS_MAIN_STATE_KEYPAD = "keypad"

//Sound States
var const_APP_SETTINGS_SOUND_STATE_BALANACE = "balance"
var const_APP_SETTINGS_SOUND_STATE_TONES = "tones"
var const_APP_SETTINGS_SOUND_STATE_VOLUME_RATIO_CONTROL = "volume_ratio_control"
var const_APP_SETTINGS_SOUND_STATE_CLARIFI = "clari_fi" //added for DH PE
var const_APP_SETTINGS_SOUND_STATE_VIP = "vip_sound"
var const_APP_SETTINGS_SOUND_STATE_VARIABLE_EQ = "variable_eq"
var const_APP_SETTINGS_SOUND_STATE_SURROUND = "surround"
var const_APP_SETTINGS_SOUND_STATE_ACTIVE_SOUND_DESIGN = "active_sound_design"
var const_APP_SETTINGS_SOUND_STATE_BEEP = "beep"
var const_APP_SETTINGS_SOUND_STATE_QUANTUM_LOGIC = "quantum_logic" // 2014.02.24 DH_PE Quantum logic
var const_APP_SETTINGS_SOUND_NAVI_VOLUME = "volume_navi"
var const_APP_SETTINGS_SOUND_AUDIO_VOLUME = "volume_audio"
var const_APP_SETTINGS_SOUND_SAME_VOLUME = "volume_same"
//added for DH PE
var const_APP_SETTINGS_SOUND_SDV_LOW = "sdv_low"
var const_APP_SETTINGS_SOUND_SDV_MID = "sdv_mid"
var const_APP_SETTINGS_SOUND_SDV_HIGH = "sdv_high"
var const_APP_SETTINGS_SOUND_SDV_OFF = "sdv_off"

// 2014.02.24 DH_PE Quantum logic
var const_APP_SETTINGS_SOUND_QUANTUM_MODE_OFF = "quantum_off"
var const_APP_SETTINGS_SOUND_QUANTUM_MODE_AUDIENCE = "quantum_audience"
var const_APP_SETTINGS_SOUND_QUANTUM_MODE_STAGE = "quantum_stage"

var const_APP_SETTINGS_SOUND_STATE_VEQ_INNOCENTE = "veq_innocente"
var const_APP_SETTINGS_SOUND_STATE_VEQ_FORZA = "veq_forza"
var const_APP_SETTINGS_SOUND_STATE_VEQ_CONCERTO = "veq_concerto"

var const_APP_SETTINGS_SOUND_STATE_SPEED_DEPENDENT_VC = "speed_dependent_vc"
var const_APP_SETTINGS_SOUND_STATE_VIRTUAL_SOUND = "virtual_sound"
var const_APP_SETTINGS_SOUND_STATE_BT_VOLUME = "btvolume"
var const_APP_SETTINGS_SOUND_STATE_BLINK_VOLUME = "blvolume"
var const_APP_SETTINGS_SOUND_STATE_RESET_ALL = "resetAll"

//Voice States
var const_APP_SETTINGS_VOICE_STATE_VOICE_RECOGNITION = "voice_recognition"

var const_APP_SETTINGS_VOICE_STATE_INSTRUCTION = "instruction"
var const_APP_SETTINGS_VOICE_STATE_VOLUME_LEVEL = "vr_volume_level"


var const_APP_SETTINGS_VOICE_STATE_VOICE_CONTROL_DETAIL_GUIDE = "voice_detail_guide"
var const_APP_SETTINGS_VOICE_STATE_VOICE_CONTROL_SIMPLE_GUIDE = "voice_simple_guide"
var const_APP_SETTINGS_VOICE_STATE_VOICE_VOICE_CONTROL_NONE = "voice_none_guide"

var const_APP_SETTINGS_VR_TEXT_VOLUME_MARGIN = 70

//General States
var const_APP_SETTINGS_GENERAL_STATE_WAITING = "waiting"
var const_APP_SETTINGS_GENERAL_STATE_PHOTO_FRAME = "photo_frame"
var const_APP_SETTINGS_GENERAL_STATE_CLOCK = "clock"
var const_APP_SETTINGS_GENERAL_STATE_LANGUAGE = "language"
var const_APP_SETTINGS_GENERAL_STATE_APPROVAL = "approval"
var const_APP_SETTINGS_GENERAL_STATE_KEYPAD = "keypad"
var const_APP_SETTINGS_GENERAL_STATE_DISNANCE_UNIT = "distance_unit"
var const_APP_SETTINGS_GENERAL_STATE_DATE_FORMAT = "date_format"
var const_APP_SETTINGS_GENERAL_STATE_RESET_ALL = "general_reset_all"
var const_APP_SETTINGS_GENERAL_STATE_REAR_SEAT_CONTROL_MENU = "rear_seat_control_menu"
var const_APP_SETTINGS_GENERAL_STATE_LOCK_REAR_MONITOR = "lock_rear_monitor"
var const_APP_SETTINGS_GENERAL_STATE_PHONE_PRIORITY = "vr_phone_priority"
var const_APP_SETTINGS_GENERAL_STATE_PHONE_PRIORITY_BLUETOOTH = "phone_priority_bluetooth"
var const_APP_SETTINGS_GENERAL_STATE_PHONE_PRIORITY_BLUELINK = "phone_priority_bluelink"
var const_APP_SETTINGS_GENERAL_STATE_MEDIA_NOTIFICATION = "media_notification"

//added for DH PE
var const_APP_SETTINGS_GENERAL_STATE_PE_DIGITAL_CLOCK = "digital_clock"
var const_APP_SETTINGS_GENERAL_STATE_PE_ANALOG_CLOCK = "analog_clock"
var const_APP_SETTINGS_GENERAL_STATE_PE_NONE = "none"

// Screen States
var const_APP_SETTINGS_SCREEN_SET_DIMMING = "screen_dimming"
var const_APP_SETTINGS_SCREEN_SET_VIDEO_IMAGE = "video_image"
var const_APP_SETTINGS_SCREEN_SET_ASPECT_RATIO = "aspect_ratio"
var const_APP_SETTINGS_SCREEN_SET_VIDEO_MODE = "video_mode"
var const_APP_SETTINGS_SCREEN_SET_NON_VIDEO_MODE = "non_video_mode"
var const_APP_SETTINGS_SCREEN_PE_ILLUMINATION_DAYLIGHT = "illumination_daylight" //added for DH PE
var const_APP_SETTINGS_SCREEN_PE_ILLUMINATION_NIGHT = "illumination_night" //added for DH PE
var const_APP_SETTINGS_SCREEN_SET_DISPLAY_OFF = "display_on_off"
var const_APP_SETTINGS_SCREEN_STATE_RESET_ALL ="screen_reset_all"
var const_APP_SETTINGS_GENERAL_INIT = "general_initialization"

var const_APP_SETTINGS_SCREEN_SET_DIMMING_AUTOMATIC = "dimming_automatic"
var const_APP_SETTINGS_SCREEN_SET_DIMMING_DAYTIME = "dimming_daytime"
var const_APP_SETTINGS_SCREEN_SET_DIMMING_NIGHT = "dimming_night"

//System States
var const_APP_SETTINGS_SYSTEM_STATE_SYSTEM_INFO = "system_info"
var const_APP_SETTINGS_SYSTEM_STATE_UPDATE = "update"
var const_APP_SETTINGS_SYSTEM_STATE_RESET_ALL = "reset_all"
var const_APP_SETTINGS_SYSTEM_STATE_SYSTEM_JUKEBOX_INFO = "system_jukebox_info"
var const_APP_SETTINGS_SYSTEM_STATE_APPROACH_SENSOR = "system_approach_state"

//Reset All States
var const_APP_SETTINGS_INITIALIZATION = " initialization"
var const_APP_SETTINGS_INITIAL_STATE_RESET_ALL = "init_reset_all"
var const_APP_SETTINGS_INITIAL_STATE_SOUND_RESET_ALL = "sound_reset_all"
var const_APP_SETTINGS_INITIAL_STATE_SCREEN_RESET_ALL = "screen_reset_all"
var const_APP_SETTINGS_INITIAL_STATE_NAVI_RESET_ALL = "navi_reset_all"
var const_APP_SETTINGS_INITIAL_STATE_BT_RESET_ALL = "bt_reset_all"

//Input States (IBox or HU or Reset)
var const_APP_SETTINGS_INPUT_FROM_IBOX = "input_from_ibox"
var const_APP_SETTINGS_INPUT_FROM_HU = "input_from_hu"
var const_APP_SETTINGS_INPUT_FROM_RESET = "input_from_reset"

//Format Button
var const_APP_SETTINGS_SYSTEM_LOCK_CHANGEBUTTON_WIDTH = 450
var const_APP_SETTINGS_SYSTEM_LOCK_CHANGEBUTTON_HEIGHT = 70

var const_WD_SETTINGS_ORDER_POP_UP = 100

//Screen Brightness
var const_APP_SETTINGS_SCREEN_BRIGHTNESS_MAX_VALUE = 5
var const_APP_SETTINGS_SCREEN_BRIGHTNESS_MIN_VALUE = -5
var const_APP_SETTINGS_SCREEN_BRIGHTNESS_SLIDER_X = 275

// screensettings video image
var const_APP_SETTINGS_VIDEO_IMAGE_CONTENTAREA_HEIGHT = 555
var const_APP_SETTINGS_VIDEO_IMAGE_CONTENTAREA_X = 0
var const_APP_SETTINGS_VIDEO_IMAGE_CONTENTAREA_Y = 168
var const_APP_SETTINGS_VIDEO_IMAGE_FRAMEAREA_X = 489

var const_APP_SETTINGS_VIDEO_IMAGE_TOP_MARGIN = 85
var const_APP_SETTINGS_VIDEO_IMAGE_TEXT_HEIGHT = 90
var const_APP_SETTINGS_VIDEO_IMAGE_LEFT_MARGIN = 40
var const_APP_SETTINGS_VIDEO_IMAGE_SLIDER_X = 360
var const_APP_SETTINGS_VIDEO_IMAGE_RESET_BTN_Y = 350
var const_APP_SETTINGS_VIDEO_IMAGE_MAX_VALUE = 10
var const_APP_SETTINGS_VIDEO_IMAGE_MIN_VALUE = -10

// DHAVN_AppSettings_EngineeringModeSound
var const_APP_SETTINGS_MODE_SOUND_HEIGHT = 552
var const_APP_SETTINGS_MODE_SOUND_Y = 168
var const_APP_SETTINGS_MODE_SOUND_BOTTOM_MARGIN = 11
var const_APP_SETTINGS_MODE_SOUND_LINE_LEFT_MARGIN = 47
var const_APP_SETTINGS_MODE_SOUND_TEXT_LEFT_MARGIN = 52
var const_APP_SETTINGS_MODE_SOUND_TEXT_WIDTH = 611
var const_APP_SETTINGS_MODE_SOUND_VOLUE_RIGHT_MARGIN = 29

//Checking State of CLOCK_SETTINGS

var const_APP_SETTINGS_CLOCK_SETTINGS_ON = 1
var const_APP_SETTINGS_CLOCK_SETTINGS_OFF = 0

///////////////////////////////////////////////
var const_APP_SETTINGS_MENU_ITEM_CHECKBOX_RIGHT_MARGIN = 12

var const_APP_SETTINGS_B_STANDART_RADIO_CONTENTAREA_X = 708
var const_APP_SETTINGS_B_STANDART_RADIO_CONTENTAREA_Y = 166 - 93 + 18 //93 status bar 15 topMargin for focus
var const_APP_SETTINGS_B_STANDART_RADIO_CONTENTAREA_WIDTH = 560
var const_APP_SETTINGS_B_STANDART_RADIO_CONTENTAREA_HEIGHT = 552

var const_APP_SETTINGS_B_STANDART_RESET_CONTENTAREA_X = 720
var const_APP_SETTINGS_B_STANDART_RESET_CONTENTAREA_Y = 166
var const_APP_SETTINGS_B_STANDART_RESET_CONTENTAREA_WIDTH = 560
var const_APP_SETTINGS_B_STANDART_RESET_CONTENTAREA_HEIGHT = 552
var const_APP_SETTINGS_B_STANDART_RESET_TEXT_Y = 228
var const_APP_SETTINGS_B_STANDART_RESET_BUTTON_X = 774
var const_APP_SETTINGS_B_STANDART_RESET_BUTTON_Y = 471
var const_APP_SETTINGS_B_STANDART_RESET_BUTTON_LEFT_MARGIN = 60

var const_APP_SETTINGS_B_MENU_ITEM_LINE_LEFT_MARGIN = 43
var const_APP_SETTINGS_B_MENU_ITEM_SELECTED_BG_TOP_MARGIN = 0
var const_APP_SETTINGS_B_MENU_ITEM_FOCUSED_BG_TOP_MARGIN = 0
//var const_APP_SETTINGS_B_MENU_WIDTH = 537
var const_APP_SETTINGS_B_MENU_WIDTH = 550

var const_APP_SETTINGS_B_STANDART_SIMPLE_SCREEN_CONTENTAREA_X = 710
var const_APP_SETTINGS_B_STANDART_SIMPLE_SCREEN_CONTENTAREA_Y = 166-93
var const_APP_SETTINGS_B_STANDART_SIMPLE_SCREEN_CONTENTAREA_WIDTH = 490
var const_APP_SETTINGS_B_STANDART_SIMPLE_SCREEN_CONTENTAREA_HEIGHT = 540
//Connectivity //added for AA/CP Setting
var const_SETTINGS_CONNECTIVITY_ANDROID = 0
var const_SETTINGS_CONNECTIVITY_IOS = 1
//connectivity States //added for AA/CP Setting
var const_APP_SETTINGS_CONNECTIVITY_STATE_IOS = "iOS"
var const_APP_SETTINGS_CONNECTIVITY_STATE_ANDRIOID = "android"
var const_APP_SETTINGS_CONNECTIVITY_IOS_CARPLAY = "carplay"
var const_APP_SETTINGS_CONNECTIVITY_IOS_TBD = "tbd"
var const_APP_SETTINGS_CONNECTIVITY_ANDROID_ONOFF = "adroidOnOff"

//Han
var const_APP_SETTINGS_MODSCROLLBAR_TEXT_WIDTH = 380

var const_APP_SETTINGS_B_STANDART_SIMPLE_MENU_SCREEN_CONTENTAREA_X = 710
var const_APP_SETTINGS_B_STANDART_SIMPLE_MENU_SCREEN_CONTENTAREA_Y = 166 - 93 + 10
var const_APP_SETTINGS_B_STANDART_SIMPLE_MENU_SCREEN_CONTENTAREA_WIDTH = 530
var const_APP_SETTINGS_B_STANDART_KEYPAD_MENU_SCREEN_CONTENTAREA_WIDTH = 540
var const_APP_SETTINGS_B_STANDART_SIMPLE_MENU_SCREEN_CONTENTAREA_HEIGHT = 540
var const_APP_SETTINGS_B_STANDART_SIMPLE_MENU_SCREEN_LEFT_TEXT_MARGIN = 8



var const_APP_SETTINGS_BROWSEIMAGEBUTTON_WIDTH = 242
var const_APP_SETTINGS_BROWSEIMAGEBUTTON_HEIGHT = 73
var const_APP_SETTINGS_BROWSEIMAGEBUTTON_TEXT_WIDTH = 216
var const_APP_SETTINGS_BROWSEIMAGEBUTTON_TEXT_TOP_MARGIN = 34
var const_APP_SETTINGS_BROWSEIMAGEBUTTON_TEXT_LEFT_MARGIN = 13

// Photo Frame

var const_APP_SETTINGS_PHOTO_FRAME_AREA_X = 708
var const_APP_SETTINGS_PHOTO_FRAME_PHOTOSOURSE_MARGIN = 28
var const_APP_SETTINGS_PHOTO_FRAME_PHOTOIMAGE_LEFT_MARGIN = 132
var const_APP_SETTINGS_PHOTO_FRAME_PHOTOIMAGE_TOP_MARGIN = 279
var const_APP_SETTINGS_PHOTO_FRAME_BUTTON_LEFT_MARGIN = -6

//clock
var const_APP_SETTINGS_B_CLOCK_SPIN_LEFT_MARGIN = 250
var const_APP_SETTINGS_B_CLOCK_SPIN_TYPE_WIDTH = 276
var const_APP_SETTINGS_LOCKED_FOCUS = -25

//Tones
var const_APP_SETTINGS_B_SOUND_TONES_FRAMEAREA_X = 708
var const_APP_SETTINGS_B_SOUND_TONES_FRAMEAREA_TOP_MARGIN = 166-93
var const_APP_SETTINGS_B_SOUND_TONES_LEFT_MARGIN = 0
var const_APP_SETTINGS_B_SOUND_TONES_SLIDER_TOP_MARGIN = 40
var const_APP_SETTINGS_B_SOUND_TONES_SLIDER_LEFT_MARGIN = 250
var const_APP_SETTINGS_B_SOUND_TONES_SLIDER_X = 242
var const_APP_SETTINGS_B_TONES_SCREEN_CONTENTAREA_X = 710
var const_APP_SETTINGS_B_TONES_SCREEN_CONTENTAREA_Y = 166
var const_APP_SETTINGS_B_SOUND_CONTENTAREA_Y_WITHOUT_SB = 73

//Reset All
var const_APP_SETTINGS_SOUND__RESET_ALL_BTN_TOP_MARGIN_FROM_TEXT = 70
var const_APP_SETTINGS_SOUND__RESET_ALL_TEXT_TOP_MARGIN = 250

//ScreenSettings

var const_APP_SETTINGS_SCREEN_FRONT_WIDTH = 476
var const_APP_SETTINGS_SCREEN_FRONT_HEIGHT= 72
var const_APP_SETTINGS_SCREEN_REAR_WIDTH=235
var const_APP_SETTINGS_SCREEN_REAR_HEIGHT=72
var const_APP_SETTINGS_SCREEN_ASPECT_RATIO_FRAME_WIDTH=365
var const_APP_SETTINGS_SCREEN_ASPECT_RATIO_FRAME_HEIGHT=210
var const_APP_SETTINGS_SCREEN_ASPECT_RATIO_FRAME_LEFT_MARGIN=60
var const_APP_SETTINGS_SCREEN_VIDEO_IMAGE_RECT_WIDTH=800
var const_APP_SETTINGS_SCREEN_VIDEO_IMAGE_RECT_HEIGHT=550


/*
a b c
d   e
f    g
h i  j
*/
//wave balance
var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_UP_A_X =  109 //778 - 669
var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_UP_A_Y = 0

var const_SETTINGS_SOUND_BALANCE_WAVE_CENTER_UP_B_X =  173 //778 - 669 + 64
var const_SETTINGS_SOUND_BALANCE_WAVE_CENTER_UP_B_Y = 0

var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_UP_C_X = 461 // 64 +64 + 64 + 288 - 65
var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_UP_C_Y = 0

var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_CENTER_D_X =  109 //778 - 669
var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_CENTER_D_Y =  106 //272 - 166

var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_CENTER_E_X =  510 // 778+401 - 669
var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_CENTER_E_Y = 106 //272  - 166


var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_CENTER_F_X = 109 //778 - 669
var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_CENTER_F_Y = 255 //272 + 149 - 166

var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_CENTER_G_X =   510 // 778+401 - 669
var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_CENTER_G_Y = 255 //272 + 149 - 166


var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_DOWN_H_X = 109 //778 - 669
var const_SETTINGS_SOUND_BALANCE_WAVE_LEFT_DOWN_H_Y = 380 //520 + 26 - 166

var const_SETTINGS_SOUND_BALANCE_WAVE_CENTER_DOWN_I_X =   173 //778 - 669 + 64
var const_SETTINGS_SOUND_BALANCE_WAVE_CENTER_DOWN_I_Y = 354 //520 - 166

var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_DOWN_J_X = 461 // 64 +64 + 64 + 288 - 65
var const_SETTINGS_SOUND_BALANCE_WAVE_RIGHT_DOWN_J_Y = 380 // 520 + 26 - 166

//Settings>DVD
var const_DVD_SETTINGS_COUNT_FONT_SIZE = 3
var const_DVD_SETTINGS_MARGIN_STATBAR = 82 //Need 93
var const_DVD_SETTINGS_MARGIN_MODEAREA = 83 //Need 73

//Caption Screen
var const_FS_CAPTION_FOCUS_NONE = 0
var const_FS_CAPTION_MARGIN_STATBAR = 82 //Need 93
var const_MODE_AREA_INDEX = 2

//Sound
var const_SETTINGS_SOUND_VOLUME_RATIO = 0
var const_SETTINGS_SOUND_BALANCE = 1
var const_SETTINGS_SOUND_TONES = 2
var const_SETTINGS_SOUND_SURROUND = 3
var const_SETTINGS_SOUND_CLARIFI = 4 //added for DH PE
var const_SETTINGS_SOUND_VIP_SOUND = 5
var const_SETTINGS_SOUND_SDVC = 6
var const_SETTINGS_SOUND_BEEP = 7
var const_SETTINGS_SOUND_RESET_ALL = 8
var const_SETTINGS_SOUND_QUANTUMLOGIC = 9 // 2014.02.24 DH_PE Quantum logic

//Clock
var const_SETTINGS_CLOCK_GPS_TIME = 0
var const_SETTINGS_CLOCK_TIME_SETTING = 1
var const_SETTINGS_CLOCK_DAYLIGHT_SAVING = 2
var const_SETTINGS_CLOCK_TIME_ZONE = 3
var const_SETTINGS_CLOCK_CLOCK_TYPE = 4
var const_SETTINGS_CLOCK_TIME_FORMAT = 5

//General
var const_SETTINGS_GENERAL_LANGUAGE = 0
var const_SETTINGS_GENERAL_KEYPAD = 1
var const_SETTINGS_GENERAL_MEDIA_NOTIFICATION = 2
var const_SETTINGS_GENERAL_DISTANCE_UNIT = 3
var const_SETTINGS_GENERAL_PHONE_PRIORITY = 4
var const_SETTINGS_GENERAL_PHOTO_FRAME = 5
var const_SETTINGS_GENERAL_APPROVAL = 6
var const_SETTINGS_GENERAL_REAR_SEAT_CONTROL_MENU = 7
var const_SETTINGS_GENERAL_LOCK_REAR_MONITOR = 8

//System Info
var const_SETTINGS_GENERAL_MODEL = 0
var const_SETTINGS_GENERAL_SW_VERSION = 1
var const_SETTINGS_GENERAL_IBOX_VERSION = 2
var const_SETTINGS_GENERAL_MAP_VERSION = 3
var const_SETTINGS_GENERAL_NAVI_APPLICATION = 4
var const_SETTINGS_GENERAL_ASSOCIATION = 5
var const_SETTINGS_GENERAL_GRACENOTE_SDK_VERSION = 6
var const_SETTINGS_GENERAL_GRACENOTE_DB_VERSION = 7
var const_SETTINGS_GENERAL_BT_MAC_ADDRESS = 8

// Radio-List's Default value (Radio-List's Index)
//Sound
var const_SETTINGS_SOUND_RATIO_DEFAULT_VALUE = 0
var const_SETTINGS_SOUND_VARIABLE_EQ_DEFAULT_VALUE = 0
var const_SETTINGS_SOUND_SDV_DEFAULT_VALUE = 0 //added for DH PE

//Display
var const_SETTINGS_SCREEN_ASPECTRATIO_DEFAULT_VALUE = 0
var const_SETTINGS_SCREEN_DIMMING_DEFAULT_VALUE = 0

//Voice Recognition
var const_SETTINGS_VOICE_RECOGNITION_DEFAULT_VALUE = 0

//Clock
var const_SETTINGS_CLOCK_TYPE_DEFAULT_VALUE = 0
var const_SETTINGS_CLOCK_TIME_FORMAT_DEFAULT_VALUE = 0
var const_SETTINGS_CLOCK_TIMEZONE_DEFAULT_VALUE = 0

//General
var const_SETTINGS_GENERAL_DISTANCE_UNIT_DEFAULT_VALUE = 0
var const_SETTINGS_GENERAL_PHONE_PRIORITY_DEFAULT_VALUE = 0
var const_SETTINGS_GENERAL_PHOTO_FRAME_DEFAULT_VALUE = 0

var const_SETTINGS_GENERAL_LANGUAGE_DEFAULT_VALUE = 0   // (Default Index: 0)
var const_SETTINGS_GENERAL_LANGUAGE_EUROPE_DEFAULT_VALUE = 2  //(UK English)
var const_SETTINGS_GENERAL_LANGUAGE_RUSSIA_DEFAULT_VALUE = 7

//Keypad Popup
var const_SETTINGS_GENERAL_KEYBOARD_POPUP_DEFAULT_VALUE = 0


// Country Region Code
var const_SETTINGS_REGION_KOREA         =  0
var const_SETTINGS_REGION_NORTH_AMERICA =  1
var const_SETTINGS_REGION_CHINA         =  2
var const_SETTINGS_REGION_GENERAL       =  3
var const_SETTINGS_REGION_MIDDLE_EAST   =  4
var const_SETTINGS_REGION_EUROPA        =  5
var const_SETTINGS_REGION_CANADA        =  6
var const_SETTINGS_REGION_RUSSIA        =  7

var const_SETTINGS_CLOCK_TIME_12HR = 0
var const_SETTINGS_CLOCK_TIME_24HR = 1

var const_SETTINGS_FRONT_SCREEN = 1
var const_SETTINGS_REAR_SCREEN =2
