/**
 * DHAVN_AppPandoraConst.js
 */

.pragma library
/**********************************************************/
// Common
/**********************************************************/
var const_PANDORA_ALL_SCREEN_WIDTH = 1280
var const_PANDORA_MAIN_SCREEN_HEIGHT = 720

var const_PANDORA_COMMON_STATUS_BAR_HEIGHT = 93
var const_PANDORA_ALL_SCREEN_BOTTOM_MARGIN = 0

// Mode area
var const_PANDORA_MODE_ITEM_HEIGHT = 72//83 //modified by jyjeon 2014-05-16 GUI update (DH Genesis_Guideline_General_v2.2.3)
var const_PANDORA_MODE_ITEM_RIGHT_MARGIN = 23
var const_PANDORA_MODE_ITEM_LEFT_MARGIN = 23
var const_PANDORA_MODE_ITEM_TOP_MARGIN = 72//83 //modified by jyjeon 2014-05-16 GUI update (DH Genesis_Guideline_General_v2.2.3)

// Mode area back button
var const_PANDORA_MODE_ITEM_BACK_BUTTON_REL_TOP_MARGINv= 100-const_PANDORA_COMMON_STATUS_BAR_HEIGHT
var const_PANDORA_MODE_ITEM_BACK_BUTTON_REL_RIGHT_MARGIN = 0

// Mode area pandora logo title
var const_PANDORA_MODE_ITEM_PANDORA_LOGO_REL_TOP_MARGIN = 118-const_PANDORA_COMMON_STATUS_BAR_HEIGHT

// All screens offset
var const_PANDORA_ALL_SCREENS_TOP_OFFSET = const_PANDORA_COMMON_STATUS_BAR_HEIGHT

// Color constants
var const_PANDORA_COLOR_TEXT_DIMMED_GREY = "#9E9E9E"
var const_PANDORA_COLOR_TEXT_BRIGHT_GREY = "#FAFAFA"
var const_PANDORA_COLOR_TEXT_PROGRESS_BLUE = "#0087EF"
var const_PANDORA_COLOR_TEXT_BUTTON_GREY = "#2F2F2F"
var const_PANDORA_COLOR_TEXT_GREY = "#C1C1C1"
var const_PANDORA_COLOR_SUB_TEXT_GREY = "#D4D4D4"
var const_PANDORA_COLOR_DISABLE_GREY = "#5B5B5B"
var const_PANDORA_COLOR_BLACK = "black"
var const_PANDORA_COLOR_WHITE = "white"
var const_PANDORA_COLOR_TEXT_CURR_STATION = "#7CBDFF"

var const_PANDORA_LIGHT_DIMMED = "#92949D"
var const_PANDORA_COLOR_LOG_TEXT_GREY = "#9BA4B0"//(155,164,176)//added by esjang 2013.06.29 for DH Genesis GUI desing v2.0.0(2013.06.28)


// Text constants
var const_PANDORA_FONT_FAMILY_HDR = "NewHDR"//"HDR"
var const_PANDORA_FONT_FAMILY_HDB = "NewHDB"//"HDB"

var const_PANDORA_FONT_SIZE_TEXT_BUTTON_FONT = 34
var const_PANDORA_FONT_SIZE_TEXT_45_FONT = 45
var const_PANDORA_FONT_SIZE_TEXT_HDB_24_FONT = 24
var const_PANDORA_FONT_SIZE_TEXT_HDR_22_FONT = 22
var const_PANDORA_FONT_SIZE_TEXT_HDR_24_FONT = 24
var const_PANDORA_FONT_SIZE_TEXT_HDR_32_FONT = 32
var const_PANDORA_FONT_SIZE_TEXT_HDR_36_FONT = 36
var const_PANDORA_FONT_SIZE_TEXT_HDR_40_FONT = 40 // added by esjang 2013.03.06 for DH Genesis GUI Design Guideline v1.1.2(2013.02.28)
var const_PANDORA_FONT_SIZE_TEXT_HDR_29_FONT = 29
var const_PANDORA_FONT_SIZE_TEXT_HDB_32_FONT = 32
var const_PANDORA_FONT_SIZE_TEXT_TIME_FONT = 34
var const_PANDORA_FONT_SIZE_TEXT_SUB_FONT = 28
var const_PANDORA_FONT_SIZE_TEXT_INDEX_FONT = 22
var const_PANDORA_FONT_SIZE_TEXT_AUX = 250
var const_PANDORA_FONT_PIXEL_SIZE_TEXT_BUTTON_FONT_LEFT = 29
var const_PANDORA_FONT_PIXEL_SIZE_TEXT_BUTTON_FONT = 25
var const_PANDORA_FONT_SIZE_TEXT_HDR_26_FONT = 26
var const_PANDORA_FONT_SIZE_TEXT_HDR_45_FONT = 45
var const_PANDORA_FONT_SIZE_TEXT_HDB_40_FONT = 40

//Timer Constant
var const_PANDORA_TIMER_COUNTER_MAX_VAL = 16
var const_PANDORA_TIMER_COUNTER_MIN_VAL = 0

/**********************************************************/
// Pandora Why This Song Screen specific
/**********************************************************/
var const_PANDORA_WHY_THIS_SONG_TEXT1_X_OFFSET = 101
var const_PANDORA_WHY_THIS_SONG_TEXT1_Y_OFFSET = 208 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_WHY_THIS_SONG_Y_OFFSET_FROM_PREV_TEXT = 60
var const_PANDORA_WHY_THIS_SONG_TEXT_WIDTH = 1100
var const_PANDORA_RIGHT_MARGIN = 53
var const_PANDORA_SCROLL_STEP_SIZE = 30


/**********************************************************/
// Pandora Connecting Screen specific
/**********************************************************/
var const_PANDORA_CONNECTING_SCREEN_HEIGHT = 720 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_CONNECTING_WAIT_IMAGE_X_OFFSET = 140 + 462
var const_PANDORA_CONNECTING_WAIT_IMAGE_Y_OFFSET = 281 + 60 + 103 - const_PANDORA_ALL_SCREENS_TOP_OFFSET


var const_PANDORA_CONNECTING_TEXT_COLOR = const_PANDORA_COLOR_TEXT_BRIGHT_GREY
var const_PANDORA_CONNECTING_TEXT_FONT_FAMILY = const_PANDORA_FONT_FAMILY_HDR
//var const_PANDORA_CONNECTING_TEXT_FONT_SIZE = const_PANDORA_FONT_SIZE_TEXT_HDR_36_FONT
var const_PANDORA_CONNECTING_TEXT_FONT_SIZE = const_PANDORA_FONT_SIZE_TEXT_HDR_40_FONT// modified by esjang 2013.03.06 for DH Genesis GUI Design Guideline v1.1.2(2013.02.28)

var const_PANDORA_CONNECTING_TEXT_WIDTH = 462 + 538
var const_PANDORA_CONNECTING_TEXT_HEIGHT = 60
var const_PANDORA_CONNECTING_WAIT_TEXT1_X_OFFSET = 140
var const_PANDORA_CONNECTING_WAIT_TEXT1_Y_OFFSET = 281 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_CONNECTING_WAIT_TEXT_LOADING_Y_OFFSET = 235 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_CONNECTING_WAIT_TEXT_LOADING_X_OFFSET = 140
var const_PANDORA_CONNECTING_WAIT_TEXT2_X_OFFSET = 140
var const_PANDORA_CONNECTING_WAIT_TEXT2_Y_OFFSET = 281 + 60 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_CONNECTING_VIEW_TIMER_COUNTER_MAX_VAL = 16
var const_PANDORA_CONNECTING_VIEW_TIMER_COUNTER_MIN_VAL = 0
var const_PANDORA_CONNECTION_ESTABLISHED = 1
var const_PANDORA_CONNECTION_FAILED = 0
var const_PANDORA_CONNECTING_VIEW_TEXT2_Y_OFFSET_FROM_TEXT1 = 60


/**************************************************************************/
/******   pandora wait view specific***************************************/
/**************************************************************************/
//{ modifid by cheolhwan 2013.11.27. for Guideline Pandora v2.0.4
//var const_PANDORA_LOADING_WAIT_IMAGE_X_OFFSET = 140 + 462
//var const_PANDORA_LOADING_WAIT_IMAGE_Y_OFFSET = 235 + 55 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_LOADING_WAIT_IMAGE_X_OFFSET = 140 + 450
var const_PANDORA_LOADING_WAIT_IMAGE_Y_OFFSET = 243 + 66 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//} modifid by cheolhwan 2013.11.27. for Guideline Pandora v2.0.4
var const_PANDORA_LOADING_TEXT_COLOR = const_PANDORA_COLOR_TEXT_BRIGHT_GREY
//{ modified by esjang 2013.03.06 for DH Genesis GUI Design Guideline v1.1.2(2013.02.28)
//var const_PANDORA_LOADING_TEXT_FONT_FAMILY = const_PANDORA_FONT_FAMILY_HDB
var const_PANDORA_LOADING_TEXT_FONT_FAMILY = const_PANDORA_FONT_FAMILY_HDR
//var const_PANDORA_LOADING_TEXT_FONT_SIZE = const_PANDORA_FONT_SIZE_TEXT_HDB_32_FONT
var const_PANDORA_LOADING_TEXT_FONT_SIZE = const_PANDORA_FONT_SIZE_TEXT_HDR_40_FONT 
//} modified by esjang 2013.03.06 for DH Genesis GUI Design Guideline v1.1.2(2013.02.28)
var const_PANDORA_LOADING_WAIT_TEXT_LOADING_X_OFFSET = 140
//{ modifid by cheolhwan 2013.11.27. for Guideline Pandora v2.0.4
//var const_PANDORA_LOADING_WAIT_TEXT_LOADING_Y_OFFSET = 235 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_LOADING_WAIT_TEXT_LOADING_Y_OFFSET = 243 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//} modifid by cheolhwan 2013.11.27. for Guideline Pandora v2.0.4
var const_PANDORA_LOADING_TEXT_WIDTH = 462 + 538


// PlayerView
var const_PANDORA_FONT_SIZE_TEXT_HDR_50_FONT = 50
var const_PANDORA_FONT_SIZE_TEXT_HDR_28_FONT = 28
var const_PANDORA_PLAYER_VIEW_BG_NUMBER = 3
var const_PANDORA_PLAYER_VIEW_ITEM_TOP_MARGIN = 20
var const_PANDORA_PROGRESS_BAR_ITEM_WIDTH = 726
var const_PANDORA_PROGRESS_BAR_ITEM_LEFT_MARGIN = 81
var const_PANDORA_PROGRESS_BAR_ITEM_BOTTOM_MARGIN = 80

/**********************************************************/
// Pandora Track View Screen specific
/**********************************************************/
var const_PANDORA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_X_OFFSET = 158 //161 new ux change
var const_PANDORA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_Y_OFFSET = 212 - const_PANDORA_ALL_SCREENS_TOP_OFFSET

var const_PANDORA_TRACK_VIEW_ALBUM_ART_IMG_X_OFFSET = const_PANDORA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_X_OFFSET + 16
var const_PANDORA_TRACK_VIEW_ALBUM_ART_IMG_Y_OFFSET = const_PANDORA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_Y_OFFSET + 3

var const_PANDORA_TRACK_VIEW_STATION_ICON_ITEM_2_IMG_Y_OFFSET= 213 - const_PANDORA_ALL_SCREENS_TOP_OFFSET

var const_PANDORA_TRACK_VIEW_ICON_ITEM_3_IMG_Y_OFFSET = 217 + 24 + 37 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_TRACK_VIEW_X_OFFSET = 440
//{ modified by cheolhwan 2014-01-09. ITS 218741.
//var const_PANDORA_TRACK_VIEW_STATION_ICON_ITEM_2_IMG_Y_OFFSET= 217 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//var const_PANDORA_TRACK_VIEW_ICON_ITEM_3_IMG_Y_OFFSET = 217 + 24 + 37 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//var const_PANDORA_TRACK_VIEW_ICON_ITEM_4_IMG_Y_OFFSET = 217+24+37+24+37 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//var const_PANDORA_TRACK_VIEW_ICON_ITEM_5_IMG_Y_OFFSET = 217+24+37+24+37+24+37- const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_TRACK_VIEW_STATION_ICON_ITEM_2_IMG_Y_OFFSET= 213 - const_PANDORA_ALL_SCREENS_TOP_OFFSET - const_PANDORA_MODE_ITEM_HEIGHT
var const_PANDORA_TRACK_VIEW_ICON_ITEM_3_IMG_Y_OFFSET = 213 + 24 + 37 - const_PANDORA_ALL_SCREENS_TOP_OFFSET - const_PANDORA_MODE_ITEM_HEIGHT
var const_PANDORA_TRACK_VIEW_ICON_ITEM_4_IMG_Y_OFFSET = 213+24+37+24+37 - const_PANDORA_ALL_SCREENS_TOP_OFFSET - const_PANDORA_MODE_ITEM_HEIGHT
var const_PANDORA_TRACK_VIEW_ICON_ITEM_5_IMG_Y_OFFSET = 213+24+37+24+37+24+37- const_PANDORA_ALL_SCREENS_TOP_OFFSET - const_PANDORA_MODE_ITEM_HEIGHT
//} modified by cheolhwan 2014-01-09. ITS 218741.
var const_PANDORA_TRACK_VIEW_TEXT_OFFSET_FROM_ICONS = 64 //59
var const_PANDORA_TRACK_VIEW_MENU_BOOKMARK_SONG_BUTTON_WIDTH = 381
var const_PANDORA_TRACK_VIEW_MENU_BOOKMARK_ARTIST_BUTTON_WIDTH = 378
var const_PANDORA_TRACK_VIEW_MENU_WHY_THIS_SONG_BUTTON_WIDTH = 509

var const_PANDORA_TRACK_VIEW_ALBUM_ART_LOADING_IMG_X_OFFSET = const_PANDORA_TRACK_VIEW_ALBUM_ART_IMG_X_OFFSET + 75
var const_PANDORA_TRACK_VIEW_ALBUM_ART_LOADING_IMG_Y_OFFSET = const_PANDORA_TRACK_VIEW_ALBUM_ART_IMG_Y_OFFSET + 60
var const_PANDORA_TARCK_VIEW_TRACK_INFO_TEXT_WIDTH_FIRST = 524
var const_PANDORA_TARCK_VIEW_TRACK_INFO_TEXT_WIDTH = 655 //524

var const_APP_PANDORA_TRACK_VIEW_BUTTONS_TOP_MARGIN_OFFSET = 465 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_APP_PANDORA_TRACK_VIEW_PANDORALOGO_X_OFFSET = 46
var const_APP_PANDORA_TRACK_VIEW_PANDORALOGO_Y_OFFSET = 103 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_APP_PANDORA_TRACK_VIEW_RATING_ICON_X_OFFSET = 1081 + 80
var const_APP_PANDORA_TRACK_VIEW_RATING_ICON_Y_OFFSET = 510 - const_APP_PANDORA_TRACK_VIEW_BUTTONS_TOP_MARGIN_OFFSET -const_PANDORA_ALL_SCREENS_TOP_OFFSET

//{ modified by yongkyun.lee 2014-10-24 for : 
var const_APP_PANDORA_TRACK_VIEW_PALY_ICON_X_OFFSET = 471 + 94
var const_APP_PANDORA_TRACK_VIEW_PALY_ICON_Y_OFFSET = 465  - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_APP_PANDORA_TRACK_VIEW_SKIP_ICON_X_OFFSET = 471 + 94 + 156
var const_APP_PANDORA_TRACK_VIEW_SKIP_ICON_Y_OFFSET = 465 + 41 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//} modified by yongkyun.lee 2014-10-24 

//{ added by esjang 2013.06.14 for UX update
var const_PANDORA_MODEWIDGET_LOGO_TEXT1_X_OFFSET = 46 //+ const_APP_PANDORA_TRACK_VIEW_PANDORALOGO_X_OFFSET
var const_PANDORA_MODEWIDGET_LOGO_TEXT1_Y_OFFSET = 103 - 6 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//var const_PANDORA_MODEWIDGET_LOGO_TEXT1_Y_OFFSET = 103 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//} added by esjang 2013.06.14 for UX update

/**********************************************************/
// Pandora DeviceList View Screen specific
/**********************************************************/
var const_PANDORA_DEVICELIST_VIEW_TEXT1_Y_OFFSET = 281-const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_DEVICELIST_VIEW_TEXT1_X_OFFSET = 140
var const_PANDORA_DEVICELIST_VIEW_TEXT1_WIDTH = 240 + 279 + 489
var const_PANDORA_DEVICELIST_VIEW_TEXT2_Y_OFFSET = 281 + 60 -const_PANDORA_ALL_SCREENS_TOP_OFFSET

var const_APP_PANDORA_DEVICE_LIST_FIRSTDEVICEOFTWO_X_OFFSET = 140 + 240
var const_APP_PANDORA_DEVICE_LIST_SECONDDEVICEOFTWO_X_OFFSET = 140 + 240 + 271
var const_APP_PANDORA_DEVICE_LIST_FIRSTDEVICEOFTHREE_X_OFFSET = 245
var const_APP_PANDORA_DEVICE_LIST_SECONDDEVICEOFTHREE_X_OFFSET = 245 + 271
var const_APP_PANDORA_DEVICE_LIST_THIRDDEVICEOFTHREE_X_OFFSET = 245 + 271 + 271

var const_APP_PANDORA_DEVICE_LIST_CONNECTION_TYPE_ICON_TOP_MARGIN = 16
var const_APP_PANDORA_DEVICE_LIST_CONNECTION_TYPE_ICON_LEFT_MARGIN = 18
var const_APP_PANDORA_DEVICE_LIST_CONNECTION_TYPE_ICON_WIDTH = 213
var const_APP_PANDORA_DEVICE_LIST_CONNECTION_TYPE_TEXT_WIDTH = 213
var const_APP_PANDORA_DEVICE_LIST_CONNECTION_TYPE_TEXT1_TOP_MARGIN = 119 + 16 - const_PANDORA_FONT_SIZE_TEXT_HDR_24_FONT/2
var const_APP_PANDORA_DEVICE_LIST_CONNECTION_TYPE_TEXT2_TOP_MARGIN = 119 + 16 + 26 - const_PANDORA_FONT_SIZE_TEXT_HDR_24_FONT/2
var const_APP_PANDORA_DEVICE_LIST_TWO_X_OFFSET = 140 + 240
var const_APP_PANDORA_DEVICE_LIST_TWO_Y_OFFSET = 281 + 60 + 75 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_APP_PANDORA_DEVICE_LIST_THREE_X_OFFSET = 245
var const_APP_PANDORA_DEVICE_LIST_THREE_Y_OFFSET = 416 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_APP_PANDORA_DEVICE_LIST_ICONS_SPACE = 22

/**********************************************************/
// Pandora Connecting Off Screen specific
/**********************************************************/
var const_PANDORA_ERROR_VIEW_WARNING_IMG_Y_OFFSET = 245- const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_ERROR_VIEW_WARNING_IMG_X_OFFSET = 200 + 388

var const_PANDORA_ERROR_VIEW_TEXT1_X_OFFSET = 140
var const_PANDORA_ERROR_VIEW_TEXT1_Y_OFFSET = 273//281- const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_ERROR_VIEW_TEXT2_X_OFFSET = 140
var const_PANDORA_ERROR_VIEW_TEXT2_Y_OFFSET = 281 + 60- const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_ERROR_VIEW_OK_BUTTON_HEIGHT = 35+35
var const_PANDORA_ERROR_VIEW_OK_BUTTON_WIDTH = 30+328+30
var const_PANDORA_ERROR_VIEW_TEXT_WIDTH = 315 + 685
var const_PANDORA_ERROR_VIEW_OK_BUTTON_Y_OFFSET = 273+60+60+84//281+60+193- const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_PANDORA_ERROR_VIEW_OK_BUTTON_X_OFFSET = 409
var const_PANDORA_CONNECTING_TEXT_COLOR_BLACK = "#000000"
var const_PANDORA_ERROR_VIEW_OK_BUTTON_TEXT_WIDTH = 344
var const_PANDORA_ERROR_VIEW_OK_BUTTON_TEXT_LEFT_MARGIN = 14
var const_PANDORA_ERROR_VIEW_OK_BUTTON_TEXT_TOP_MARGIN = 33

// StationListView
var const_PANDORA_STATION_LIST_VIEW_BG_NUMBER = 1
var const_PANDORA_STATION_LIST_VIEW_TOPMARGIN_AREA_CONTAINER = 4
//var const_PANDORA_STATION_LIST_VIEW_HEIGHT_AREA_CONTAINER = 472 //esjang test
var const_PANDORA_STATION_LIST_VIEW_HEIGHT_AREA_CONTAINER = 545
var const_PANDORA_STATION_LIST_VIEW_WIDTH_AREA_CONTAINER = 1280
var const_PANDORA_STATION_LIST_VIEW_WIDTH_CATEGORY_LIST = 250
var const_PANDORA_STATION_LIST_VIEW_COLUMN_X = 39
var const_PANDORA_STATION_LIST_VIEW_COLUMN_SPACING = 5
var const_PANDORA_STATION_LIST_VIEW_COLUMN_BORDER_WIDTH = 5
var const_PANDORA_STATION_LIST_VIEW_ROW_HEIGHT = 88//85 //esjang test
var const_PANDORA_STATION_LIST_VIEW_ROW_HEIGHT_WITHBORDER = 92//91//88 //modified by esjang 2014.01.11
var const_PANDORA_STATION_LIST_VIEW_ROW_SPACING = 28
var const_PANDORA_STATION_LIST_VIEW_SECTION_IMAGE_X = 21
var const_PANDORA_STATION_LIST_VIEW_SECTION_TEXT_X = 27
var const_PANDORA_STATION_LIST_VIEW_SECTION_HEADING_TEXT_LEFTMARGIN = 52
var const_PANDORA_STATION_LIST_VIEW_SECTION_HEADING_TEXT_WIDTH = 45
var const_PANDORA_STATION_LIST_VIEW_SECTION_HEADING_TEXT_FONT_POINTSZIE = 30//32 // modified by jyjeon 2014.02.03 for ITS 223503
var const_PANDORA_STATION_LIST_VIEW_TRACKITEM_TEXT_FONT_POINTSZIE = 40
var const_PANDORA_STATION_LIST_VIEW_TRACKITEM_TEXT_X = 176
var const_PANDORA_STATION_LIST_VIEW_TRACKITEM_TEXT_WIDTH = 1004
var const_PANDORA_STATION_LIST_VIEW_THUMBNAIL_IMAGE_SIZE = 74
var const_PANDORA_STATION_LIST_VIEW_BG_THUMBNAIL_IMAGE_SIZE = const_PANDORA_STATION_LIST_VIEW_THUMBNAIL_IMAGE_SIZE + 2 // added by esjang 2013.03.06 for DH Genesis GUI Design Guideline v1.1.2(2013.02.28)
var const_PANDORA_STATION_LIST_VIEW_PICT_IMAGE_SIZE = 45
var const_PANDORA_STATION_LIST_VIEW_CURRENTPLAYING_IMAGE_TOPMARGIN = 15
var const_PANDORA_STATION_LIST_VIEW_CURRENTPLAYING_IMAGE_WIDTH = 46// modified by esjang 2013.03.06 for DH Genesis GUI Design Guideline v1.1.2(2013.02.28)
var const_PANDORA_STATION_LIST_VIEW_SHARED_IMAGE_X = 1126 // added by jyjeon 2013.12.09 for UX Update
var const_PANDORA_STATION_LIST_VIEW_SHARED_IMAGE_TOPMARGIN = 12 // added by jyjeon 2013.12.09 for UX Update 
var const_PANDORA_STATION_LIST_VIEW_SHARED_IMAGE_WIDTH = 45 // added by jyjeon 2013.12.09 for UX Update 
var const_PANDORA_STATION_LIST_VIEW_TRACK_IMAGE_LFET_MARGIN = 72
var const_PANDORA_PLAY_PROGRESS_BAR_BG_NUMBER = 3
var const_PANDORA_PLAY_PROGRESS_BAR_LEFT_MARGIN = 28
var const_PANDORA_PLAY_PROGRESS_BAR_TOP_MARGIN = -28
var const_PANDORA_PLAY_PROGRESS_BAR_RIGHT_MARGIN = 38
var const_PANDORA_STATION_LIST_VIEW_BORDER_COLOR = "#0080FF"
var const_PANDORA_STATION_LIST_VIEW_COLUMN_COLOR = "transparent"

// ProgressBar
var const_PANDORA_PROGRESS_BAR_WIDTH = 500
var const_PANDORA_PROGRESS_BAR_SMALL_HEIGHT = 80
var const_PANDORA_PROGRESS_BAR_BIG_HEIGHT = 100
var const_PANDORA_PROGRESS_BAR_CURRENT_TIME_RIGHT_MARGIN = 14
var const_PANDORA_PROGRESS_BAR_TOTAL_TIME_LEFT_MARGIN = 14
var const_PANDORA_PROGRESS_BAR_ALBUM_TEXT_BOTTOM_MARGIN = 9
var const_PANDORA_PROGRESS_BAR_SONG_TEXT_LEFT_MARGIN = 10
var const_PANDORA_PROGRESS_BAR_LINE_HEIGHT = 50
var const_PANDORA_PROGRESS_BAR_LINE_LEFT_MARGIN = 76
var const_PANDORA_PROGRESS_BAR_SLIDER_Y = -25
var const_PANDORA_PROGRESS_BAR_SLIDER_X_0 = 0
var const_PANDORA_PROGRESS_BAR_SLIDER_X_10 = 10
var const_PANDORA_PROGRESS_BAR_SLIDER_X_20 = 20
var const_PANDORA_PROGRESS_BAR_SLIDER_X_30 = 30
var const_PANDORA_PROGRESS_BAR_SLIDER_X_40 = 40
var const_PANDORA_PROGRESS_BAR_SLIDER_X_50 = 50
var const_PANDORA_PROGRESS_BAR_SLIDER_X_60 = 60
var const_PANDORA_PROGRESS_BAR_SLIDER_X_70 = 70
var const_PANDORA_PROGRESS_BAR_SLIDER_X_80 = 80
var const_PANDORA_PROGRESS_BAR_SLIDER_X_90 = 90
var const_PANDORA_PROGRESS_BAR_SLIDER_X_100 = 100
var const_PANDORA_PROGRESS_BAR_PLAY_RANDOM_BOTTOM_MARGIN = 8
var const_PANDORA_PROGRESS_BAR_PLAY_REPEAT_RIGHT_MARGIN = 7



//AlphabeticList
var const_PANDORA_ALPHABETIC_LIST_RIGHT_MARGIN = 16
var const_PANDORA_ALPHABETIC_LIST_TOP_MARGIN = 22
var const_PANDORA_ALPHABETIC_LIST_LISTVIEW_TOP_MARGIN = 33
var const_PANDORA_ALPHABETIC_FONT_TYPE = "NewHDR"//"HDR"
var const_PANDORA_ALPHABETIC_TEXT_COLOR = "#FFFFFF"
var const_PANDORA_LIST_FONT_SIZE = 40

var const_PANDORA_ALPHABETIC_USB_ITEM_WIDTH = 22
var const_PANDORA_ALPHABETIC_USB_ICON_SEARCH_LEFT_MARGIN = 0
var const_PANDORA_ALPHABETIC_USB_ICON_INDEX_LEFT_MARGIN = 6
var const_PANDORA_ALPHABETIC_USB_ITEM_HEIGHT_TOP_PART = 28
var const_PANDORA_ALPHABETIC_USB_ITEM_HEIGHT_BOTTOM_PART = 20
var const_PANDORA_ALPHABETIC_MENU_TOP_MARGIN = 188 - const_PANDORA_ALL_SCREENS_TOP_OFFSET//218 - const_PANDORA_ALL_SCREENS_TOP_OFFSET// modified by esjang 2014.02.07 for ITS # 223522
var const_PANDORA_ALPHABETIC_MENU_LEFT_MARGIN = 1209
var const_PANDORA_ALPHABETIC_MENU_WIDTH = 40
var const_PANDORA_ALPHABETIC_TEXT_POINTSIZE = 22
var const_PANDORA_ALPHABETIC_TEXT_WIDTH = 30
var const_PANDORA_ALPHABETIC_MENU_ICON_Y = 54//44 // modified by esjang 2014.02.07 for ITS # 223522

//{ removed by yongkyun.lee 2014-03-21 for : ITS 230348
//var const_PANDORA_POPUP_QUICKSCROLL_X = 539
//var const_PANDORA_POPUP_QUICKSCROLL_Y = 388 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
//var const_PANDORA_POPUP_QUICKSCROLL_TEXT_LEFTMARGIN = 17
//var const_PANDORA_POPUP_QUICKSCROLL_TEXT_WIDTH = 170
//} removed by yongkyun.lee 2014-03-21 for : ITS 230348
var const_PANDORA_POPUP_QUICKSCROLL_TEXT_FONT_POINTSIZE = 100

var const_PANDORA_JOG_EVENT_CENTER = 0
var const_PANDORA_JOG_EVENT_ARROW_UP = 1
var const_PANDORA_JOG_EVENT_ARROW_DOWN = 2
var const_PANDORA_JOG_EVENT_ARROW_LEFT = 3
var const_PANDORA_JOG_EVENT_ARROW_RIGHT = 4
var const_PANDORA_EVT_KEY_JOG_TOP_RIGHT = 5
var const_PANDORA_EVT_KEY_JOG_BOTTOM_RIGHT = 6
var const_PANDORA_EVT_KEY_JOG_TOP_LEFT = 7
var const_PANDORA_EVT_KEY_JOG_BOTTOM_LEFT =8
var const_PANDORA_JOG_EVENT_WHEEL_LEFT = 9
var const_PANDORA_JOG_EVENT_WHEEL_RIGHT = 10
var const_PANDORA_JOG_EVENT_HOLD_LEFT = 11
var const_PANDORA_JOG_EVENT_HOLD_RIGHT = 12
var const_PANDORA_EVT_KEY_JOG_NONE = 13

var const_PANDORA_SCREEN_STATE_ACTIVE_PREV_SCREEN = -1
var const_PANDORA_SCREEN_STATE_ACTIVE_PLAY_SCREEN = 0
var const_PANDORA_SCREEN_STATE_ACTIVE_LIST_SCREEN = 1
var const_PANDORA_LIST_VIEW_QUICKMIX_Y_OFFSET = 7
var const_PANDORA_LIST_VIEW_QUICKMIX_TEXT_X_OFFSET = 104
var const_PANDORA_LIST_VIEW_QUICKMIX_IMAGE_X = 57
var const_APP_PANDORA_LIST_VIEW_SECTION_HEADING_X = 13
var const_APP_PANDORA_LIST_VIEW_SECTION_HEADING_HEIGHT = 45
var const_APP_PANDORA_LIST_VIEW_LIST_ITEM_DELEGATE_Y_OFFSET = 254 - const_PANDORA_ALL_SCREENS_TOP_OFFSET

var const_PANDORA_LANGCONTEXT = "main"

//keyboard
var const_SEARCH_FOCUS_INDEX_KEYPAD_AND_SEARCH_LIST = 1
var const_SEARCH_FOCUS_INDEX_SEARCH_BUTTON = 0

//search color
var const_SEARCH_BOX_TEXT_COLOR_BLACK = "#000000"
var const_SEARCH_BOX_TEXT_COLOR_DIMMED_GREY = "#9E9E9E"
var const_COLOR_BRIGHT_GREY = "#FAFAFA"

/** Search box constants */
var const_SEARCH_BOX_TEXT_TO = 35
var const_SEARCH_BOX_TEXT_LO = 164
var const_SEARCH_BOX_TEXT_RO = 15 /** By eye */
var const_SEARCH_BOX_TEXT_PIXEL_SIZE = 30
var const_SEARCH_BOX_MAX_KEY_CODE = 0xFF
var const_SEARCH_BOX_MAX_SYMBOL_CODE = 0xFFFF
var const_SEARCH_BOX_MASK_1 = 0xD800
var const_SEARCH_BOX_MASK_2 = 0xDC00
var const_SEARCH_BOX_MASK_3 = 0x3FF
var const_SEARCH_BOX_SUB_VAL = 0x10000

/** Contacts search list */
//Contacts search list
var const_SEARCH_LIST_ITEM_CONTACT_HEIGHT = 90
var const_SEARCH_LIST_ITEM_CONTACT_WIDTH = 1280
var const_SEARCH_LIST_ITEM_CONTACT_ICON_LO = 26
var const_SEARCH_LIST_ITEM_CONTACT_NAME_LO = const_SEARCH_LIST_ITEM_CONTACT_ICON_LO + 95
var const_SEARCH_LIST_ITEM_CONTACT_NAME_VCO = 45
var const_SEARCH_LIST_ITEM_CONTACT_NAME_WIDTH = 423
var const_SEARCH_LIST_ITEM_CONTACT_NUBMER_LO = const_SEARCH_LIST_ITEM_CONTACT_NAME_LO + const_SEARCH_LIST_ITEM_CONTACT_NAME_WIDTH + 80
var const_SEARCH_LIST_ITEM_CONTACT_NUBMER_VCO = const_SEARCH_LIST_ITEM_CONTACT_NAME_VCO
var const_SEARCH_LIST_ITEM_CONTACT_NUBMER_WIDTH = 358
var const_SEARCH_LIST_ITEM_CONTACT_DIAL_BUTTON_LO = const_SEARCH_LIST_ITEM_CONTACT_NUBMER_LO + const_SEARCH_LIST_ITEM_CONTACT_NUBMER_WIDTH + 80
var const_SEARCH_LIST_ITEM_CONTACT_DIAL_BUTTON_TO = 11

var const_SEARCH_FOCUS_ACTIVE_KEYPAD = 0

/** Search */
var const_SEARCH_TEXT_BOX_POS_X = 0
var const_SEARCH_TEXT_BOX_POS_Y = 90
var const_SEARCH_TEXT_BOX_POS_Z = 3
var const_SEARCH_TEXT_BOX_WIDTH = 850
var const_SEARCH_PAD_WIDGET_POS_Y = 334 //298
var const_SEARCH_KEYPAD_Z = 3
/** FIXME! It mast be 170 instead of 200 after when textbox item will be changed to mode area */
var const_SEARCH_LIST_WIDGET_POS_Y = 200
var const_SEARCH_LIST_HEIGHT = 480
var const_SEARCH_LIST_Z = 2
var const_BACK_BUTTON_X = 1059
var const_BACK_BUTTON_Y = const_SEARCH_TEXT_BOX_POS_Y
var const_SEARCH_BUTTON_X = 859
var const_SEARCH_BUTTON_Y = const_SEARCH_TEXT_BOX_POS_Y

var const_FONT_FAMILY_BASE = "NewHDR"//"HDR"
var const_FONT_SIZE_BUTTONS = 36

var const_LIST_VIEW_MOVING_NONE = 0
var const_LIST_VIEW_MOVING_UP = 1
var const_LIST_VIEW_MOVING_DOWN = 2

//=========================================Added for new UX

var const_APP_PANDORA_ALBUM_ART_WIDTH = 224
var const_APP_PANDORA_ALBUM_ART_HEIGHT = 224
//{ modified by cheolhwan 2014-01-09. ITS 218741.
//var const_APP_PANDORA_BASE_ALBUMART_TOP_MARGIN_REFLECT = 354
var const_APP_PANDORA_BASE_ALBUMART_TOP_MARGIN_REFLECT = 354 - const_PANDORA_MODE_ITEM_HEIGHT
//} modified by cheolhwan 2014-01-09. ITS 218741.
var const_APP_PANDORA_ALBUM_LEFT_MARGIN = 19
var const_APP_PANDORA_ALBUM_TOP_MARGIN = 3
var const_APP_PANDORA_ALBUMART_LEFT_MARGIN_REFLECT_X = 163
//{ modified by cheolhwan 2014-01-09. ITS 218741.
//var const_APP_PANDORA_ALBUMART_TOP_MARGIN_REFLECT_Y = 343
var const_APP_PANDORA_ALBUMART_TOP_MARGIN_REFLECT_Y = 343 - const_PANDORA_MODE_ITEM_HEIGHT
//} modified by cheolhwan 2014-01-09. ITS 218741.
var const_APP_PANDORA_BASE_ALBUMART_LEFT_MARGIN_REFLECT = 158
//=========================================Added for new UX


// list view high light image  width / height

var const_APP_PANDORA_LISTITEM_WITH_QUICKSCROOL_HIGHLIGHT_WIDTH = 1188
var const_APP_PANDORA_LISTITEM_WITH_QUICKSCROOL_HIGHLIGHT_HEIGHT = 95
var const_APP_PANDORA_LISTITEM_WITHOUT_QUICKSCROOL_HIGHLIGHT_WIDTH = 1238
var const_APP_PANDORA_LISTITEM_WITHOUT_QUICKSCROOL_HIGHLIGHT_HEIGHT = 97
