<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_A00</source>
        <translation>[</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A01</source>
        <translation>]</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A02</source>
        <translation>{</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A03</source>
        <translation>}</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A04</source>
        <translation>#</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A05</source>
        <translation>%</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A06</source>
        <translation>^</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A07</source>
        <translation>*</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A08</source>
        <translation>+</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A09</source>
        <translation>=</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B00</source>
        <translation>`</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B01</source>
        <translation>\</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B02</source>
        <translation>|</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B03</source>
        <translation>~</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B04</source>
        <translation>&lt;</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B05</source>
        <translation>&gt;</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B06</source>
        <translation>&#8361;</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B07</source>
        <translation>€</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B08</source>
        <translation>＄</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C00</source>
        <translation>2/2</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C01</source>
        <translation>ㆍ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C02</source>
        <translation>℃</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C03</source>
        <translation>℉</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C04</source>
        <translation>¢</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C05</source>
        <translation>£</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C06</source>
        <translation>¤</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C07</source>
        <translation>§</translation>
    </message>
</context>
</TS>
