<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_A00</source>
        <translation>á</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A01</source>
        <translation>ä</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A02</source>
        <translation>ą</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A03</source>
        <translation>ć</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A04</source>
        <translation>č</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A05</source>
        <translation>ď</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A06</source>
        <translation>é</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A07</source>
        <translation>ę</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A08</source>
        <translation>ě</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A09</source>
        <translation>í</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A10</source>
        <translation>ł</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B00</source>
        <translation>ĺ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B01</source>
        <translation>ľ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B02</source>
        <translation>ń</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B03</source>
        <translation>ň</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B04</source>
        <translation>ó</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B05</source>
        <translation>ô</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B06</source>
        <translation>ŕ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B07</source>
        <translation>ř</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B08</source>
        <translation>ś</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B09</source>
        <translation>š</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B10</source>
        <translation>ť</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C00</source>
        <translation>2/3</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C01</source>
        <translation>ü</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C02</source>
        <translation>ú</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C03</source>
        <translation>ů</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C04</source>
        <translation>ý</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C05</source>
        <translation>ź</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C06</source>
        <translation>ż</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C07</source>
        <translation>ž</translation>
    </message>
</context>
</TS>
