<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ko">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_A00</source>
        <translation>ㄱ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A01</source>
        <translation>ㄴ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A02</source>
        <translation>ㄷ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A03</source>
        <translation>ㄹ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A04</source>
        <translation>ㅁ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A05</source>
        <translation>ㅂ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A06</source>
        <translation>ㅅ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A07</source>
        <translation>ㅏ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A08</source>
        <translation>ㅑ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A09</source>
        <translation>ㅓ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A10</source>
        <translation>ㅕ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A11</source>
        <translation>ㅗ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A12</source>
        <translation>ㅛ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B00</source>
        <translation>ㅇ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B01</source>
        <translation>ㅈ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B02</source>
        <translation>ㅊ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B03</source>
        <translation>ㅋ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B04</source>
        <translation>ㅌ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B05</source>
        <translation>ㅍ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B06</source>
        <translation>ㅎ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B07</source>
        <translation>ㅜ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B08</source>
        <translation>ㅠ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B09</source>
        <translation>ㅡ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B10</source>
        <translation>ㅣ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C00</source>
        <translation>ㄲ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C01</source>
        <translation>ㄸ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C02</source>
        <translation>ㅃ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C03</source>
        <translation>ㅆ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C04</source>
        <translation>ㅉ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C05</source>
        <translation>ㅐ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C06</source>
        <translation>ㅔ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C07</source>
        <translation>ㅒ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C08</source>
        <translation>ㅖ</translation>
    </message>
</context>
</TS>
