<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_A00</source>
        <translation>Ā</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A01</source>
        <translation>Ă</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A02</source>
        <translation>Ç</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A03</source>
        <translation>Ċ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A04</source>
        <translation>Đ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A05</source>
        <translation>Ð</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A06</source>
        <translation>Ē</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A07</source>
        <translation>Ė</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A08</source>
        <translation>Ğ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A09</source>
        <translation>Ģ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A10</source>
        <translation>Ħ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A11</source>
        <translation>Ī</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B00</source>
        <translation>Ĭ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B01</source>
        <translation>Į</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B02</source>
        <translation>I</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B03</source>
        <translation>Ķ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B04</source>
        <translation>Ļ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B05</source>
        <translation>Ņ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B06</source>
        <translation>Ő</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B07</source>
        <translation>Õ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B08</source>
        <translation>Ö</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B09</source>
        <translation>Ŗ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B10</source>
        <translation>Ş</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B11</source>
        <translation>Ș</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C00</source>
        <translation>3/3</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C01</source>
        <translation>Ţ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C02</source>
        <translation>Ț</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C03</source>
        <translation>Þ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C04</source>
        <translation>Ū</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C05</source>
        <translation>Ű</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C06</source>
        <translation>Ų</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C07</source>
        <translation>Ü</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C08</source>
        <translation>Ŷ</translation>
    </message>

</context>
</TS>
