<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ko" sourcelanguage="en_CA">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_Q</source>
        <translation>ㅂ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_W</source>
        <translation>ㅈ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_E</source>
        <translation>ㄷ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_R</source>
        <translation>ㄱ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_T</source>
        <translation>ㅅ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_Y</source>
        <translation>ㅛ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_U</source>
        <translation>ㅕ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_I</source>
        <translation>ㅑ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_O</source>
        <translation>ㅐ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_P</source>
        <translation>ㅔ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A</source>
        <translation>ㅁ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_S</source>
        <translation>ㄴ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_D</source>
        <translation>ㅇ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_F</source>
        <translation>ㄹ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_G</source>
        <translation>ㅎ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_H</source>
        <translation>ㅗ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_J</source>
        <translation>ㅓ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_K</source>
        <translation>ㅏ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_L</source>
        <translation>ㅣ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_Z</source>
        <translation>ㅋ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_X</source>
        <translation>ㅌ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C</source>
        <translation>ㅊ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_V</source>
        <translation>ㅍ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B</source>
        <translation>ㅠ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_N</source>
        <translation>ㅜ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_M</source>
        <translation>ㅡ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_Q_PRESS_AND_HOLD</source>
        <translation>ㅃ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_W_PRESS_AND_HOLD</source>
        <translation>ㅉ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_E_PRESS_AND_HOLD</source>
        <translation>ㄸ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_R_PRESS_AND_HOLD</source>
        <translation>ㄲ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_T_PRESS_AND_HOLD</source>
        <translation>ㅆ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_O_PRESS_AND_HOLD</source>
        <translation>ㅒ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_P_PRESS_AND_HOLD</source>
        <translation>ㅖ</translation>
    </message>
</context>
</TS>
