<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_A00</source>
        <translation>À</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A01</source>
        <translation>Á</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A02</source>
        <translation>Â</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A03</source>
        <translation>Ã</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A04</source>
        <translation>Ä</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A05</source>
        <translation>Å</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A06</source>
        <translation>Æ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A07</source>
        <translation>Ç</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A08</source>
        <translation>È</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A09</source>
        <translation>É</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B00</source>
        <translation>Ê</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B01</source>
        <translation>Ë</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B02</source>
        <translation>Ì</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B03</source>
        <translation>Í</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B04</source>
        <translation>Î</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B05</source>
        <translation>Ï</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B06</source>
        <translation>Ñ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B07</source>
        <translation>Ò</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B08</source>
        <translation>Ó</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B09</source>
        <translation>Ô</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C00</source>
        <translation>Õ</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C01</source>
        <translation>Ö</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C02</source>
        <translation>Ø</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C03</source>
        <translation>Ù</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C04</source>
        <translation>Ú</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C05</source>
        <translation>Û</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C06</source>
        <translation>Ü</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C07</source>
        <translation>Ý</translation>
    </message>
</context>
</TS>
