<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_Q</source>
        <translation>q</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_W</source>
        <translation>w</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_E</source>
        <translation>e</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_R</source>
        <translation>r</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_T</source>
        <translation>t</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_Y</source>
        <translation>y</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_U</source>
        <translation>u</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_I</source>
        <translation>i</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_O</source>
        <translation>o</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_P</source>
        <translation>p</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A</source>
        <translation>a</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_S</source>
        <translation>s</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_D</source>
        <translation>d</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_F</source>
        <translation>f</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_G</source>
        <translation>g</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_H</source>
        <translation>h</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_J</source>
        <translation>j</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_K</source>
        <translation>k</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_L</source>
        <translation>l</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_Z</source>
        <translation>z</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_X</source>
        <translation>x</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C</source>
        <translation>c</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_V</source>
        <translation>v</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B</source>
        <translation>b</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_N</source>
        <translation>n</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_M</source>
        <translation>m</translation>
    </message>
</context>
</TS>
