<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>DHAVN_QwertyKeypad_Screen</name>
    <message>
        <source>STR_KEYPAD_TYPE_Q</source>
        <translation>A</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_W</source>
        <translation>B</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_E</source>
        <translation>C</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_R</source>
        <translation>D</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_T</source>
        <translation>E</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_Y</source>
        <translation>F</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_U</source>
        <translation>G</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_I</source>
        <translation>H</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_O</source>
        <translation>I</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_P</source>
        <translation>J</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_A</source>
        <translation>K</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_S</source>
        <translation>L</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_D</source>
        <translation>M</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_F</source>
        <translation>N</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_G</source>
        <translation>O</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_H</source>
        <translation>P</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_J</source>
        <translation>Q</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_K</source>
        <translation>R</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_L</source>
        <translation>S</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_Z</source>
        <translation>T</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_X</source>
        <translation>U</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_C</source>
        <translation>V</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_V</source>
        <translation>W</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_B</source>
        <translation>X</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_N</source>
        <translation>Y</translation>
    </message>
    <message>
        <source>STR_KEYPAD_TYPE_M</source>
        <translation>Z</translation>
    </message>
</context>
</TS>
