var const_COLOR_TEXT_BRIGHT_GREY = "#FAFAFA"
var const_COLOR_TEXT_DIMMED_GREY = "#9E9E9E"
var const_COLOR_TEXT_DIMMED_BLUE = "#447CAD"

var const_APP_SETTINGS_COLOR_TEXT_BLACK = "#000000"
var const_APP_SETTINGS_COLOR_TEXT_WHITE = "white"

var const_APP_SETTINGS_FONT_FAMILY_HDR = "HDR"
var const_APP_SETTINGS_FONT_FAMILY_HDB = "HDR"
