/** General*/
var const_ACTIVITY_SCROLL_SMAL_SWITCH =  34

var const_ACTIVITY_SCROLL_BIG_SWITCH =  64

var const_ACTIVITY_SCROLL_SMAL_SLIDER_WIDTH =  405

var const_ACTIVITY_SCROLL_BIG_SLIDER_WIDTH =  730

var const_ACTIVITY_SCROLL_DOUBLE_PNG_LEVEI =  43

var const_ACTIVITY_SCROLL_X =  100
var const_ACTIVITY_SCROLL_Y =  100

var const_ACTIVITY_SCROLL_CURSOR_SHIFT_HOR =  15
var const_ACTIVITY_SCROLL_CURSOR_SHIFT_VERT =  23

var const_ACTIVITY_SCROLL_Y_TEXT_HOR =  14
var const_ACTIVITY_SCROLL_Y_TEXT_VERT =  86

var const_ACTIVITY_SCROLL_INVALID_VALUE =  -1

var const_ACTIVITY_SCROLL_TEXT_FONT_FAMILY = "HDR"
var const_ACTIVITY_SCROLL_TEXT_PIXEL_SIZE = 35
var const_ACTIVITY_SCROLL_TEXT_PIXEL_SIZE_OVER = 36
var const_ACTIVITY_SCROLL_TEXT_COLOR = "#C1C1C1"



var const_SETTINGS_SOUND_BALANCE_SEAT_X = 320
var const_SETTINGS_SOUND_BALANCE_SEAT_Y = 60

var const_SETTINGS_SOUND_BALANCE_VL_SHIFT = 4
var const_SETTINGS_SOUND_BALANCE_VL_Y = 60
var const_SETTINGS_SOUND_BALANCE_VL_X = 320
var const_SETTINGS_SOUND_BALANCE_HL_SHIFT = 5

var const_SETTINGS_SOUND_BALANCE_TEXT_X = 10
var const_SETTINGS_SOUND_BALANCE_TEXT_Y = 10

var const_SETTINGS_SOUND_BALANCE_VALUE_X = 150
var const_SETTINGS_SOUND_BALANCE_FADER_VALUE_X = 120

var const_SETTINGS_SOUND_BALANCE_CURSOR_X_MIN = 320
var const_SETTINGS_SOUND_BALANCE_CURSOR_X_MAX = 610
var const_SETTINGS_SOUND_BALANCE_CURSOR_Y_MIN = 50
var const_SETTINGS_SOUND_BALANCE_CURSOR_Y_MAX = 395

var const_SETTINGS_SOUND_BALANCE_CURSOR_X_SHIFT = 31
var const_SETTINGS_SOUND_BALANCE_CURSOR_Y_SHIFT = 30

var const_SETTINGS_SOUND_BALANCE_RESET_BTN_Y = 390

var const_SETTINGS_SOUND_BALANCE_DEFAULT_BALANCE = 0
var const_SETTINGS_SOUND_BALANCE_DEFAULT_FADER = 0

var const_SETTINGS_BALANCE_VALUE_MAX = 10
var const_SETTINGS_BALANCE_VALUE_MIN = -10
var const_SETTINGS_BALANCE_VALUE_FADER_MAX = 10
var const_SETTINGS_BALANCE_VALUE_FADER_MIN = -10


var const_SETTINGS_BALANCE_CURSOR_MULTIPLY_X = 290
var const_SETTINGS_BALANCE_CURSOR_MULTIPLY_Y = 335

var const_SETTINGS_BALANCE_CURSOR_LINE_SHIFT = 25
var const_SETTINGS_BALANCE_CURSOR_LINE_X_SHIFT = 27
var const_SETTINGS_BALANCE_CURSOR_LINE_Y_SHIFT = 23






