/**
 * DHAVN_AppAhaConst.js
 */

.pragma library
/**********************************************************/
// Common
/**********************************************************/
var const_AHA_ALL_SCREEN_WIDTH = 1280
var const_AHA_MAIN_SCREEN_HEIGHT = 720

var const_AHA_COMMON_STATUS_BAR_HEIGHT = 93
var const_AHA_ALL_SCREEN_BOTTOM_MARGIN = 0

// Mode area
var const_AHA_MODE_ITEM_HEIGHT = 83
var const_AHA_MODE_ITEM_RIGHT_MARGIN = 23
var const_AHA_MODE_ITEM_LEFT_MARGIN = 23
var const_AHA_MODE_ITEM_TOP_MARGIN = 83

// Mode area back button
var const_AHA_MODE_ITEM_BACK_BUTTON_REL_TOP_MARGINv= 100-const_AHA_COMMON_STATUS_BAR_HEIGHT
var const_AHA_MODE_ITEM_BACK_BUTTON_REL_RIGHT_MARGIN = 0

// Mode area aha logo title
var const_AHA_MODE_ITEM_AHA_LOGO_REL_TOP_MARGIN = 118-const_AHA_COMMON_STATUS_BAR_HEIGHT

// All screens offset
var const_AHA_ALL_SCREENS_TOP_OFFSET = const_AHA_COMMON_STATUS_BAR_HEIGHT

// Color constants
var const_AHA_COLOR_TEXT_DIMMED_GREY = "#9E9E9E"
var const_AHA_COLOR_TEXT_BRIGHT_GREY = "#FAFAFA"
var const_AHA_COLOR_TEXT_PROGRESS_BLUE = "#0087EF"
var const_AHA_COLOR_TEXT_BUTTON_GREY = "#2F2F2F"
var const_AHA_COLOR_TEXT_GREY = "#C1C1C1"
var const_AHA_COLOR_SUB_TEXT_GREY = "#D4D4D4"
var const_AHA_COLOR_DISABLE_GREY = "#5B5B5B"
var const_AHA_COLOR_BLACK = "black"
//Tan: added when upgrading from 124.1 to 5.35.2
var const_AHA_COLOR_TEXT_CURR_STATION = "#7CBDFF"
var const_AHA_LIGHT_DIMMED = "#92949D"

// Text constants
var const_AHA_FONT_FAMILY_HDR = "NewHDR"
var const_AHA_FONT_FAMILY_HDB = "NewHDB"

var const_AHA_FONT_SIZE_TEXT_BUTTON_FONT = 34
var const_AHA_FONT_SIZE_TEXT_45_FONT = 45
var const_AHA_FONT_SIZE_TEXT_HDB_24_FONT = 24
var const_AHA_FONT_SIZE_TEXT_HDR_22_FONT = 22
var const_AHA_FONT_SIZE_TEXT_HDR_24_FONT = 24
var const_AHA_FONT_SIZE_TEXT_HDR_32_FONT = 32
var const_AHA_FONT_SIZE_TEXT_HDR_36_FONT = 36
var const_AHA_FONT_SIZE_TEXT_HDR_40_FONT = 40 //hsryu_0315_change_text_format
var const_AHA_FONT_SIZE_TEXT_HDR_29_FONT = 29
var const_AHA_FONT_SIZE_TEXT_HDB_32_FONT = 32
var const_AHA_FONT_SIZE_TEXT_TIME_FONT = 34
var const_AHA_FONT_SIZE_TEXT_SUB_FONT = 28
var const_AHA_FONT_SIZE_TEXT_INDEX_FONT = 22
var const_AHA_FONT_SIZE_TEXT_AUX = 250
var const_AHA_FONT_PIXEL_SIZE_TEXT_BUTTON_FONT_LEFT = 29
var const_AHA_FONT_PIXEL_SIZE_TEXT_BUTTON_FONT = 25
var const_AHA_FONT_SIZE_TEXT_HDR_26_FONT = 26
var const_AHA_FONT_SIZE_TEXT_HDR_45_FONT = 45
var const_AHA_FONT_SIZE_TEXT_HDB_40_FONT = 40
var const_AHA_FONT_SIZE_TEXT_HDB_62_FONT = 62
var const_AHA_FONT_SIZE_TEXT_HDB_50_FONT = 50   //wsuk.kim  station_name

//Timer Constant
var const_AHA_TIMER_COUNTER_MAX_VAL = 16
var const_AHA_TIMER_COUNTER_MIN_VAL = 0

/**********************************************************/
// Aha Why This Song Screen specific
/**********************************************************/
var const_AHA_WHY_THIS_SONG_TEXT1_X_OFFSET = 101
var const_AHA_WHY_THIS_SONG_TEXT1_Y_OFFSET = 208 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_WHY_THIS_SONG_Y_OFFSET_FROM_PREV_TEXT = 60
var const_AHA_WHY_THIS_SONG_TEXT_WIDTH = 1100
var const_AHA_RIGHT_MARGIN = 53
var const_AHA_SCROLL_STEP_SIZE = 30


/**********************************************************/
// Aha Connecting Screen specific
/**********************************************************/
var const_AHA_CONNECTING_SCREEN_HEIGHT = 720 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_CONNECTING_WAIT_IMAGE_X_OFFSET = 140 + 462
var const_AHA_CONNECTING_WAIT_IMAGE_Y_OFFSET = 281 + 60 + 103 - const_AHA_ALL_SCREENS_TOP_OFFSET


var const_AHA_CONNECTING_TEXT_COLOR = const_AHA_COLOR_TEXT_BRIGHT_GREY
var const_AHA_CONNECTING_TEXT_FONT_FAMILY = const_AHA_FONT_FAMILY_HDR
//hsryu_0315_change_text_format
var const_AHA_CONNECTING_TEXT_FONT_SIZE = const_AHA_FONT_SIZE_TEXT_HDR_40_FONT

var const_AHA_CONNECTING_TEXT_WIDTH = 462 + 538
var const_AHA_CONNECTING_TEXT_HEIGHT = 60
var const_AHA_CONNECTING_WAIT_TEXT1_X_OFFSET = 140
var const_AHA_CONNECTING_WAIT_TEXT1_Y_OFFSET = 281 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_CONNECTING_WAIT_TEXT_LOADING_Y_OFFSET = 235 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_CONNECTING_WAIT_TEXT_LOADING_X_OFFSET = 140
var const_AHA_CONNECTING_WAIT_TEXT2_X_OFFSET = 140
var const_AHA_CONNECTING_WAIT_TEXT2_Y_OFFSET = 281 + 60 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_CONNECTING_VIEW_TIMER_COUNTER_MAX_VAL = 16
var const_AHA_CONNECTING_VIEW_TIMER_COUNTER_MIN_VAL = 0
var const_AHA_CONNECTION_ESTABLISHED = 1
var const_AHA_CONNECTION_FAILED = 0
var const_AHA_CONNECTING_VIEW_TEXT2_Y_OFFSET_FROM_TEXT1 = 60


/**************************************************************************/
/******   aha wait view specific***************************************/
/**************************************************************************/
var const_AHA_LOADING_WAIT_IMAGE_X_OFFSET = 140 + 462
var const_AHA_LOADING_WAIT_IMAGE_Y_OFFSET = 235 + 55 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_LOADING_TEXT_COLOR = const_AHA_COLOR_TEXT_BRIGHT_GREY
var const_AHA_LOADING_TEXT_FONT_FAMILY = const_AHA_FONT_FAMILY_HDB
var const_AHA_LOADING_TEXT_FONT_SIZE = const_AHA_FONT_SIZE_TEXT_HDB_32_FONT
var const_AHA_LOADING_WAIT_TEXT_LOADING_X_OFFSET = 140
var const_AHA_LOADING_WAIT_TEXT_LOADING_Y_OFFSET = 235 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_LOADING_TEXT_WIDTH = 462 + 538


// PlayerView
var const_AHA_FONT_SIZE_TEXT_HDR_50_FONT = 50
var const_AHA_FONT_SIZE_TEXT_HDR_28_FONT = 28
var const_AHA_PLAYER_VIEW_BG_NUMBER = 3
var const_AHA_PLAYER_VIEW_ITEM_TOP_MARGIN = 20
var const_AHA_PROGRESS_BAR_ITEM_WIDTH = 726
var const_AHA_PROGRESS_BAR_ITEM_LEFT_MARGIN = 81
var const_AHA_PROGRESS_BAR_ITEM_BOTTOM_MARGIN = 80

/**********************************************************/
// Aha Track View Screen specific
/**********************************************************/
var const_AHA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_X_OFFSET = 161
var const_AHA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_Y_OFFSET = 212 - const_AHA_ALL_SCREENS_TOP_OFFSET    //wsuk.kim 121206_temp

/*wsuk.kim album img*/
var const_AHA_TRACK_VIEW_ALBUM_ART_IMG_W_OFFSET = 232
var const_AHA_TRACK_VIEW_ALBUM_ART_IMG_H_OFFSET = 219
var const_AHA_TRACK_VIEW_ALBUM_ART_IMG_LEFT_MARGIN = 9
var const_AHA_TRACK_VIEW_ALBUM_ART_IMG_TOP_MARGIN = 6
/*wsuk.kim album img*/

//hsryu_0611_album_reflection
var const_AHA_TRACK_VIEW_ALBUM_ART_LOAD_IMG_LEFT_MARGIN = 75
var const_AHA_TRACK_VIEW_ALBUM_ART_LOAD_IMG_TOP_MARGIN = 60

var const_AHA_TRACK_VIEW_ALBUM_ART_IMG_X_OFFSET = const_AHA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_X_OFFSET + 16
var const_AHA_TRACK_VIEW_ALBUM_ART_IMG_Y_OFFSET = const_AHA_TRACK_VIEW_DEFAULT_ALBUM_ART_IMG_Y_OFFSET + 3

var const_AHA_TRACK_VIEW_STATION_ICON_ITEM_2_IMG_Y_OFFSET= 217 - const_AHA_ALL_SCREENS_TOP_OFFSET

//wsuk.kim new_trackview
var const_AHA_TRACK_VIEW_STATION_ICON_X_OFFSET = 443
var const_AHA_TRACK_VIEW_STATION_ICON_IMG_W_OFFSET = 64
var const_AHA_TRACK_VIEW_STATION_ICON_IMG_H_OFFSET = 64
var const_AHA_TRACK_VIEW_TRACK_INFO_STATON_TEXT_WIDTH = 607
//wsuk.kim new_trackview

var const_AHA_TRACK_VIEW_ICON_ITEM_3_IMG_Y_OFFSET = 217 + 24 + 37 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_TRACK_VIEW_X_OFFSET = 445//wsuk.kim new_trackview    440
var const_AHA_TRACK_VIEW_ICON_ITEM_4_IMG_Y_OFFSET = 217+24+37+24+37 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_TRACK_VIEW_ICON_ITEM_5_IMG_Y_OFFSET = 217+24+37+24+37+24+37- const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_TRACK_VIEW_TEXT_OFFSET_FROM_ICONS = 95//wsuk.kim new_trackview  59
var const_AHA_TRACK_VIEW_MENU_BOOKMARK_SONG_BUTTON_WIDTH = 381
var const_AHA_TRACK_VIEW_MENU_BOOKMARK_ARTIST_BUTTON_WIDTH = 378
var const_AHA_TRACK_VIEW_MENU_WHY_THIS_SONG_BUTTON_WIDTH = 509

//hsryu_0408_change_load_pos
var const_AHA_TRACK_VIEW_ALBUM_ART_LOADING_IMG_X_OFFSET = const_AHA_TRACK_VIEW_ALBUM_ART_IMG_X_OFFSET + 70
var const_AHA_TRACK_VIEW_ALBUM_ART_LOADING_IMG_Y_OFFSET = const_AHA_TRACK_VIEW_ALBUM_ART_IMG_Y_OFFSET + 60
var const_AHA_TRACK_VIEW_TRACK_INFO_TEXT_WIDTH = 700//wsuk.kim new_trackview   661

var const_APP_AHA_TRACK_VIEW_AHALOGO_X_OFFSET = 46  //wsuk.kim AhaRadio logo 42
var const_APP_AHA_TRACK_VIEW_AHALOGO_Y_OFFSET = 105 - const_AHA_ALL_SCREENS_TOP_OFFSET //wsuk.kim AhaRadio logo 116 - const_PANDORA_ALL_SCREENS_TOP_OFFSET
var const_APP_AHA_TRACK_VIEW_RATING_ICON_X_OFFSET = 1068
var const_APP_AHA_TRACK_VIEW_BUTTONS_TOP_MARGIN_OFFSET = 520 - const_AHA_ALL_SCREENS_TOP_OFFSET

/**********************************************************/
// Tan Aha play view
/**********************************************************/
var const_AHA_TRACK_VIEW_VSPACE = 24;
var const_AHA_TRACK_SMALL_TEXT_HEIGHT = 30;
var const_AHA_TRACK_BIG_TEXT_HEIGHT = 38;

var const_AHA_TRACK_VIEW_STATIONLOGO_X = 440;
var const_AHA_TRACK_VIEW_STATIONLOGO_Y = 217 - const_AHA_ALL_SCREENS_TOP_OFFSET;

var const_AHA_TRACK_VIEW_DESC1_X = const_AHA_TRACK_VIEW_STATIONLOGO_X;
var const_AHA_TRACK_VIEW_DESC1_Y = const_AHA_TRACK_VIEW_STATIONLOGO_Y + const_AHA_TRACK_BIG_TEXT_HEIGHT;

var const_AHA_TRACK_VIEW_DESC2_X = const_AHA_TRACK_VIEW_STATIONLOGO_X;
var const_AHA_TRACK_VIEW_DESC2_Y = const_AHA_TRACK_VIEW_DESC1_Y + const_AHA_TRACK_BIG_TEXT_HEIGHT +
        const_AHA_TRACK_VIEW_VSPACE + 5;

var const_AHA_TRACK_VIEW_DESC3_X = const_AHA_TRACK_VIEW_STATIONLOGO_X;
var const_AHA_TRACK_VIEW_DESC3_Y = const_AHA_TRACK_VIEW_DESC2_Y + const_AHA_TRACK_SMALL_TEXT_HEIGHT +
        const_AHA_TRACK_VIEW_VSPACE;

var const_AHA_TRACK_VIEW_RATING_IMAGE_IMG_X = const_AHA_TRACK_VIEW_STATIONLOGO_X;
var const_AHA_TRACK_VIEW_RATING_IMAGE_IMG_Y = const_AHA_TRACK_VIEW_DESC3_Y + const_AHA_TRACK_SMALL_TEXT_HEIGHT +
        const_AHA_TRACK_VIEW_VSPACE + 10;

var const_AHA_TRACK_VIEW_PARTNER_LOGO_IMG_X_OFFSET = const_AHA_TRACK_VIEW_ALBUM_ART_IMG_X_OFFSET + 224/2 - 150/2;
var const_AHA_TRACK_VIEW_PARTNER_LOGO_IMG_Y_OFFSET = const_AHA_TRACK_VIEW_ALBUM_ART_IMG_Y_OFFSET + 224 + 20;

var const_AHA_TRACK_VIEW_LIKE_ICON_WIDTH = 80;
var const_AHA_TRACK_VIEW_LIKE_ICON_HEIGHT = 80;
/**********************************************************/
// Aha DeviceList View Screen specific
/**********************************************************/
var const_AHA_DEVICELIST_VIEW_TEXT1_Y_OFFSET = 281-const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_DEVICELIST_VIEW_TEXT1_X_OFFSET = 140
var const_AHA_DEVICELIST_VIEW_TEXT1_WIDTH = 240 + 279 + 489
var const_AHA_DEVICELIST_VIEW_TEXT2_Y_OFFSET = 281 + 60 -const_AHA_ALL_SCREENS_TOP_OFFSET

var const_APP_AHA_DEVICE_LIST_FIRSTDEVICEOFTWO_X_OFFSET = 140 + 240
var const_APP_AHA_DEVICE_LIST_SECONDDEVICEOFTWO_X_OFFSET = 140 + 240 + 271
var const_APP_AHA_DEVICE_LIST_FIRSTDEVICEOFTHREE_X_OFFSET = 245
var const_APP_AHA_DEVICE_LIST_SECONDDEVICEOFTHREE_X_OFFSET = 245 + 271
var const_APP_AHA_DEVICE_LIST_THIRDDEVICEOFTHREE_X_OFFSET = 245 + 271 + 271

var const_APP_AHA_DEVICE_LIST_CONNECTION_TYPE_ICON_TOP_MARGIN = 16
var const_APP_AHA_DEVICE_LIST_CONNECTION_TYPE_ICON_LEFT_MARGIN = 18
var const_APP_AHA_DEVICE_LIST_CONNECTION_TYPE_ICON_WIDTH = 213
var const_APP_AHA_DEVICE_LIST_CONNECTION_TYPE_TEXT_WIDTH = 213
var const_APP_AHA_DEVICE_LIST_CONNECTION_TYPE_TEXT1_TOP_MARGIN = 119 + 16 - const_AHA_FONT_SIZE_TEXT_HDR_24_FONT/2
var const_APP_AHA_DEVICE_LIST_CONNECTION_TYPE_TEXT2_TOP_MARGIN = 119 + 16 + 26 - const_AHA_FONT_SIZE_TEXT_HDR_24_FONT/2
var const_APP_AHA_DEVICE_LIST_TWO_X_OFFSET = 140 + 240
var const_APP_AHA_DEVICE_LIST_TWO_Y_OFFSET = 281 + 60 + 75 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_APP_AHA_DEVICE_LIST_THREE_X_OFFSET = 245
var const_APP_AHA_DEVICE_LIST_THREE_Y_OFFSET = 416 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_APP_AHA_DEVICE_LIST_ICONS_SPACE = 22

/**********************************************************/
// Aha Connecting Off Screen specific
/**********************************************************/
var const_AHA_ERROR_VIEW_TEXT1_X_OFFSET = 140
var const_AHA_ERROR_VIEW_TEXT1_Y_OFFSET = 281- const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_ERROR_VIEW_TEXT2_X_OFFSET = 140
var const_AHA_ERROR_VIEW_TEXT2_Y_OFFSET = 281 + 60- const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_ERROR_VIEW_TEXT_WIDTH = 269+731
var const_AHA_ERROR_VIEW_OK_BUTTON_Y_OFFSET = 333+60+84- const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_ERROR_VIEW_OK_BUTTON_X_OFFSET = 140+269
var const_AHA_ERROR_VIEW_OK_BUTTON_TEXT_WIDTH = 422

// StationListView
var const_AHA_STATION_LIST_VIEW_BG_NUMBER = 1
var const_AHA_STATION_LIST_VIEW_TOPMARGIN_AREA_CONTAINER = 4
var const_AHA_STATION_LIST_VIEW_HEIGHT_AREA_CONTAINER = 472
var const_AHA_STATION_LIST_VIEW_HEIGHT_AREA_CONTAINER = 545
var const_AHA_STATION_LIST_VIEW_WIDTH_AREA_CONTAINER = 1280
var const_AHA_STATION_LIST_VIEW_WIDTH_CATEGORY_LIST = 250
var const_AHA_STATION_LIST_VIEW_COLUMN_X = 39
var const_AHA_STATION_LIST_VIEW_COLUMN_SPACING = 5
var const_AHA_STATION_LIST_VIEW_ROW_HEIGHT = 85
var const_AHA_STATION_LIST_VIEW_ROW_HEIGHT_WITHBORDER = 88
var const_AHA_STATION_LIST_VIEW_ROW_SPACING = 28
var const_AHA_STATION_LIST_VIEW_SECTION_IMAGE_X = 21
var const_AHA_STATION_LIST_VIEW_SECTION_TEXT_X = 27
var const_AHA_STATION_LIST_VIEW_SECTION_HEADING_TEXT_LEFTMARGIN = 52
var const_AHA_STATION_LIST_VIEW_SECTION_HEADING_TEXT_WIDTH = 45
var const_AHA_STATION_LIST_VIEW_SECTION_HEADING_TEXT_FONT_POINTSZIE = 32
var const_AHA_STATION_LIST_VIEW_TRACKITEM_TEXT_FONT_POINTSZIE = 40
//hsryu_0315_change_text_format
var const_AHA_STATION_LIST_VIEW_TRACKITEM_TEXT_X = 156
var const_AHA_STATION_LIST_VIEW_TRACKITEM_TEXT_WIDTH = 1146
var const_AHA_STATION_LIST_VIEW_THUMBNAIL_IMAGE_SIZE = 76
var const_AHA_STATION_LIST_VIEW_THUMBNAIL_IMAGE_WIDTH = 74
var const_AHA_STATION_LIST_VIEW_THUMBNAIL_IMAGE_HEIGHT = 74 //hsryu_0314_fit_image
var const_AHA_STATION_LIST_VIEW_PICT_IMAGE_SIZE = 45
var const_AHA_STATION_LIST_VIEW_CURRENTPLAYING_IMAGE_TOPMARGIN = 15
var const_AHA_STATION_LIST_VIEW_CURRENTPLAYING_IMAGE_WIDTH = 46
//hsryu_0315_change_text_format
var const_AHA_STATION_LIST_VIEW_TRACK_IMAGE_LFET_MARGIN = const_AHA_STATION_LIST_VIEW_CURRENTPLAYING_IMAGE_WIDTH + 10
var const_AHA_PLAY_PROGRESS_BAR_BG_NUMBER = 3
var const_AHA_PLAY_PROGRESS_BAR_LEFT_MARGIN = 28
var const_AHA_PLAY_PROGRESS_BAR_TOP_MARGIN = -28
var const_AHA_PLAY_PROGRESS_BAR_RIGHT_MARGIN = 38
var const_AHA_STATION_LIST_VIEW_BORDER_COLOR = "#0080FF"
var const_AHA_STATION_LIST_VIEW_COLUMN_COLOR = "transparent"

// ContentsListView hsryu added
var const_AHA_CONTENT_LIST_VIEW_TRACKITEM_BORDER_WIDTH = 1238

// Preset/LBS ListView hsryu added
var const_AHA_PRESET_LEFT_MENU_BG_WIDTH = 276
var const_AHA_PRESET_LEFT_MENU_BG_HEIGHT = 555
var const_AHA_STATION_LEFT_MENU_BUTTON_WIDTH = 276
var const_AHA_STATION_LEFT_MENU_BUTTON_FG_IMAGE_X = 103
var const_AHA_STATION_LEFT_MENU_BUTTON_FG_IMAGE_Y = 78
var const_AHA_STATION_LEFT_MENU_BUTTON_FG_IMAGE_WIDTH = 46
var const_AHA_STATION_LEFT_MENU_BUTTON_FG_IMAGE_HEIGHT = 46
var const_AHA_STATION_LEFT_MENU_BUTTON_TEXT_WIDTH = 240
var const_AHA_STATION_LEFT_MENU_BUTTON_TEXT_SIZE = 40
var const_AHA_STATION_LIST_TRACK_PLAYING_IMAGE_RIGHT_MARGIN = 6
var const_AHA_STATION_LIST_TRACK_QUICKMIX_IMAGE_LFET_MARGIN = 56

var const_AHA_PRESET_LIST_VIEW_ROW_HEIGHT_WITHBORDER = 92
var const_AHA_PRESET_LIST_VIEW_ROW_HEIGHT_WITHBORDER_FOCUS = 97
var const_AHA_PRESET_LIST_VIEW_TRACKITEM_TEXT_WIDTH = 788
var const_AHA_PRESET_LIST_VIEW_BORDER_WIDTH = 969
var const_AHA_PRESET_LIST_VIEW_WIDTH = 993


// ProgressBar
var const_AHA_PROGRESS_BAR_WIDTH = 500
var const_AHA_PROGRESS_BAR_SMALL_HEIGHT = 80
var const_AHA_PROGRESS_BAR_BIG_HEIGHT = 100
var const_AHA_PROGRESS_BAR_CURRENT_TIME_RIGHT_MARGIN = 14
var const_AHA_PROGRESS_BAR_TOTAL_TIME_LEFT_MARGIN = 14
var const_AHA_PROGRESS_BAR_ALBUM_TEXT_BOTTOM_MARGIN = 9
var const_AHA_PROGRESS_BAR_SONG_TEXT_LEFT_MARGIN = 10
var const_AHA_PROGRESS_BAR_LINE_HEIGHT = 50
var const_AHA_PROGRESS_BAR_LINE_LEFT_MARGIN = 76
var const_AHA_PROGRESS_BAR_SLIDER_Y = -25
var const_AHA_PROGRESS_BAR_SLIDER_X_0 = 0
var const_AHA_PROGRESS_BAR_SLIDER_X_10 = 10
var const_AHA_PROGRESS_BAR_SLIDER_X_20 = 20
var const_AHA_PROGRESS_BAR_SLIDER_X_30 = 30
var const_AHA_PROGRESS_BAR_SLIDER_X_40 = 40
var const_AHA_PROGRESS_BAR_SLIDER_X_50 = 50
var const_AHA_PROGRESS_BAR_SLIDER_X_60 = 60
var const_AHA_PROGRESS_BAR_SLIDER_X_70 = 70
var const_AHA_PROGRESS_BAR_SLIDER_X_80 = 80
var const_AHA_PROGRESS_BAR_SLIDER_X_90 = 90
var const_AHA_PROGRESS_BAR_SLIDER_X_100 = 100
var const_AHA_PROGRESS_BAR_PLAY_RANDOM_BOTTOM_MARGIN = 8
var const_AHA_PROGRESS_BAR_PLAY_REPEAT_RIGHT_MARGIN = 7



//AlphabeticList
var const_AHA_ALPHABETIC_LIST_RIGHT_MARGIN = 16
var const_AHA_ALPHABETIC_LIST_TOP_MARGIN = 22
var const_AHA_ALPHABETIC_LIST_LISTVIEW_TOP_MARGIN = 33
var const_AHA_ALPHABETIC_FONT_TYPE = "NewHDR"
var const_AHA_ALPHABETIC_TEXT_COLOR = "#FFFFFF"
var const_AHA_LIST_FONT_SIZE = 40

var const_AHA_ALPHABETIC_USB_ITEM_WIDTH = 22
var const_AHA_ALPHABETIC_USB_ICON_SEARCH_LEFT_MARGIN = 0
var const_AHA_ALPHABETIC_USB_ICON_INDEX_LEFT_MARGIN = 6
var const_AHA_ALPHABETIC_USB_ITEM_HEIGHT_TOP_PART = 28
var const_AHA_ALPHABETIC_USB_ITEM_HEIGHT_BOTTOM_PART = 20
var const_AHA_ALPHABETIC_MENU_TOP_MARGIN = 218 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_ALPHABETIC_MENU_LEFT_MARGIN = 1209
var const_AHA_ALPHABETIC_MENU_WIDTH = 40
var const_AHA_ALPHABETIC_TEXT_POINTSIZE = 22
var const_AHA_ALPHABETIC_TEXT_WIDTH = 30
var const_AHA_ALPHABETIC_MENU_ICON_Y = 44

var const_AHA_POPUP_QUICKSCROLL_X = 539
var const_AHA_POPUP_QUICKSCROLL_Y = 388 - const_AHA_ALL_SCREENS_TOP_OFFSET
var const_AHA_POPUP_QUICKSCROLL_TEXT_LEFTMARGIN = 17
var const_AHA_POPUP_QUICKSCROLL_TEXT_WIDTH = 170
var const_AHA_POPUP_QUICKSCROLL_TEXT_FONT_POINTSIZE = 100

var const_AHA_JOG_EVENT_CENTER = 0
var const_AHA_JOG_EVENT_ARROW_UP = 1
var const_AHA_JOG_EVENT_ARROW_DOWN = 2
var const_AHA_JOG_EVENT_ARROW_LEFT = 3
var const_AHA_JOG_EVENT_ARROW_RIGHT = 4
var const_AHA_EVT_KEY_JOG_TOP_RIGHT = 5
var const_AHA_EVT_KEY_JOG_BOTTOM_RIGHT = 6
var const_AHA_EVT_KEY_JOG_TOP_LEFT = 7
var const_AHA_EVT_KEY_JOG_BOTTOM_LEFT =8
var const_AHA_JOG_EVENT_WHEEL_LEFT = 9
var const_AHA_JOG_EVENT_WHEEL_RIGHT = 10
var const_AHA_JOG_EVENT_HOLD_LEFT = 11
var const_AHA_JOG_EVENT_HOLD_RIGHT = 12
var const_AHA_EVT_KEY_JOG_NONE = 13

var const_AHA_SCREEN_STATE_ACTIVE_PREV_SCREEN = -1
var const_AHA_SCREEN_STATE_ACTIVE_PLAY_SCREEN = 0
var const_AHA_SCREEN_STATE_ACTIVE_LIST_SCREEN = 1
var const_AHA_LIST_VIEW_QUICKMIX_Y_OFFSET = 7
var const_AHA_LIST_VIEW_QUICKMIX_TEXT_X_OFFSET = 104
var const_AHA_LIST_VIEW_QUICKMIX_IMAGE_X = 57
var const_APP_AHA_LIST_VIEW_SECTION_HEADING_X = 13
var const_APP_AHA_LIST_VIEW_SECTION_HEADING_HEIGHT = 62
var const_APP_AHA_LIST_VIEW_LIST_ITEM_DELEGATE_Y_OFFSET = 254 - const_AHA_ALL_SCREENS_TOP_OFFSET

var const_AHA_LANGCONTEXT = "main"

//keyboard
var const_SEARCH_FOCUS_INDEX_KEYPAD_AND_SEARCH_LIST = 1
var const_SEARCH_FOCUS_INDEX_SEARCH_BUTTON = 0

//search color
var const_SEARCH_BOX_TEXT_COLOR_BLACK = "#000000"
var const_SEARCH_BOX_TEXT_COLOR_DIMMED_GREY = "#9E9E9E"
var const_COLOR_BRIGHT_GREY = "#FAFAFA"

/** Search box constants */
var const_SEARCH_BOX_TEXT_TO = 35
var const_SEARCH_BOX_TEXT_LO = 164
var const_SEARCH_BOX_TEXT_RO = 15 /** By eye */
var const_SEARCH_BOX_TEXT_PIXEL_SIZE = 30
var const_SEARCH_BOX_MAX_KEY_CODE = 0xFF
var const_SEARCH_BOX_MAX_SYMBOL_CODE = 0xFFFF
var const_SEARCH_BOX_MASK_1 = 0xD800
var const_SEARCH_BOX_MASK_2 = 0xDC00
var const_SEARCH_BOX_MASK_3 = 0x3FF
var const_SEARCH_BOX_SUB_VAL = 0x10000

/** Contacts search list */
//Contacts search list
var const_SEARCH_LIST_ITEM_CONTACT_HEIGHT = 90
var const_SEARCH_LIST_ITEM_CONTACT_WIDTH = 1280
var const_SEARCH_LIST_ITEM_CONTACT_ICON_LO = 26
var const_SEARCH_LIST_ITEM_CONTACT_NAME_LO = const_SEARCH_LIST_ITEM_CONTACT_ICON_LO + 95
var const_SEARCH_LIST_ITEM_CONTACT_NAME_VCO = 45
var const_SEARCH_LIST_ITEM_CONTACT_NAME_WIDTH = 423
var const_SEARCH_LIST_ITEM_CONTACT_NUBMER_LO = const_SEARCH_LIST_ITEM_CONTACT_NAME_LO + const_SEARCH_LIST_ITEM_CONTACT_NAME_WIDTH + 80
var const_SEARCH_LIST_ITEM_CONTACT_NUBMER_VCO = const_SEARCH_LIST_ITEM_CONTACT_NAME_VCO
var const_SEARCH_LIST_ITEM_CONTACT_NUBMER_WIDTH = 358
var const_SEARCH_LIST_ITEM_CONTACT_DIAL_BUTTON_LO = const_SEARCH_LIST_ITEM_CONTACT_NUBMER_LO + const_SEARCH_LIST_ITEM_CONTACT_NUBMER_WIDTH + 80
var const_SEARCH_LIST_ITEM_CONTACT_DIAL_BUTTON_TO = 11

var const_SEARCH_FOCUS_ACTIVE_KEYPAD = 0

/** Search */
var const_SEARCH_TEXT_BOX_POS_X = 0
var const_SEARCH_TEXT_BOX_POS_Y = 90
var const_SEARCH_TEXT_BOX_POS_Z = 3
var const_SEARCH_TEXT_BOX_WIDTH = 850
var const_SEARCH_PAD_WIDGET_POS_Y = 334 //298
var const_SEARCH_KEYPAD_Z = 3
/** FIXME! It mast be 170 instead of 200 after when textbox item will be changed to mode area */
var const_SEARCH_LIST_WIDGET_POS_Y = 200
var const_SEARCH_LIST_HEIGHT = 480
var const_SEARCH_LIST_Z = 2
var const_BACK_BUTTON_X = 1059
var const_BACK_BUTTON_Y = const_SEARCH_TEXT_BOX_POS_Y
var const_SEARCH_BUTTON_X = 859
var const_SEARCH_BUTTON_Y = const_SEARCH_TEXT_BOX_POS_Y

var const_FONT_FAMILY_BASE = "NewHDR"
var const_FONT_SIZE_BUTTONS = 36

var const_LIST_VIEW_MOVING_NONE = 0
var const_LIST_VIEW_MOVING_UP = 1
var const_LIST_VIEW_MOVING_DOWN = 2

var const_STATION_LIST_PRESET_FOCUS_SCREEN = 1  //"Preset"
var const_STATION_LIST_LBS_FOCUS_SCREEN = 2     //"LBS"


var const_STATION_LIST_LEFT_MENU_PRESET_FOCUS = 1  //"Preset on Left Menu"
var const_STATION_LIST_LEFT_MENU_LBS_FOCUS = 3  //"LBS on Left Menu"
var const_STATION_LIST_PRESET_LIST_FOCUS = 5  //"Preset list"
var const_STATION_LIST_LBS_LIST_FOCUS = 7  //"LBS list"
var const_STATION_LIST_TITLE_FOCUS = 9  //"Title"
var const_STATION_LIST_TRACK_VIEW_FOCUS = 11  //"Track View"
var const_STATION_LIST_CONTENT_LIST_FOCUS = 13  //"Content List"
var const_STATION_LIST_ERROR_VIEW_FOCUS = 15 //"Error View" //hsryu_0607_inititialize_controller

//hsryu added
/** Popup Title text */
/** Title text */
var const_TITLE_TEXT_PT = 44
var const_TITLE_TEXT_COLOR = "#B6C9FF"
var const_TITLE_TEXT_COLOR_BG = "#000000"
var const_TITLE_X = 45
var const_TITLE_MY = 59
var const_CONTENT_TEXT_PT = 2

//popup margin
var const_POPUPTYPE_A_TOP_MARGIN = 208
var const_POPUPTYPE_A_LEFT_MARGIN = 93
var const_POPUPTYPE_B_TOP_MARGIN = 171
var const_POPUPTYPE_B_LEFT_MARGIN = 93
var const_POPUPTYPE_C_TOP_MARGIN = 215
var const_POPUPTYPE_C_LEFT_MARGIN = 250
var const_POPUPTYPE_D_TOP_MARGIN = 168
var const_POPUPTYPE_D_LEFT_MARGIN = 93
var const_POPUPTYPE_E_TOP_MARGIN = 93
var const_POPUPTYPE_E_LEFT_MARGIN = 131
var const_POPUPTYPE_F_TOP_MARGIN = 404
var const_POPUPTYPE_F_LEFT_MARGIN = 250

var const_POPUPTYPE_D_CONTEXT_TOP_MARGIN = 80
var const_POPUPTYPE_G_TOP_MARGIN = 130

var const_POPUPTYPE_ETC01_TOP_MARGIN = 119
var const_POPUPTYPE_ETC01_LEFT_MARGIN = 93

/** Popup content */
var const_TEXT_COLOR = "#FAFAFA"
var const_TEXT_COLOR_BG = "#000000"
var const_TEXT_COLOR_HIGHLIGHT = "#0087EF"
var const_TEXT_PT = 32
var const_TEXT_LIST_PT = 32
var const_TEXTONLY_SPACING = 51 - const_TEXT_PT
var const_TEXT_FONT_FAMILY = "NewHDB"
var const_TEXT_TOAST_PT = 36

/** Cue Jog Long Pressed Timer **/
var const_AHA_CUE_LEFT_TIMER_COUNTER_MIN_VAL = 0
var const_AHA_CUE_LEFT_TIMER_COUNTER_MAX_VAL = 5
var const_AHA_CUE_RIGHT_TIMER_COUNTER_MIN_VAL = 10
var const_AHA_CUE_RIGHT_TIMER_COUNTER_MAX_VAL = 15

/** SEEK, TRACK Long Pressed Allowed Key **/
var const_AHA_SEEK_OR_JOGLEFT_ALLOW_KEY = 1
var const_AHA_TRACK_OR_JOGRIGHT_ALLOW_KEY = 2

var const_AHA_STATION_LIST_LOOPING_HOLD = 6

var const_AHA_NO_SUPPORT_SKIP_BACK = 11
var const_AHA_NO_SUPPORT_SKIP = 12
var const_AHA_NO_SUPPORT_REW15 = 13
var const_AHA_NO_SUPPORT_FW30 = 14
var const_AHA_SKIP_NOT_AVAILABLE = 15
var const_AHA_AHA_FEATURE_NOT_AVAILABLE_DURING_CALL = 16

