#!/bin/sh
if [ $# -ne 1 ]
then
        exit 0;
fi


TARGET_PID=`pgrep -l $1 | awk '{print $1}'`
UPGRADE_PID=`pgrep -l AppUpgrade | awk '{print $1}'`

if [ -n "$UPGRADE_PID" ] ; then
	for i in $TARGET_PID; do
			if [ $i -ne $UPGRADE_PID ]
			then
				kill -9 $i
			fi
	done
fi

STATUS_PID=`pgrep -l statusdata | awk '{print $1}'`
if [ -n "$STATUS_PID" ] ; then
	kill -9 $STATUS_PID
fi

GRACENOTE_PID=`pgrep -l DHAVN_Gra | awk '{print $1}'`
if [ -n "$GRACENOTE_PID" ] ; then
	kill -9 $GRACENOTE_PID
fi

EMERGENCY_PID=`pgrep -l micom_emergency | awk '{print $1}'`
if [ -n "$EMERGENCY_PID" ] ; then
	kill -9 $EMERGENCY_PID
fi

