<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="zh_CN">
   <context>
      <name>RadioStringInfo</name>
      <message>
         <source>STR_RADIO_MENU_ALL_CHANNEL_SCAN</source>
         <translation>浏览所有频道</translation>
      </message>
      <message>
         <source>STR_RADIO_BAND_AM</source>
         <translation>AM</translation>
      </message>
      <message>
         <source>STR_RADIO_MENU_AUTO_STORE</source>
         <translation>自动选台</translation>
      </message>
      <message>
         <source>STR_RADIO_BAND_FM2</source>
         <translation>FM2</translation>
      </message>
      <message>
         <source>STR_RADIO_BAND_MENU</source>
         <translation>菜单</translation>
      </message>
      <message>
         <source>STR_RADIO_MENU_PRESET_SCAN</source>
         <translation>预置电台浏览</translation>
      </message>
      <message>
         <source>STR_RADIO_MENU_EDIT_PRESET_ORDER</source>
         <translation>预设电台排序</translation>
      </message>
      <message>
         <source>STR_RADIO_MENU_SAVE_AS_PRESET</source>
         <translation>另存为预设</translation>
      </message>
      <message>
         <source>STR_RADIO_POPUP_PRESET_SAVE_SUCCESSFULLY</source>
         <translation>已成功另存为预设</translation>
      </message>
      <message>
         <source>STR_RADIO_MENU_SOUND_SETTINGS</source>
         <translation>声音设置</translation>
      </message>
      <message>
         <source>STR_RADIO_SAVE</source>
         <translation>保存</translation>
      </message>
      <message>
         <source>STR_RADIO_MENU_STOP_SCAN</source>
         <translation>停止浏览</translation>
      </message>
      <message>
         <source>STR_RADIO_PREVENT_SAVE</source>
         <translation>停止</translation>
      </message>
      <message>
         <source>STR_RADIO_BAND_FM1</source>
         <translation>FM1</translation>
      </message>
   </context>
</TS>
