.pragma library

/** Basic layout - Home */

var CHECKBOX_LIST_HOME_LEFT_OFFSET            = 38
var CHECKBOX_LIST_HOME_TEXT_LEFT_OFFSET       = 4
var CHECKBOX_LIST_HOME_FONT_TYPE              = "HDR"
var CHECKBOX_LIST_HOME_FONT_TYPE_NEW              = "DH_HDR"
var CHECKBOX_LIST_HOME_FONT_SIZE              = 40
var CHECKBOX_LIST_HOME_FONT_COLOR             = "#FAFAFA"
var CHECKBOX_LIST_HOME_WIDTH                  = 1201
var CHECKBOX_LIST_HOME_ROW_HEIGHT             = 90
var CHECKBOX_LIST_HOME_DELIMITER_URL          = "/app/share/images/general/list_line.png"
var CHECKBOX_LIST_HOME_CHECKED_N_URL          = "/app/share/images/general/checkbox_check_n.png"
var CHECKBOX_LIST_HOME_UNCHECKED_N_URL        = "/app/share/images/general/checkbox_uncheck_n.png"
var CHECKBOX_LIST_HOME_CHECKED_D_URL          = "/app/share/images/general/checkbox_check_d.png"
var CHECKBOX_LIST_HOME_UNCHECKED_D_URL        = "/app/share/images/general/checkbox_uncheck_d.png"
var CHECKBOX_LIST_HOME_HILIGHTED_URL          = "/app/share/images/general/checkbox_f.png"

/** Check Box Layout for Music */

var CHECKBOX_LIST_MUSIC_LEFT_OFFSET           = 294
var CHECKBOX_LIST_MUSIC_TEXT_LEFT_OFFSET      = 16
var CHECKBOX_LIST_MUSIC_FONT_TYPE             = "HDR"
var CHECKBOX_LIST_MUSIC_FONT_TYPE_NEW             = "DH_HDR"
var CHECKBOX_LIST_MUSIC_FONT_SIZE             = 40
var CHECKBOX_LIST_MUSIC_FONT_COLOR            = "#FAFAFA"
var CHECKBOX_LIST_MUSIC_WIDTH                 = 771
var CHECKBOX_LIST_MUSIC_ROW_HEIGHT            = 90
var CHECKBOX_LIST_MUSIC_DELIMITER_URL         = CHECKBOX_LIST_HOME_DELIMITER_URL
var CHECKBOX_LIST_MUSIC_CHECKED_N_URL         = CHECKBOX_LIST_HOME_CHECKED_N_URL
var CHECKBOX_LIST_MUSIC_UNCHECKED_N_URL       = CHECKBOX_LIST_HOME_UNCHECKED_N_URL
var CHECKBOX_LIST_MUSIC_CHECKED_D_URL         = CHECKBOX_LIST_HOME_CHECKED_D_URL
var CHECKBOX_LIST_MUSIC_UNCHECKED_D_URL       = CHECKBOX_LIST_HOME_UNCHECKED_D_URL

/** Check Box Layout for Bluetooth */

var CHECKBOX_LIST_BT_LEFT_OFFSET              = 31
var CHECKBOX_LIST_BT_TEXT_LEFT_OFFSET         = 10
var CHECKBOX_LIST_BT_TEXT2_RIGHT_OFFSET       = 20
var CHECKBOX_LIST_BT_FONT_TYPE                = "HDR"
var CHECKBOX_LIST_BT_FONT_TYPE_NEW                = "DH_HDR"
var CHECKBOX_LIST_BT_FONT_SIZE                = 40
var CHECKBOX_LIST_BT_SMALL_FONT_SIZE          = 28
var CHECKBOX_LIST_BT_FONT_COLOR               = "#FAFAFA"
var CHECKBOX_LIST_BT_SMALL_FONT_COLOR         = "#9E9E9E"
var CHECKBOX_LIST_BT_WIDTH                    = 1212
var CHECKBOX_LIST_BT_ROW_HEIGHT               = 90
var CHECKBOX_LIST_BT_DELIMITER_URL            = CHECKBOX_LIST_HOME_DELIMITER_URL
var CHECKBOX_LIST_BT_CHECKED_N_URL            = CHECKBOX_LIST_HOME_CHECKED_N_URL
var CHECKBOX_LIST_BT_UNCHECKED_N_URL          = CHECKBOX_LIST_HOME_UNCHECKED_N_URL
var CHECKBOX_LIST_BT_CHECKED_D_URL            = CHECKBOX_LIST_HOME_CHECKED_D_URL
var CHECKBOX_LIST_BT_UNCHECKED_D_URL          = CHECKBOX_LIST_HOME_UNCHECKED_D_URL

/** Check Box Layout for DMB */
var CHECKBOX_LIST_DMB_LEFT_OFFSET              = 266
var CHECKBOX_LIST_DMB_TEXT_LEFT_OFFSET         = 19
var CHECKBOX_LIST_DMB_TEXT2_LEFT_OFFSET        = 19
var CHECKBOX_LIST_DMB_TEXT_BOTTOM_OFFSET       = 51
var CHECKBOX_LIST_DMB_TEXT2_BOTTOM_OFFSET      = 11
var CHECKBOX_LIST_DMB_FONT_TYPE                = "HDR"
var CHECKBOX_LIST_DMB_FONT_TYPE_NEW                = "DH_HDR"
var CHECKBOX_LIST_DMB_FONT_SIZE                = 40
var CHECKBOX_LIST_DMB_SMALL_FONT_SIZE          = 30
var CHECKBOX_LIST_DMB_FONT_COLOR               = "#FAFAFA"
var CHECKBOX_LIST_DMB_SMALL_FONT_COLOR         = "#0087EF"
var CHECKBOX_LIST_DMB_WIDTH                    = 970
var CHECKBOX_LIST_DMB_ROW_HEIGHT               = 110
var CHECKBOX_LIST_DMB_DELIMITER_URL            = CHECKBOX_LIST_HOME_DELIMITER_URL
var CHECKBOX_LIST_DMB_CHECKED_N_URL            = CHECKBOX_LIST_HOME_CHECKED_N_URL
var CHECKBOX_LIST_DMB_UNCHECKED_N_URL          = CHECKBOX_LIST_HOME_UNCHECKED_N_URL
var CHECKBOX_LIST_DMB_CHECKED_D_URL            = CHECKBOX_LIST_HOME_CHECKED_D_URL
var CHECKBOX_LIST_DMB_UNCHECKED_D_URL          = CHECKBOX_LIST_HOME_UNCHECKED_D_URL

var const_TRANSPARENT_COLOR = "#00ffffff"
var const_SELECTION_COLOR = "#00aef8"
var const_BORDER_SELECTION_WIDTH = 8
var const_CHECKBOX_LANGCONTEXT = "main"

var const_JOG_EVENT_ARROW_UP = 0
var const_JOG_EVENT_ARROW_DOWN = 1
var const_JOG_EVENT_ARROW_LEFT = 2
var const_JOG_EVENT_ARROW_RIGHT = 3
var const_JOG_EVENT_WHEEL_LEFT = 4
var const_JOG_EVENT_WHEEL_RIGHT = 5
var const_JOG_EVENT_CENTER = 6
var const_JOG_EVENT_HOLD_LEFT = 7
var const_JOG_EVENT_HOLD_RIGHT = 8

var const_CHECKBOX_LIST_LEFT_FOCUS_LOST = 0
var const_CHECKBOX_LIST_RIGHT_FOCUS_LOST = 1
var const_CHECKBOX_LIST_UPPER_FOCUS_LOST = 2
var const_CHECKBOX_LIST_LOWER_FOCUS_LOST = 3
