<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="zh_CN" sourcelanguage="en_US">
<context>
    <name>NonAV</name>
    <message>
        <source>STR_NONAV_DRIVE</source>
        <translation>驾驶模式</translation>
    </message>
    <message>
        <source>STR_NONAV_DRIVING_ECO</source>
        <translation>经济驾驶</translation>
    </message>
    <message>
        <source>STR_NONAV_DRIVING_NORMAL</source>
        <translation>标准</translation>
    </message>
    <message>
        <source>STR_NONAV_DRIVING_SPORTS</source>
        <translation>体育</translation>
    </message>
    <message>
        <source>STR_NONAV_DRIVINGSNOW</source>
        <translation>雪地</translation>
    </message>
    <message>
        <source>STR_NONAV_HIGH</source>
        <translation>高</translation>
    </message>
    <message>
        <source>STR_NONAV_LOW</source>
        <translation>低</translation>
    </message>
    <message>
        <source>STR_HVAC_strDriver</source>
        <translation>驾驶座</translation>
    </message>
    <message>
        <source>STR_HVAC_strMENU</source>
        <translation>菜单</translation>
    </message>
    <message>
        <source>STR_HVAC_strMENUDHPE</source>
        <translation>菜单</translation>
    </message>
    <message>
        <source>STR_HVAC_strPassenger</source>
        <translation>副驾驶座</translation>
    </message>
    <message>
        <source>STR_NONAV_SMART_CO2_VENT</source>
        <translation>SMART CO2 VENTILATION正在运行</translation>
    </message>
    <message>
        <source>STR_NONAV_SMART_VENT</source>
        <translation>Smart Ventilation正在运行</translation>
    </message>
    <message>
        <source>STR_HVAC_strRearOff</source>
        <translation>关闭后部气候控制</translation>
    </message>
    <message>
        <source>STR_HVAC_strRearOn</source>
        <translation>打开后部气候控制</translation>
    </message>
    <message>
        <source>STR_HVAC_strRear</source>
        <translation>后部气候控制</translation>
    </message>
    <message>
        <source>STR_HVAC_strSmartVentOff</source>
        <translation>Smart Vent 已关闭。</translation>
    </message>
    <message>
        <source>STR_HVAC_strSmartVentOn</source>
        <translation>Smart Vent 已开启。</translation>
    </message>
    <message>
        <source>STR_HVAC_strSmartVent</source>
        <translation>智能通风</translation>
    </message>
    <message>
        <source>STR_HVAC_strADSOn</source>
        <translation>自动除雾已开启</translation>
    </message>
    <message>
        <source>STR_HVAC_strADSOff</source>
        <translation>自动除雾已关闭</translation>
    </message>
    <message>
        <source>STR_HVAC_strADS</source>
        <translation>自动除雾系统</translation>
    </message>
    <message>
        <source>STR_NONAV_ADS_OSD_ON</source>
        <translation>自动除雾系统处于“开”状态</translation>
    </message>
    <message>
        <source>STR_NONAV_ADS_OSD_OFF</source>
        <translation>自动除雾系统处于“关”状态</translation>
    </message>
    <message>
        <source>STR_OUTSIDE_TEMP</source>
        <translation>外部</translation>
    </message>
    <message>
       <source>STR_HVAC_HELP</source>
       <translation>帮助</translation>
    </message>
    <message>
       <source>STR_HVAC_HELP_REAR</source>
       <translation>关闭或打开后排座椅的气候控制</translation>
    </message>
    <message>
       <source>STR_HVAC_HELP_SVENT</source>
       <translation>当气候控制关闭时，车内的湿度和二氧化碳含量将会增加，
空气被自动排出以维持舒适的环境</translation>
    </message>
    <message>
       <source>STR_HVAC_HELP_ADS</source>
       <translation>自动运行空调提供持续气流以清洁挡风玻璃</translation>
    </message>
</context>
<context>
    <name>CanDataBind</name>
    <message>
        <source>STR_SEATCONTROL_OSD_TITLE</source>
        <translation>Seat Control</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_LUMBAR</source>
        <translation>上下前后调整座椅腰部支撑</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_BOLSTER</source>
        <translation>向前及向後移動側墊</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_CUSHION</source>
        <translation>您可控制座椅深度。.</translation>
    </message>
    <message>
        <source>STR_Info_strDrivingNormal</source>
        <translation>NORMAL</translation>
    </message>
    <message>
        <source>STR_Info_strDrivingSports</source>
        <translation>SPORTS</translation>
    </message>
    <message>
        <source>STR_Info_strDrivingEco</source>
        <translation>ECO</translation>
    </message>
    <message>
        <source>STR_Info_strDrivingSNOW</source>
        <translation>SNOW</translation>
    </message>
</context>
<context>
    <name>DHAVN_AppSeatControl_main</name>
    <message>
        <source>STR_SEATCONTROL_BTN_LUMBAR</source>
        <translation>腰部支撑</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_BTN_BOLSTER</source>
        <translation>侧垫调节</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_BTN_CUSHION</source>
        <translation>坐垫长度可调节</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_OSD_TITLE</source>
        <translation>Seat Control</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_LUMBAR</source>
        <translation>上下前后调整座椅腰部支撑</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_BOLSTER</source>
        <translation>向前及向後移動側墊</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_CUSHION</source>
        <translation>您可控制座椅深度。.</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_LUMBAR_UP</source>
        <translation>上下前后调整座椅腰部支撑</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_LUMBAR_DOWN</source>
        <translation>上下前后调整座椅腰部支撑</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_LUMBAR_LEFT</source>
        <translation>向左移動腰靠</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_LUMBAR_RIGHT</source>
        <translation>向右移動腰靠</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_BOLSTER_LEFT</source>
        <translation>向前移動側墊</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_BOLSTER_RIGHT</source>
        <translation>向後移動側墊</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_CUSHION_LEFT</source>
        <translation>按下左側按鈕可以增加深度</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_DESC_CUSHION_RIGHT</source>
        <translation>按下右側按鈕可以減少深度</translation>
    </message>
    <message>
        <source>STR_SEATCONTROL_MODE_TITLE</source>
        <translation>Seat Comfort Control</translation>
    </message>
</context>
</TS>
