#!/bin/bash
#
# clean_xdg_dirs
#
# Copyright (C) 2007  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
ROOT_DIR=$1
export HOME=$2

if [ -f $ROOT_DIR/root/.config/user-dirs.dirs ]; then
    source $ROOT_DIR/$HOME/.config/user-dirs.dirs
    rm -rf $ROOT_DIR/$XDG_DESKTOP_DIR
    rm -rf $ROOT_DIR/$XDG_DOWNLOAD_DIR
    rm -rf $ROOT_DIR/$XDG_TEMPLATES_DIR
    rm -rf $ROOT_DIR/$XDG_PUBLICSHARE_DIR
    rm -rf $ROOT_DIR/$XDG_DOCUMENTS_DIR
    rm -rf $ROOT_DIR/$XDG_MUSIC_DIR
    rm -rf $ROOT_DIR/$XDG_PICTURES_DIR
    rm -rf $ROOT_DIR/$XDG_VIDEOS_DIR
    rm -rf $ROOT_DIR/$HOME/.config
fi
