.pragma library

var  const_SCREEN_WIDTH = 1280
var  const_SCREEN_HEIGHT = 720
var const_APP_PROJECTION_FONT_SIZE_TEXT_HDB_40_FONT = 40
var const_APP_PROJECTION_COLOR_TEXT_GREY = "#C1C1C1"
var const_APP_PROJECTION_FONT_FAMILY_NEW_HDR = "DH_HDR"
var const_APP_PROJECTION_FONT_FAMILY_NEW_HDB = "DH_HDB"
